---

- name: '[friendsvr] Create a directory if it does not exist'
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /data/PokerGo/
    - /data/PokerGo/friendsvr/
    - /data/PokerGo/logs/
    - /data/PokerGo/logs/friendsvr
  tags: 'friendsvr_init'
- name: '[friendsvr] Copy scripts'
  copy:
    src: ./scripts/server.sh
    dest: /data/PokerGo/friendsvr/server.sh
    mode: '0755'
  tags: "friendsvr_init"

- name: '[friendsvr] Copy bin'
  copy:
    src: ../build/friendsvr
    dest: /data/PokerGo/friendsvr/friendsvr
    mode: '755'
    backup: yes
  tags: "friendsvr_push"

- name: '[friendsvr] start friendsvr'
  shell: cd /data/PokerGo/friendsvr; ./server.sh start; ./server.sh check
  ignore_errors: yes
  tags: 'friendsvr_start'

- name: '[friendsvr] stop friendsvr'
  shell: cd /data/PokerGo/friendsvr; ./server.sh stop
  ignore_errors: yes
  tags: 'friendsvr_stop'

- name: '[friendsvr] restart friendsvr'
  shell: cd /data/PokerGo/friendsvr; ./server.sh restart; ./server.sh check
  ignore_errors: yes
  tags: 'friendsvr_restart'

- name: '[friendsvr] check friendsvr'
  shell: cd /data/PokerGo/friendsvr; ./server.sh check
  ignore_errors: yes
  tags: 'friendsvr_check'

- name: '[friendsvr] delLog friendsvr'
  shell: cd /data/PokerGo/logs/friendsvr; rm ./*
  ignore_errors: yes
  tags: 'friendsvr_delLog'