---

- name: '[connsvr] Create a directory if it does not exist'
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /data/PokerGo/
    - /data/PokerGo/connsvr/
    - /data/PokerGo/logs/
    - /data/PokerGo/logs/connsvr
  tags: 'connsvr_init'
- name: '[connsvr] Copy scripts'
  copy:
    src: ./scripts/server.sh
    dest: /data/PokerGo/connsvr/server.sh
    mode: '0755'
  tags: "connsvr_init"


- name: '[connsvr] Copy bin'
  copy:
    src: ../build/connsvr
    dest: /data/PokerGo/connsvr/connsvr
    mode: '0755'
    backup: yes
  tags: "connsvr_push"

- name: '[connsvr] start connsvr'
  shell: cd /data/PokerGo/connsvr; ./server.sh start; ./server.sh check
  ignore_errors: yes
  tags: 'connsvr_start'

- name: '[connsvr] stop connsvr'
  shell: cd /data/PokerGo/connsvr; ./server.sh stop
  ignore_errors: yes
  tags: 'connsvr_stop'

- name: '[connsvr] restart connsvr'
  shell: cd /data/PokerGo/connsvr; ./server.sh restart; ./server.sh check
  ignore_errors: yes
  tags: 'connsvr_restart'

- name: '[connsvr] check connsvr'
  shell: cd /data/PokerGo/connsvr; ./server.sh check
  ignore_errors: yes
  tags: 'connsvr_check'

- name: '[connsvr] delLog connsvr'
  shell: cd /data/PokerGo/logss/connsvr; rm ./*
  ignore_errors: yes
  tags: 'connsvr_delLog'
