package main

import (
	"fmt"
	"strings"
)

func renderCmdProto(pkg string, goPackage string, enumName string, hex bool, items []cmdItem, commentByName map[string]string) string {
	var b strings.Builder
	b.WriteString("syntax = \"proto3\";\n\n")
	b.WriteString(fmt.Sprintf("package %s;\n\n", pkg))
	b.WriteString(fmt.Sprintf("option go_package = %q;\n\n", goPackage))
	b.WriteString("// Code generated by tools/cmd/gencmdproto. DO NOT EDIT.\n")
	b.WriteString("// This enum mirrors github.com/Iori372552686/g1_common/protocol.CMD.\n\n")
	b.WriteString(fmt.Sprintf("enum %s {\n", enumName))

	// Emit allow_alias only when this enum actually contains aliases.
	// Newer protoc versions treat unnecessary allow_alias as an error.
	valCount := map[int32]int{}
	for _, it := range items {
		valCount[it.val]++
	}
	hasAlias := false
	for _, c := range valCount {
		if c > 1 {
			hasAlias = true
			break
		}
	}
	if hasAlias {
		b.WriteString("  option allow_alias = true;\n\n")
	}

	// If upstream has a 0-valued constant, keep it; otherwise add a local *_UNSPECIFIED = 0.
	hasZero := false
	for _, it := range items {
		if it.val == 0 {
			hasZero = true
			break
		}
	}
	if !hasZero {
		b.WriteString(fmt.Sprintf("  %s_UNSPECIFIED = 0;\n\n", enumName))
	}

	for _, it := range items {
		// Skip zero if we emitted our own *_UNSPECIFIED.
		if it.val == 0 && !hasZero {
			continue
		}

		if c := strings.TrimSpace(commentByName[it.name]); c != "" {
			for _, line := range strings.Split(c, "\n") {
				line = strings.TrimSpace(strings.TrimPrefix(line, "//"))
				if line == "" {
					continue
				}
				b.WriteString("  // " + line + "\n")
			}
		}

		if hex {
			b.WriteString(fmt.Sprintf("  %s = 0x%X;\n", it.name, uint32(it.val)))
		} else {
			b.WriteString(fmt.Sprintf("  %s = %d;\n", it.name, it.val))
		}
	}
	b.WriteString("}\n")
	return b.String()
}


