base_cfg:
  runtime:
    register_addr: '{{ zk_address }}'
    bus_mq_addr: '{{ rabbitmq_address }}'
    admin_server:
      enabled: true
      ip: ""
      port: 0
    tracing:
      enabled: false
      exporter: stdout
      endpoint: ""
      insecure: false
      sampler_ratio: 1
  dependencies:
    game_data_dir: '{{ root_path }}/gamedata'
    sensitive_words_file: '{{ root_path }}/commconf/sensitive.txt'
    http_sign:
      - index_name: default
        private_key: d1233f2b7e9885ffb8a8268d06f44c6e2
        sign_name: sign
        expired_time: 1800
        timestamp_name: timestamp
        sign_type: md5
        request_id_name: ''
    db_instances:
      - instance_id: 1
        ip: {{ redis_ip }}
        port: {{ redis_port }}
        password: {{ redis_passwd }}
        is_cluster: {{ redis_use_cluster }}
        description: role info data
      - instance_id: 3
        ip: {{ redis_ip }}
        port: {{ redis_port }}
        password: {{ redis_passwd }}
        is_cluster: {{ redis_use_cluster }}
        description: brief info data
    orm_instances:
      - index_name: default
        master:
          ip: '{{ mysql_ip }}'
          port: {{ mysql_port }}
          user: '{{ mysql_user }}'
          password: '{{ mysql_password }}'
          db_name: '{{ mysql_schema }}'
        slaves: []
        description: 'test db1'
        max_idle: 10
        max_open: 200
        show_sql: true
        init_flag: true
        drive_name: mysql
    rest_api_config:
      - service_name: default
        urls:
          - '{{LoginSdkAddr}}'
        sign_name: default
    nacos_conf:
      #ip_addr: 192.168.50.250
      port: 8848
      namespace_id: df4ad231-f231-49a1-b309-44493e949dd0
      group_name: poker_gameconf
      user_name: poker
      password: poker123
      log_dir: \tmp\nacos\log
      cache_dir: \tmp\nacos\cache
      rotate_time: 1h
      max_age: 3
      log_level: debug
  debug:
    pprof: true

connsvr:
  identity:
    self_bus_id: '1.1.1.{{ instance_id }}'
  runtime:
    listen_port: 11000
  debug:
    log_dir: ../logs/connsvr
    log_level: debug

infosvr:
  identity:
    self_bus_id: '1.1.3.{{ instance_id }}'
  debug:
    log_dir: ../logs/infosvr
    log_level: debug

mainsvr:
  identity:
    self_bus_id: '1.1.2.{{ instance_id }}'
  debug:
    log_dir: ../logs/mainsvr
    log_level: debug
  capacity:
    trans_shard_count: 0

mysqlsvr:
  identity:
    self_bus_id: '1.1.4.{{ instance_id }}'
  debug:
    log_dir: ../logs/mysqlsvr
    log_level: debug

roomcentersvr:
  identity:
    self_bus_id: '1.1.11.{{ instance_id }}'
  debug:
    log_dir: ../logs/roomcentersvr
    log_level: debug
  capacity:
    trans_shard_count: 0


websvr:
  identity:
    self_bus_id: '1.1.12.{{ instance_id }}'
  debug:
    log_dir: ./logs
    log_level: debug
  runtime:
    http_server:
      port: 10001
      session_name: GoOne@Gin.Seeeion
      mode: debug
      auth_enable: false
    grpc_server:
      enabled: false
      ip: ""
      port: 10002
