---
- hosts: all
  vars:
    password: 'Iori@123'
  tasks:
    # 1.用户
    - name: user00
      user:
        name: user00
        group: wheel
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
    # 2.依赖库
    - yum: { state: present, name: [libunwind-devel, epel-release, vim, net-tools, crontabs, psmisc, at, rsync, python2-pip, iproute, daemonize] }
    # 3.系统设置
    # 修改相关限制
    - pam_limits: { domain: user00, limit_type: soft, limit_item: core, value: 1000000000}
    - pam_limits: { domain: user00, limit_type: hard, limit_item: core, value: 1000000000}
    - pam_limits: { domain: user00, limit_type: soft, limit_item: nofile, value: 100000}
    - pam_limits: { domain: user00, limit_type: hard, limit_item: nofile, value: 100000}
    # 创建core文件存放目录
    - file:
        path: /home/user00/cores/
        owner: user00
        group: wheel
        state: directory
    # 修改core文件位置
    - sysctl:
        name: kernel.core_pattern
        value: /home/user00/cores/core_%e_%p
        sysctl_set: yes
        state: present
        reload: yes
    # 4.数据库
    - yum: { state: present, name: [redis, mariadb-server , mariadb, MySQL-python] }
    - name: start db
      service:
        name: "{{item}}"
        state: started
      with_items:
        - redis
        - mariadb
    - mysql_user:
        name: user00
        password: Iori@123
        host: localhost
        priv: '*.*:ALL,GRANT'
        state: present
#    - name: set timezone
#      timezone:
#        name: UTC

#    - pip:
#        name: pexpect
#    - pip:
#        name: futures
#    - pip:
#        name: threadpool
#    - easy_install:
#        name: pip
#        state: latest
#    - pip: { name: protobuf, version: 3.7.1 }
