---
- hosts: dst
  vars:
    password: 'Iori@123'
  tasks:
    # 1. 安装依赖库 (Ubuntu 版)
    - name: Install required packages
      apt:
        name:
          - libunwind-dev         # 替代 libunwind-devel
          - vim
          - net-tools
          - cron                  # 替代 crontabs
          - psmisc
          - at
          - htop
          - rsync
          - python3-pip
          - iproute2              # 替代 iproute
          - daemonize
          # epel-release 在 Ubuntu 中无直接对应项，需通过 PPA 或第三方仓库
        state: present
        update_cache: yes         # 相当于 apt update
      become: yes

    # 2. 系统设置
    # 修改资源限制（Ubuntu 使用 /etc/security/limits.conf）
    - name: Set core soft limit
      pam_limits:
        domain: root
        limit_type: soft
        limit_item: core
        value: 1000000000
        dest: /etc/security/limits.conf  # 显式指定路径

    - name: Set core hard limit
      pam_limits:
        domain: root
        limit_type: hard
        limit_item: core
        value: 1000000000
        dest: /etc/security/limits.conf

    - name: Set nofile soft limit
      pam_limits:
        domain: root
        limit_type: soft
        limit_item: nofile
        value: 100000
        dest: /etc/security/limits.conf

    - name: Set nofile hard limit
      pam_limits:
        domain: root
        limit_type: hard
        limit_item: nofile
        value: 100000
        dest: /etc/security/limits.conf

    # 创建 core 文件目录（Ubuntu 路径保持不变）
    - name: Create core dump directory
      file:
        path: /data/PokerGo/cores/
        owner: root
        group: root
        mode: '0755'
        state: directory
      become: yes

    # 配置核心转储路径（需要安装 procps）
    - name: Install procps for sysctl
      apt:
        name: procps
        state: present
      become: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Configure core pattern
      sysctl:
        name: kernel.core_pattern
        value: /data/PokerGo/cores/core_%e_%p
        sysctl_set: yes
        state: present
        reload: yes
      become: yes