---

- name: '[mainsvr] Create a directory if it does not exist'
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /data/PokerGo/
    - /data/PokerGo/mainsvr/
    - /data/PokerGo/logs/
    - /data/PokerGo/logs/mainsvr
  tags: 'mainsvr_init'
- name: '[mainsvr] Copy scripts'
  copy:
    src: ./scripts/server.sh
    dest: /data/PokerGo/mainsvr/server.sh
    mode: '0755'
  tags: "mainsvr_init"

- name: '[mainsvr] Copy bin'
  copy:
    src: ../build/mainsvr
    dest: /data/PokerGo/mainsvr/mainsvr
    mode: '0755'
    backup: yes
  tags: "mainsvr_push"

- name: '[mainsvr] start mainsvr'
  shell: cd /data/PokerGo/mainsvr; ./server.sh start; ./server.sh check
  ignore_errors: yes
  tags: 'mainsvr_start'

- name: '[mainsvr] stop mainsvr'
  shell: cd /data/PokerGo/mainsvr; ./server.sh stop
  ignore_errors: yes
  tags: 'mainsvr_stop'

- name: '[mainsvr] restart mainsvr'
  shell: cd /data/PokerGo/mainsvr; ./server.sh restart; ./server.sh check
  ignore_errors: yes
  tags: 'mainsvr_restart'

- name: '[mainsvr] check mainsvr'
  shell: cd /data/PokerGo/mainsvr; ./server.sh check
  ignore_errors: yes
  tags: 'mainsvr_check'

- name: '[mainsvr] delLog mainsvr'
  shell: cd /data/PokerGo/logs/mainsvr; rm ./*
  ignore_errors: yes
  tags: 'mainsvr_delLog'