---

- name: '[commconf] Create a directory if it does not exist'
  file:
    path: /home/user00/g1/commconf/
    state: directory
    mode: '0755'
  tags: 'commconf_init'

- name: '[commconf] Copy files'
  copy:
    src: ../comm_conf/
    dest: /home/user00/g1/commconf/
  tags: "commconf_push"
