---
# 用法：
# 由于ansible的文件夹层级关系，这个playbook实际运行时是被复制到上层文件夹来执行的
# vars：变量，主要定义机器的instanceID, 用于生成实例的唯一busID，进程实例busID的规则是：[worldID].[zoneID].[instanceType].[instanceID]
# vars_file: 变量文件，里面的变量用于替换进程实例配置文件中的变量，比如redis地址mysql地址等等
# roles: 机器上安装的实例类型，除了commconf，gamedata是配置文件之外，其余的都是进程实例

- hosts: devmix_1
  vars:
    - instance_id: 1
  vars_files:
    - playbook_dev/devmix_vars
  roles:
    - commconf
    - gamedata
    - connsvr
    - mainsvr
    - gmconnsvr


- hosts: devmix_2
  vars:
    - instance_id: 2
  vars_files:
    - playbook_dev/devmix_vars
  roles:
    - commconf
    - gamedata
    - mainsvr
    - dbsvr
    - gmconnsvr
    - rcmdsvr
    - infosvr
    - mysqlsvr


