// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatsvr.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PbChatMsg struct {
	Channel              int32       `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Sender               uint64      `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderIcon           *PbIconDesc `protobuf:"bytes,3,opt,name=sender_icon,json=senderIcon,proto3" json:"sender_icon,omitempty"`
	Receiver             uint64      `protobuf:"varint,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Msg                  string      `protobuf:"bytes,10,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PbChatMsg) Reset()         { *m = PbChatMsg{} }
func (m *PbChatMsg) String() string { return proto.CompactTextString(m) }
func (*PbChatMsg) ProtoMessage()    {}
func (*PbChatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c4a54de7be1588, []int{0}
}

func (m *PbChatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbChatMsg.Unmarshal(m, b)
}
func (m *PbChatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbChatMsg.Marshal(b, m, deterministic)
}
func (m *PbChatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbChatMsg.Merge(m, src)
}
func (m *PbChatMsg) XXX_Size() int {
	return xxx_messageInfo_PbChatMsg.Size(m)
}
func (m *PbChatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PbChatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PbChatMsg proto.InternalMessageInfo

func (m *PbChatMsg) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *PbChatMsg) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *PbChatMsg) GetSenderIcon() *PbIconDesc {
	if m != nil {
		return m.SenderIcon
	}
	return nil
}

func (m *PbChatMsg) GetReceiver() uint64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *PbChatMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PbChatFriendMsg struct {
	FriendUid            uint64       `protobuf:"varint,1,opt,name=friend_uid,json=friendUid,proto3" json:"friend_uid,omitempty"`
	MsgList              []*PbChatMsg `protobuf:"bytes,2,rep,name=msg_list,json=msgList,proto3" json:"msg_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PbChatFriendMsg) Reset()         { *m = PbChatFriendMsg{} }
func (m *PbChatFriendMsg) String() string { return proto.CompactTextString(m) }
func (*PbChatFriendMsg) ProtoMessage()    {}
func (*PbChatFriendMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c4a54de7be1588, []int{1}
}

func (m *PbChatFriendMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbChatFriendMsg.Unmarshal(m, b)
}
func (m *PbChatFriendMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbChatFriendMsg.Marshal(b, m, deterministic)
}
func (m *PbChatFriendMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbChatFriendMsg.Merge(m, src)
}
func (m *PbChatFriendMsg) XXX_Size() int {
	return xxx_messageInfo_PbChatFriendMsg.Size(m)
}
func (m *PbChatFriendMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PbChatFriendMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PbChatFriendMsg proto.InternalMessageInfo

func (m *PbChatFriendMsg) GetFriendUid() uint64 {
	if m != nil {
		return m.FriendUid
	}
	return 0
}

func (m *PbChatFriendMsg) GetMsgList() []*PbChatMsg {
	if m != nil {
		return m.MsgList
	}
	return nil
}

type PbChatInfo struct {
	Uid                  uint64             `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FriendMsgList        []*PbChatFriendMsg `protobuf:"bytes,2,rep,name=friend_msg_list,json=friendMsgList,proto3" json:"friend_msg_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PbChatInfo) Reset()         { *m = PbChatInfo{} }
func (m *PbChatInfo) String() string { return proto.CompactTextString(m) }
func (*PbChatInfo) ProtoMessage()    {}
func (*PbChatInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c4a54de7be1588, []int{2}
}

func (m *PbChatInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbChatInfo.Unmarshal(m, b)
}
func (m *PbChatInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbChatInfo.Marshal(b, m, deterministic)
}
func (m *PbChatInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbChatInfo.Merge(m, src)
}
func (m *PbChatInfo) XXX_Size() int {
	return xxx_messageInfo_PbChatInfo.Size(m)
}
func (m *PbChatInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PbChatInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PbChatInfo proto.InternalMessageInfo

func (m *PbChatInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PbChatInfo) GetFriendMsgList() []*PbChatFriendMsg {
	if m != nil {
		return m.FriendMsgList
	}
	return nil
}

func init() {
	proto.RegisterType((*PbChatMsg)(nil), "g1.protocol.PbChatMsg")
	proto.RegisterType((*PbChatFriendMsg)(nil), "g1.protocol.PbChatFriendMsg")
	proto.RegisterType((*PbChatInfo)(nil), "g1.protocol.PbChatInfo")
}

func init() {
	proto.RegisterFile("chatsvr.proto", fileDescriptor_50c4a54de7be1588)
}

var fileDescriptor_50c4a54de7be1588 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0x6b, 0xb3, 0x30,
	0x1c, 0xc6, 0x49, 0xf5, 0x6d, 0xeb, 0x5f, 0x4a, 0x5f, 0x72, 0xe8, 0x42, 0xd9, 0x40, 0x3c, 0x79,
	0x12, 0xda, 0x5d, 0x76, 0x5f, 0x19, 0x14, 0x36, 0x28, 0x81, 0x9d, 0x45, 0x63, 0xd4, 0x80, 0x26,
	0x23, 0xc9, 0xfa, 0x8d, 0xf6, 0x3d, 0x47, 0x8c, 0xed, 0x46, 0xd9, 0xed, 0xf9, 0x85, 0x3f, 0xcf,
	0xf3, 0x0b, 0xac, 0x58, 0x57, 0x5a, 0x73, 0xd6, 0xf9, 0x87, 0x56, 0x56, 0xe1, 0xb8, 0xdd, 0xf9,
	0xc4, 0x54, 0xbf, 0x05, 0xad, 0x7a, 0xee, 0x31, 0xfd, 0x42, 0x10, 0x9d, 0xaa, 0xe7, 0xae, 0xb4,
	0x6f, 0xa6, 0xc5, 0x04, 0x16, 0xac, 0x2b, 0xa5, 0xe4, 0x3d, 0x41, 0x09, 0xca, 0xfe, 0xd1, 0x0b,
	0xe2, 0x0d, 0xcc, 0x0d, 0x97, 0x35, 0xd7, 0x64, 0x96, 0xa0, 0x2c, 0xa4, 0x13, 0xe1, 0x27, 0x88,
	0x7d, 0x2a, 0x04, 0x53, 0x92, 0x04, 0x09, 0xca, 0xe2, 0xfd, 0x5d, 0xfe, 0x6b, 0x2e, 0x3f, 0x55,
	0x47, 0xa6, 0xe4, 0x81, 0x1b, 0x46, 0xc1, 0xdf, 0x3a, 0xc6, 0x5b, 0x58, 0x6a, 0xce, 0xb8, 0x38,
	0x73, 0x4d, 0xc2, 0xb1, 0xf3, 0xca, 0xf8, 0x3f, 0x04, 0x83, 0x69, 0x09, 0x24, 0x28, 0x8b, 0xa8,
	0x8b, 0x29, 0x83, 0xb5, 0xd7, 0x7c, 0xd1, 0x82, 0xcb, 0xda, 0xc9, 0x3e, 0x00, 0x34, 0x23, 0x14,
	0x9f, 0xa2, 0x1e, 0x7d, 0x43, 0x1a, 0xf9, 0x97, 0x77, 0x51, 0xe3, 0x1d, 0x2c, 0x07, 0xd3, 0x16,
	0xbd, 0x30, 0x96, 0xcc, 0x92, 0x20, 0x8b, 0xf7, 0x9b, 0x1b, 0xad, 0xe9, 0xd7, 0x74, 0x31, 0x98,
	0xf6, 0x55, 0x18, 0x9b, 0xd6, 0x00, 0xfe, 0xf5, 0x28, 0x1b, 0xe5, 0x24, 0x7e, 0x8a, 0x5d, 0xc4,
	0x07, 0x58, 0x4f, 0x8b, 0x37, 0xcd, 0xf7, 0x7f, 0x34, 0x5f, 0x45, 0xe9, 0xaa, 0xb9, 0x44, 0xb7,
	0x52, 0xcd, 0xc7, 0xc3, 0xc7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xe3, 0x9b, 0x81, 0xa3,
	0x01, 0x00, 0x00,
}
