// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SC_KICK_OUT
type ScKickOut struct {
	Reason               EKickOutReason `protobuf:"varint,1,opt,name=reason,proto3,enum=g1.protocol.EKickOutReason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ScKickOut) Reset()         { *m = ScKickOut{} }
func (m *ScKickOut) String() string { return proto.CompactTextString(m) }
func (*ScKickOut) ProtoMessage()    {}
func (*ScKickOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *ScKickOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScKickOut.Unmarshal(m, b)
}
func (m *ScKickOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScKickOut.Marshal(b, m, deterministic)
}
func (m *ScKickOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScKickOut.Merge(m, src)
}
func (m *ScKickOut) XXX_Size() int {
	return xxx_messageInfo_ScKickOut.Size(m)
}
func (m *ScKickOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ScKickOut.DiscardUnknown(m)
}

var xxx_messageInfo_ScKickOut proto.InternalMessageInfo

func (m *ScKickOut) GetReason() EKickOutReason {
	if m != nil {
		return m.Reason
	}
	return EKickOutReason_UNKNOWN
}

// SC_SYNC_USER_DATA
type ScSyncUserData struct {
	RoleInfo             *RoleInfo `protobuf:"bytes,1,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScSyncUserData) Reset()         { *m = ScSyncUserData{} }
func (m *ScSyncUserData) String() string { return proto.CompactTextString(m) }
func (*ScSyncUserData) ProtoMessage()    {}
func (*ScSyncUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *ScSyncUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScSyncUserData.Unmarshal(m, b)
}
func (m *ScSyncUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScSyncUserData.Marshal(b, m, deterministic)
}
func (m *ScSyncUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScSyncUserData.Merge(m, src)
}
func (m *ScSyncUserData) XXX_Size() int {
	return xxx_messageInfo_ScSyncUserData.Size(m)
}
func (m *ScSyncUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_ScSyncUserData.DiscardUnknown(m)
}

var xxx_messageInfo_ScSyncUserData proto.InternalMessageInfo

func (m *ScSyncUserData) GetRoleInfo() *RoleInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

// SC_CHAT
type ScChat struct {
	Msg                  *PbChatMsg `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ScChat) Reset()         { *m = ScChat{} }
func (m *ScChat) String() string { return proto.CompactTextString(m) }
func (*ScChat) ProtoMessage()    {}
func (*ScChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *ScChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScChat.Unmarshal(m, b)
}
func (m *ScChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScChat.Marshal(b, m, deterministic)
}
func (m *ScChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScChat.Merge(m, src)
}
func (m *ScChat) XXX_Size() int {
	return xxx_messageInfo_ScChat.Size(m)
}
func (m *ScChat) XXX_DiscardUnknown() {
	xxx_messageInfo_ScChat.DiscardUnknown(m)
}

var xxx_messageInfo_ScChat proto.InternalMessageInfo

func (m *ScChat) GetMsg() *PbChatMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

//SC_DATA_CHANGE_NOTIFY
type ScDataChangeNotify struct {
	Cmd                  int32    `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScDataChangeNotify) Reset()         { *m = ScDataChangeNotify{} }
func (m *ScDataChangeNotify) String() string { return proto.CompactTextString(m) }
func (*ScDataChangeNotify) ProtoMessage()    {}
func (*ScDataChangeNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3}
}

func (m *ScDataChangeNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScDataChangeNotify.Unmarshal(m, b)
}
func (m *ScDataChangeNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScDataChangeNotify.Marshal(b, m, deterministic)
}
func (m *ScDataChangeNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScDataChangeNotify.Merge(m, src)
}
func (m *ScDataChangeNotify) XXX_Size() int {
	return xxx_messageInfo_ScDataChangeNotify.Size(m)
}
func (m *ScDataChangeNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ScDataChangeNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ScDataChangeNotify proto.InternalMessageInfo

func (m *ScDataChangeNotify) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

// MAIN_LOGIN_REQ
type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ServerId             string   `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginReq) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

type LoginRsp struct {
	Ret                  *Ret      `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	TimeNowMs            int64     `protobuf:"varint,2,opt,name=time_now_ms,json=timeNowMs,proto3" json:"time_now_ms,omitempty"`
	RoleInfo             *RoleInfo `protobuf:"bytes,3,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{5}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *LoginRsp) GetTimeNowMs() int64 {
	if m != nil {
		return m.TimeNowMs
	}
	return 0
}

func (m *LoginRsp) GetRoleInfo() *RoleInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

// MAIN_LOGOUT_REQ
type LogoutReq struct {
	ByServer             bool     `protobuf:"varint,1,opt,name=by_server,json=byServer,proto3" json:"by_server,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{6}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetByServer() bool {
	if m != nil {
		return m.ByServer
	}
	return false
}

func (m *LogoutReq) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type LogoutRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRsp) Reset()         { *m = LogoutRsp{} }
func (m *LogoutRsp) String() string { return proto.CompactTextString(m) }
func (*LogoutRsp) ProtoMessage()    {}
func (*LogoutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{7}
}

func (m *LogoutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRsp.Unmarshal(m, b)
}
func (m *LogoutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRsp.Marshal(b, m, deterministic)
}
func (m *LogoutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRsp.Merge(m, src)
}
func (m *LogoutRsp) XXX_Size() int {
	return xxx_messageInfo_LogoutRsp.Size(m)
}
func (m *LogoutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRsp proto.InternalMessageInfo

func (m *LogoutRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// MAIN_HEARTBEAT_REQ
type HeartBeatReq struct {
	ClientNowMs          int64    `protobuf:"varint,2,opt,name=client_now_ms,json=clientNowMs,proto3" json:"client_now_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{8}
}

func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (m *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(m, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

func (m *HeartBeatReq) GetClientNowMs() int64 {
	if m != nil {
		return m.ClientNowMs
	}
	return 0
}

type HeartBeatRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ClientNowMsInReq     int64    `protobuf:"varint,2,opt,name=client_now_ms_in_req,json=clientNowMsInReq,proto3" json:"client_now_ms_in_req,omitempty"`
	ServerNowMs          int64    `protobuf:"varint,3,opt,name=server_now_ms,json=serverNowMs,proto3" json:"server_now_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRsp) Reset()         { *m = HeartBeatRsp{} }
func (m *HeartBeatRsp) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRsp) ProtoMessage()    {}
func (*HeartBeatRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{9}
}

func (m *HeartBeatRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRsp.Unmarshal(m, b)
}
func (m *HeartBeatRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRsp.Marshal(b, m, deterministic)
}
func (m *HeartBeatRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRsp.Merge(m, src)
}
func (m *HeartBeatRsp) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRsp.Size(m)
}
func (m *HeartBeatRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRsp.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRsp proto.InternalMessageInfo

func (m *HeartBeatRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *HeartBeatRsp) GetClientNowMsInReq() int64 {
	if m != nil {
		return m.ClientNowMsInReq
	}
	return 0
}

func (m *HeartBeatRsp) GetServerNowMs() int64 {
	if m != nil {
		return m.ServerNowMs
	}
	return 0
}

// MAIN_ITEM_USE_REQ
type ItemUseReq struct {
	ItemList             []*PbItem `protobuf:"bytes,1,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ItemUseReq) Reset()         { *m = ItemUseReq{} }
func (m *ItemUseReq) String() string { return proto.CompactTextString(m) }
func (*ItemUseReq) ProtoMessage()    {}
func (*ItemUseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{10}
}

func (m *ItemUseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemUseReq.Unmarshal(m, b)
}
func (m *ItemUseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemUseReq.Marshal(b, m, deterministic)
}
func (m *ItemUseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemUseReq.Merge(m, src)
}
func (m *ItemUseReq) XXX_Size() int {
	return xxx_messageInfo_ItemUseReq.Size(m)
}
func (m *ItemUseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemUseReq.DiscardUnknown(m)
}

var xxx_messageInfo_ItemUseReq proto.InternalMessageInfo

func (m *ItemUseReq) GetItemList() []*PbItem {
	if m != nil {
		return m.ItemList
	}
	return nil
}

type ItemUseRsp struct {
	Ret                  *Ret      `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	RealAddItemList      []*PbItem `protobuf:"bytes,2,rep,name=real_add_item_list,json=realAddItemList,proto3" json:"real_add_item_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ItemUseRsp) Reset()         { *m = ItemUseRsp{} }
func (m *ItemUseRsp) String() string { return proto.CompactTextString(m) }
func (*ItemUseRsp) ProtoMessage()    {}
func (*ItemUseRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{11}
}

func (m *ItemUseRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemUseRsp.Unmarshal(m, b)
}
func (m *ItemUseRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemUseRsp.Marshal(b, m, deterministic)
}
func (m *ItemUseRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemUseRsp.Merge(m, src)
}
func (m *ItemUseRsp) XXX_Size() int {
	return xxx_messageInfo_ItemUseRsp.Size(m)
}
func (m *ItemUseRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemUseRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ItemUseRsp proto.InternalMessageInfo

func (m *ItemUseRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *ItemUseRsp) GetRealAddItemList() []*PbItem {
	if m != nil {
		return m.RealAddItemList
	}
	return nil
}

// MAIN_CHANGE_NAME_REQ
type ChangeNameReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeNameReq) Reset()         { *m = ChangeNameReq{} }
func (m *ChangeNameReq) String() string { return proto.CompactTextString(m) }
func (*ChangeNameReq) ProtoMessage()    {}
func (*ChangeNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{12}
}

func (m *ChangeNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeNameReq.Unmarshal(m, b)
}
func (m *ChangeNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeNameReq.Marshal(b, m, deterministic)
}
func (m *ChangeNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeNameReq.Merge(m, src)
}
func (m *ChangeNameReq) XXX_Size() int {
	return xxx_messageInfo_ChangeNameReq.Size(m)
}
func (m *ChangeNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeNameReq proto.InternalMessageInfo

func (m *ChangeNameReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChangeNameRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeNameRsp) Reset()         { *m = ChangeNameRsp{} }
func (m *ChangeNameRsp) String() string { return proto.CompactTextString(m) }
func (*ChangeNameRsp) ProtoMessage()    {}
func (*ChangeNameRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{13}
}

func (m *ChangeNameRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeNameRsp.Unmarshal(m, b)
}
func (m *ChangeNameRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeNameRsp.Marshal(b, m, deterministic)
}
func (m *ChangeNameRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeNameRsp.Merge(m, src)
}
func (m *ChangeNameRsp) XXX_Size() int {
	return xxx_messageInfo_ChangeNameRsp.Size(m)
}
func (m *ChangeNameRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeNameRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeNameRsp proto.InternalMessageInfo

func (m *ChangeNameRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// INFO_GET_BRIEF_INFO_REQ
type InfoGetBriefInfoReq struct {
	UidList              []uint64 `protobuf:"varint,1,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoGetBriefInfoReq) Reset()         { *m = InfoGetBriefInfoReq{} }
func (m *InfoGetBriefInfoReq) String() string { return proto.CompactTextString(m) }
func (*InfoGetBriefInfoReq) ProtoMessage()    {}
func (*InfoGetBriefInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{14}
}

func (m *InfoGetBriefInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoGetBriefInfoReq.Unmarshal(m, b)
}
func (m *InfoGetBriefInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoGetBriefInfoReq.Marshal(b, m, deterministic)
}
func (m *InfoGetBriefInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoGetBriefInfoReq.Merge(m, src)
}
func (m *InfoGetBriefInfoReq) XXX_Size() int {
	return xxx_messageInfo_InfoGetBriefInfoReq.Size(m)
}
func (m *InfoGetBriefInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoGetBriefInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoGetBriefInfoReq proto.InternalMessageInfo

func (m *InfoGetBriefInfoReq) GetUidList() []uint64 {
	if m != nil {
		return m.UidList
	}
	return nil
}

type InfoGetBriefInfoRsp struct {
	Ret                  *Ret               `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	InfoList             []*PbRoleBriefInfo `protobuf:"bytes,2,rep,name=info_list,json=infoList,proto3" json:"info_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InfoGetBriefInfoRsp) Reset()         { *m = InfoGetBriefInfoRsp{} }
func (m *InfoGetBriefInfoRsp) String() string { return proto.CompactTextString(m) }
func (*InfoGetBriefInfoRsp) ProtoMessage()    {}
func (*InfoGetBriefInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{15}
}

func (m *InfoGetBriefInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoGetBriefInfoRsp.Unmarshal(m, b)
}
func (m *InfoGetBriefInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoGetBriefInfoRsp.Marshal(b, m, deterministic)
}
func (m *InfoGetBriefInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoGetBriefInfoRsp.Merge(m, src)
}
func (m *InfoGetBriefInfoRsp) XXX_Size() int {
	return xxx_messageInfo_InfoGetBriefInfoRsp.Size(m)
}
func (m *InfoGetBriefInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoGetBriefInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_InfoGetBriefInfoRsp proto.InternalMessageInfo

func (m *InfoGetBriefInfoRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *InfoGetBriefInfoRsp) GetInfoList() []*PbRoleBriefInfo {
	if m != nil {
		return m.InfoList
	}
	return nil
}

// INFO_GET_ICON_DESC_REQ
type InfoGetIconDescReq struct {
	UidList              []uint64 `protobuf:"varint,1,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoGetIconDescReq) Reset()         { *m = InfoGetIconDescReq{} }
func (m *InfoGetIconDescReq) String() string { return proto.CompactTextString(m) }
func (*InfoGetIconDescReq) ProtoMessage()    {}
func (*InfoGetIconDescReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{16}
}

func (m *InfoGetIconDescReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoGetIconDescReq.Unmarshal(m, b)
}
func (m *InfoGetIconDescReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoGetIconDescReq.Marshal(b, m, deterministic)
}
func (m *InfoGetIconDescReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoGetIconDescReq.Merge(m, src)
}
func (m *InfoGetIconDescReq) XXX_Size() int {
	return xxx_messageInfo_InfoGetIconDescReq.Size(m)
}
func (m *InfoGetIconDescReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoGetIconDescReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoGetIconDescReq proto.InternalMessageInfo

func (m *InfoGetIconDescReq) GetUidList() []uint64 {
	if m != nil {
		return m.UidList
	}
	return nil
}

type InfoGetIconDescRsp struct {
	Ret                  *Ret          `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	IconList             []*PbIconDesc `protobuf:"bytes,2,rep,name=icon_list,json=iconList,proto3" json:"icon_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InfoGetIconDescRsp) Reset()         { *m = InfoGetIconDescRsp{} }
func (m *InfoGetIconDescRsp) String() string { return proto.CompactTextString(m) }
func (*InfoGetIconDescRsp) ProtoMessage()    {}
func (*InfoGetIconDescRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{17}
}

func (m *InfoGetIconDescRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoGetIconDescRsp.Unmarshal(m, b)
}
func (m *InfoGetIconDescRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoGetIconDescRsp.Marshal(b, m, deterministic)
}
func (m *InfoGetIconDescRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoGetIconDescRsp.Merge(m, src)
}
func (m *InfoGetIconDescRsp) XXX_Size() int {
	return xxx_messageInfo_InfoGetIconDescRsp.Size(m)
}
func (m *InfoGetIconDescRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoGetIconDescRsp.DiscardUnknown(m)
}

var xxx_messageInfo_InfoGetIconDescRsp proto.InternalMessageInfo

func (m *InfoGetIconDescRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *InfoGetIconDescRsp) GetIconList() []*PbIconDesc {
	if m != nil {
		return m.IconList
	}
	return nil
}

// MAIL_GET_MAIL_LIST_REQ
type GetMailListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMailListReq) Reset()         { *m = GetMailListReq{} }
func (m *GetMailListReq) String() string { return proto.CompactTextString(m) }
func (*GetMailListReq) ProtoMessage()    {}
func (*GetMailListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{18}
}

func (m *GetMailListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMailListReq.Unmarshal(m, b)
}
func (m *GetMailListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMailListReq.Marshal(b, m, deterministic)
}
func (m *GetMailListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMailListReq.Merge(m, src)
}
func (m *GetMailListReq) XXX_Size() int {
	return xxx_messageInfo_GetMailListReq.Size(m)
}
func (m *GetMailListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMailListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMailListReq proto.InternalMessageInfo

type GetMailListRsp struct {
	Ret                  *Ret      `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	MailInfo             *MailInfo `protobuf:"bytes,2,opt,name=mail_info,json=mailInfo,proto3" json:"mail_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetMailListRsp) Reset()         { *m = GetMailListRsp{} }
func (m *GetMailListRsp) String() string { return proto.CompactTextString(m) }
func (*GetMailListRsp) ProtoMessage()    {}
func (*GetMailListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{19}
}

func (m *GetMailListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMailListRsp.Unmarshal(m, b)
}
func (m *GetMailListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMailListRsp.Marshal(b, m, deterministic)
}
func (m *GetMailListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMailListRsp.Merge(m, src)
}
func (m *GetMailListRsp) XXX_Size() int {
	return xxx_messageInfo_GetMailListRsp.Size(m)
}
func (m *GetMailListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMailListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMailListRsp proto.InternalMessageInfo

func (m *GetMailListRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *GetMailListRsp) GetMailInfo() *MailInfo {
	if m != nil {
		return m.MailInfo
	}
	return nil
}

// MAIL_READ_MAIL_REQ
type ReadMailReq struct {
	IdList               []int32  `protobuf:"varint,1,rep,packed,name=id_list,json=idList,proto3" json:"id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMailReq) Reset()         { *m = ReadMailReq{} }
func (m *ReadMailReq) String() string { return proto.CompactTextString(m) }
func (*ReadMailReq) ProtoMessage()    {}
func (*ReadMailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{20}
}

func (m *ReadMailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMailReq.Unmarshal(m, b)
}
func (m *ReadMailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMailReq.Marshal(b, m, deterministic)
}
func (m *ReadMailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMailReq.Merge(m, src)
}
func (m *ReadMailReq) XXX_Size() int {
	return xxx_messageInfo_ReadMailReq.Size(m)
}
func (m *ReadMailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMailReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMailReq proto.InternalMessageInfo

func (m *ReadMailReq) GetIdList() []int32 {
	if m != nil {
		return m.IdList
	}
	return nil
}

type ReadMailRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	IdList               []int32  `protobuf:"varint,2,rep,packed,name=id_list,json=idList,proto3" json:"id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMailRsp) Reset()         { *m = ReadMailRsp{} }
func (m *ReadMailRsp) String() string { return proto.CompactTextString(m) }
func (*ReadMailRsp) ProtoMessage()    {}
func (*ReadMailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{21}
}

func (m *ReadMailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMailRsp.Unmarshal(m, b)
}
func (m *ReadMailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMailRsp.Marshal(b, m, deterministic)
}
func (m *ReadMailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMailRsp.Merge(m, src)
}
func (m *ReadMailRsp) XXX_Size() int {
	return xxx_messageInfo_ReadMailRsp.Size(m)
}
func (m *ReadMailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMailRsp proto.InternalMessageInfo

func (m *ReadMailRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *ReadMailRsp) GetIdList() []int32 {
	if m != nil {
		return m.IdList
	}
	return nil
}

// MAIL_DEL_MAIL_REQ
type DelMailReq struct {
	IdList               []int32  `protobuf:"varint,1,rep,packed,name=id_list,json=idList,proto3" json:"id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelMailReq) Reset()         { *m = DelMailReq{} }
func (m *DelMailReq) String() string { return proto.CompactTextString(m) }
func (*DelMailReq) ProtoMessage()    {}
func (*DelMailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{22}
}

func (m *DelMailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelMailReq.Unmarshal(m, b)
}
func (m *DelMailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelMailReq.Marshal(b, m, deterministic)
}
func (m *DelMailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelMailReq.Merge(m, src)
}
func (m *DelMailReq) XXX_Size() int {
	return xxx_messageInfo_DelMailReq.Size(m)
}
func (m *DelMailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelMailReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelMailReq proto.InternalMessageInfo

func (m *DelMailReq) GetIdList() []int32 {
	if m != nil {
		return m.IdList
	}
	return nil
}

type DelMailRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	IdList               []int32  `protobuf:"varint,2,rep,packed,name=id_list,json=idList,proto3" json:"id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelMailRsp) Reset()         { *m = DelMailRsp{} }
func (m *DelMailRsp) String() string { return proto.CompactTextString(m) }
func (*DelMailRsp) ProtoMessage()    {}
func (*DelMailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{23}
}

func (m *DelMailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelMailRsp.Unmarshal(m, b)
}
func (m *DelMailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelMailRsp.Marshal(b, m, deterministic)
}
func (m *DelMailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelMailRsp.Merge(m, src)
}
func (m *DelMailRsp) XXX_Size() int {
	return xxx_messageInfo_DelMailRsp.Size(m)
}
func (m *DelMailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelMailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DelMailRsp proto.InternalMessageInfo

func (m *DelMailRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DelMailRsp) GetIdList() []int32 {
	if m != nil {
		return m.IdList
	}
	return nil
}

// MAIL_GET_MAIL_ATTACH_REQ
type GetMailAttachReq struct {
	IdList               []int32  `protobuf:"varint,1,rep,packed,name=id_list,json=idList,proto3" json:"id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMailAttachReq) Reset()         { *m = GetMailAttachReq{} }
func (m *GetMailAttachReq) String() string { return proto.CompactTextString(m) }
func (*GetMailAttachReq) ProtoMessage()    {}
func (*GetMailAttachReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{24}
}

func (m *GetMailAttachReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMailAttachReq.Unmarshal(m, b)
}
func (m *GetMailAttachReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMailAttachReq.Marshal(b, m, deterministic)
}
func (m *GetMailAttachReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMailAttachReq.Merge(m, src)
}
func (m *GetMailAttachReq) XXX_Size() int {
	return xxx_messageInfo_GetMailAttachReq.Size(m)
}
func (m *GetMailAttachReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMailAttachReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMailAttachReq proto.InternalMessageInfo

func (m *GetMailAttachReq) GetIdList() []int32 {
	if m != nil {
		return m.IdList
	}
	return nil
}

type GetMailAttachRsp struct {
	Ret                  *Ret      `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	IdList               []int32   `protobuf:"varint,2,rep,packed,name=id_list,json=idList,proto3" json:"id_list,omitempty"`
	ItemList             []*PbItem `protobuf:"bytes,3,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetMailAttachRsp) Reset()         { *m = GetMailAttachRsp{} }
func (m *GetMailAttachRsp) String() string { return proto.CompactTextString(m) }
func (*GetMailAttachRsp) ProtoMessage()    {}
func (*GetMailAttachRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{25}
}

func (m *GetMailAttachRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMailAttachRsp.Unmarshal(m, b)
}
func (m *GetMailAttachRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMailAttachRsp.Marshal(b, m, deterministic)
}
func (m *GetMailAttachRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMailAttachRsp.Merge(m, src)
}
func (m *GetMailAttachRsp) XXX_Size() int {
	return xxx_messageInfo_GetMailAttachRsp.Size(m)
}
func (m *GetMailAttachRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMailAttachRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMailAttachRsp proto.InternalMessageInfo

func (m *GetMailAttachRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *GetMailAttachRsp) GetIdList() []int32 {
	if m != nil {
		return m.IdList
	}
	return nil
}

func (m *GetMailAttachRsp) GetItemList() []*PbItem {
	if m != nil {
		return m.ItemList
	}
	return nil
}

// CHAT_CHAT_REQ
type ChatChatReq struct {
	Msg                  *PbChatMsg `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChatChatReq) Reset()         { *m = ChatChatReq{} }
func (m *ChatChatReq) String() string { return proto.CompactTextString(m) }
func (*ChatChatReq) ProtoMessage()    {}
func (*ChatChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{26}
}

func (m *ChatChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatChatReq.Unmarshal(m, b)
}
func (m *ChatChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatChatReq.Marshal(b, m, deterministic)
}
func (m *ChatChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatChatReq.Merge(m, src)
}
func (m *ChatChatReq) XXX_Size() int {
	return xxx_messageInfo_ChatChatReq.Size(m)
}
func (m *ChatChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatChatReq proto.InternalMessageInfo

func (m *ChatChatReq) GetMsg() *PbChatMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type ChatChatRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatChatRsp) Reset()         { *m = ChatChatRsp{} }
func (m *ChatChatRsp) String() string { return proto.CompactTextString(m) }
func (*ChatChatRsp) ProtoMessage()    {}
func (*ChatChatRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{27}
}

func (m *ChatChatRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatChatRsp.Unmarshal(m, b)
}
func (m *ChatChatRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatChatRsp.Marshal(b, m, deterministic)
}
func (m *ChatChatRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatChatRsp.Merge(m, src)
}
func (m *ChatChatRsp) XXX_Size() int {
	return xxx_messageInfo_ChatChatRsp.Size(m)
}
func (m *ChatChatRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatChatRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatChatRsp proto.InternalMessageInfo

func (m *ChatChatRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// CHAT_GET_CHAT_INFO_REQ
type ChatGetChatInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatGetChatInfoReq) Reset()         { *m = ChatGetChatInfoReq{} }
func (m *ChatGetChatInfoReq) String() string { return proto.CompactTextString(m) }
func (*ChatGetChatInfoReq) ProtoMessage()    {}
func (*ChatGetChatInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{28}
}

func (m *ChatGetChatInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatGetChatInfoReq.Unmarshal(m, b)
}
func (m *ChatGetChatInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatGetChatInfoReq.Marshal(b, m, deterministic)
}
func (m *ChatGetChatInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatGetChatInfoReq.Merge(m, src)
}
func (m *ChatGetChatInfoReq) XXX_Size() int {
	return xxx_messageInfo_ChatGetChatInfoReq.Size(m)
}
func (m *ChatGetChatInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatGetChatInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatGetChatInfoReq proto.InternalMessageInfo

type ChatGetChatInfoRsp struct {
	Ret                  *Ret        `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ChatInfo             *PbChatInfo `protobuf:"bytes,2,opt,name=chat_info,json=chatInfo,proto3" json:"chat_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChatGetChatInfoRsp) Reset()         { *m = ChatGetChatInfoRsp{} }
func (m *ChatGetChatInfoRsp) String() string { return proto.CompactTextString(m) }
func (*ChatGetChatInfoRsp) ProtoMessage()    {}
func (*ChatGetChatInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{29}
}

func (m *ChatGetChatInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatGetChatInfoRsp.Unmarshal(m, b)
}
func (m *ChatGetChatInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatGetChatInfoRsp.Marshal(b, m, deterministic)
}
func (m *ChatGetChatInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatGetChatInfoRsp.Merge(m, src)
}
func (m *ChatGetChatInfoRsp) XXX_Size() int {
	return xxx_messageInfo_ChatGetChatInfoRsp.Size(m)
}
func (m *ChatGetChatInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatGetChatInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatGetChatInfoRsp proto.InternalMessageInfo

func (m *ChatGetChatInfoRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *ChatGetChatInfoRsp) GetChatInfo() *PbChatInfo {
	if m != nil {
		return m.ChatInfo
	}
	return nil
}

// CHAT_DEL_CHAT_REQ
type ChatDelChatReq struct {
	FriendUid            uint64   `protobuf:"varint,1,opt,name=friend_uid,json=friendUid,proto3" json:"friend_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatDelChatReq) Reset()         { *m = ChatDelChatReq{} }
func (m *ChatDelChatReq) String() string { return proto.CompactTextString(m) }
func (*ChatDelChatReq) ProtoMessage()    {}
func (*ChatDelChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{30}
}

func (m *ChatDelChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatDelChatReq.Unmarshal(m, b)
}
func (m *ChatDelChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatDelChatReq.Marshal(b, m, deterministic)
}
func (m *ChatDelChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatDelChatReq.Merge(m, src)
}
func (m *ChatDelChatReq) XXX_Size() int {
	return xxx_messageInfo_ChatDelChatReq.Size(m)
}
func (m *ChatDelChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatDelChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatDelChatReq proto.InternalMessageInfo

func (m *ChatDelChatReq) GetFriendUid() uint64 {
	if m != nil {
		return m.FriendUid
	}
	return 0
}

type ChatDelChatRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatDelChatRsp) Reset()         { *m = ChatDelChatRsp{} }
func (m *ChatDelChatRsp) String() string { return proto.CompactTextString(m) }
func (*ChatDelChatRsp) ProtoMessage()    {}
func (*ChatDelChatRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{31}
}

func (m *ChatDelChatRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatDelChatRsp.Unmarshal(m, b)
}
func (m *ChatDelChatRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatDelChatRsp.Marshal(b, m, deterministic)
}
func (m *ChatDelChatRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatDelChatRsp.Merge(m, src)
}
func (m *ChatDelChatRsp) XXX_Size() int {
	return xxx_messageInfo_ChatDelChatRsp.Size(m)
}
func (m *ChatDelChatRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatDelChatRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatDelChatRsp proto.InternalMessageInfo

func (m *ChatDelChatRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// FRIEND_GET_FRIEND_INFO_REQ
type FriendGetFriendInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendGetFriendInfoReq) Reset()         { *m = FriendGetFriendInfoReq{} }
func (m *FriendGetFriendInfoReq) String() string { return proto.CompactTextString(m) }
func (*FriendGetFriendInfoReq) ProtoMessage()    {}
func (*FriendGetFriendInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{32}
}

func (m *FriendGetFriendInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendGetFriendInfoReq.Unmarshal(m, b)
}
func (m *FriendGetFriendInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendGetFriendInfoReq.Marshal(b, m, deterministic)
}
func (m *FriendGetFriendInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendGetFriendInfoReq.Merge(m, src)
}
func (m *FriendGetFriendInfoReq) XXX_Size() int {
	return xxx_messageInfo_FriendGetFriendInfoReq.Size(m)
}
func (m *FriendGetFriendInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendGetFriendInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_FriendGetFriendInfoReq proto.InternalMessageInfo

type FriendGetFriendInfoRsp struct {
	Ret                  *Ret            `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	FriendInfo           *RoleFriendInfo `protobuf:"bytes,2,opt,name=friend_info,json=friendInfo,proto3" json:"friend_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FriendGetFriendInfoRsp) Reset()         { *m = FriendGetFriendInfoRsp{} }
func (m *FriendGetFriendInfoRsp) String() string { return proto.CompactTextString(m) }
func (*FriendGetFriendInfoRsp) ProtoMessage()    {}
func (*FriendGetFriendInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{33}
}

func (m *FriendGetFriendInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendGetFriendInfoRsp.Unmarshal(m, b)
}
func (m *FriendGetFriendInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendGetFriendInfoRsp.Marshal(b, m, deterministic)
}
func (m *FriendGetFriendInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendGetFriendInfoRsp.Merge(m, src)
}
func (m *FriendGetFriendInfoRsp) XXX_Size() int {
	return xxx_messageInfo_FriendGetFriendInfoRsp.Size(m)
}
func (m *FriendGetFriendInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendGetFriendInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FriendGetFriendInfoRsp proto.InternalMessageInfo

func (m *FriendGetFriendInfoRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *FriendGetFriendInfoRsp) GetFriendInfo() *RoleFriendInfo {
	if m != nil {
		return m.FriendInfo
	}
	return nil
}

// FRIEND_ADD_FRIEND_REQ
type FriendAddFriendReq struct {
	FriendUid            uint64   `protobuf:"varint,1,opt,name=friend_uid,json=friendUid,proto3" json:"friend_uid,omitempty"`
	IsDelFriend          bool     `protobuf:"varint,2,opt,name=is_del_friend,json=isDelFriend,proto3" json:"is_del_friend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendAddFriendReq) Reset()         { *m = FriendAddFriendReq{} }
func (m *FriendAddFriendReq) String() string { return proto.CompactTextString(m) }
func (*FriendAddFriendReq) ProtoMessage()    {}
func (*FriendAddFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{34}
}

func (m *FriendAddFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendAddFriendReq.Unmarshal(m, b)
}
func (m *FriendAddFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendAddFriendReq.Marshal(b, m, deterministic)
}
func (m *FriendAddFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendAddFriendReq.Merge(m, src)
}
func (m *FriendAddFriendReq) XXX_Size() int {
	return xxx_messageInfo_FriendAddFriendReq.Size(m)
}
func (m *FriendAddFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendAddFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_FriendAddFriendReq proto.InternalMessageInfo

func (m *FriendAddFriendReq) GetFriendUid() uint64 {
	if m != nil {
		return m.FriendUid
	}
	return 0
}

func (m *FriendAddFriendReq) GetIsDelFriend() bool {
	if m != nil {
		return m.IsDelFriend
	}
	return false
}

type FriendAddFriendRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	FriendUid            uint64   `protobuf:"varint,2,opt,name=friend_uid,json=friendUid,proto3" json:"friend_uid,omitempty"`
	IsDelFriend          bool     `protobuf:"varint,3,opt,name=is_del_friend,json=isDelFriend,proto3" json:"is_del_friend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendAddFriendRsp) Reset()         { *m = FriendAddFriendRsp{} }
func (m *FriendAddFriendRsp) String() string { return proto.CompactTextString(m) }
func (*FriendAddFriendRsp) ProtoMessage()    {}
func (*FriendAddFriendRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{35}
}

func (m *FriendAddFriendRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendAddFriendRsp.Unmarshal(m, b)
}
func (m *FriendAddFriendRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendAddFriendRsp.Marshal(b, m, deterministic)
}
func (m *FriendAddFriendRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendAddFriendRsp.Merge(m, src)
}
func (m *FriendAddFriendRsp) XXX_Size() int {
	return xxx_messageInfo_FriendAddFriendRsp.Size(m)
}
func (m *FriendAddFriendRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendAddFriendRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FriendAddFriendRsp proto.InternalMessageInfo

func (m *FriendAddFriendRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *FriendAddFriendRsp) GetFriendUid() uint64 {
	if m != nil {
		return m.FriendUid
	}
	return 0
}

func (m *FriendAddFriendRsp) GetIsDelFriend() bool {
	if m != nil {
		return m.IsDelFriend
	}
	return false
}

// FRIEND_CONFIRM_FRIEND_REQ
type FriendConfirmFriendReq struct {
	FriendUid            uint64   `protobuf:"varint,1,opt,name=friend_uid,json=friendUid,proto3" json:"friend_uid,omitempty"`
	IsReject             bool     `protobuf:"varint,2,opt,name=is_reject,json=isReject,proto3" json:"is_reject,omitempty"`
	AllInvitation        bool     `protobuf:"varint,3,opt,name=all_invitation,json=allInvitation,proto3" json:"all_invitation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendConfirmFriendReq) Reset()         { *m = FriendConfirmFriendReq{} }
func (m *FriendConfirmFriendReq) String() string { return proto.CompactTextString(m) }
func (*FriendConfirmFriendReq) ProtoMessage()    {}
func (*FriendConfirmFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{36}
}

func (m *FriendConfirmFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendConfirmFriendReq.Unmarshal(m, b)
}
func (m *FriendConfirmFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendConfirmFriendReq.Marshal(b, m, deterministic)
}
func (m *FriendConfirmFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendConfirmFriendReq.Merge(m, src)
}
func (m *FriendConfirmFriendReq) XXX_Size() int {
	return xxx_messageInfo_FriendConfirmFriendReq.Size(m)
}
func (m *FriendConfirmFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendConfirmFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_FriendConfirmFriendReq proto.InternalMessageInfo

func (m *FriendConfirmFriendReq) GetFriendUid() uint64 {
	if m != nil {
		return m.FriendUid
	}
	return 0
}

func (m *FriendConfirmFriendReq) GetIsReject() bool {
	if m != nil {
		return m.IsReject
	}
	return false
}

func (m *FriendConfirmFriendReq) GetAllInvitation() bool {
	if m != nil {
		return m.AllInvitation
	}
	return false
}

type FriendConfirmFriendRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	FriendUid            uint64   `protobuf:"varint,2,opt,name=friend_uid,json=friendUid,proto3" json:"friend_uid,omitempty"`
	IsReject             bool     `protobuf:"varint,3,opt,name=is_reject,json=isReject,proto3" json:"is_reject,omitempty"`
	AllInvitation        bool     `protobuf:"varint,4,opt,name=all_invitation,json=allInvitation,proto3" json:"all_invitation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendConfirmFriendRsp) Reset()         { *m = FriendConfirmFriendRsp{} }
func (m *FriendConfirmFriendRsp) String() string { return proto.CompactTextString(m) }
func (*FriendConfirmFriendRsp) ProtoMessage()    {}
func (*FriendConfirmFriendRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{37}
}

func (m *FriendConfirmFriendRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendConfirmFriendRsp.Unmarshal(m, b)
}
func (m *FriendConfirmFriendRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendConfirmFriendRsp.Marshal(b, m, deterministic)
}
func (m *FriendConfirmFriendRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendConfirmFriendRsp.Merge(m, src)
}
func (m *FriendConfirmFriendRsp) XXX_Size() int {
	return xxx_messageInfo_FriendConfirmFriendRsp.Size(m)
}
func (m *FriendConfirmFriendRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendConfirmFriendRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FriendConfirmFriendRsp proto.InternalMessageInfo

func (m *FriendConfirmFriendRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *FriendConfirmFriendRsp) GetFriendUid() uint64 {
	if m != nil {
		return m.FriendUid
	}
	return 0
}

func (m *FriendConfirmFriendRsp) GetIsReject() bool {
	if m != nil {
		return m.IsReject
	}
	return false
}

func (m *FriendConfirmFriendRsp) GetAllInvitation() bool {
	if m != nil {
		return m.AllInvitation
	}
	return false
}

// FRIEND_SHIELD_USER_REQ
type FriendShieldUserReq struct {
	ShieldUid            uint64   `protobuf:"varint,1,opt,name=shield_uid,json=shieldUid,proto3" json:"shield_uid,omitempty"`
	IsCancelShield       bool     `protobuf:"varint,2,opt,name=is_cancel_shield,json=isCancelShield,proto3" json:"is_cancel_shield,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendShieldUserReq) Reset()         { *m = FriendShieldUserReq{} }
func (m *FriendShieldUserReq) String() string { return proto.CompactTextString(m) }
func (*FriendShieldUserReq) ProtoMessage()    {}
func (*FriendShieldUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{38}
}

func (m *FriendShieldUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendShieldUserReq.Unmarshal(m, b)
}
func (m *FriendShieldUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendShieldUserReq.Marshal(b, m, deterministic)
}
func (m *FriendShieldUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendShieldUserReq.Merge(m, src)
}
func (m *FriendShieldUserReq) XXX_Size() int {
	return xxx_messageInfo_FriendShieldUserReq.Size(m)
}
func (m *FriendShieldUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendShieldUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_FriendShieldUserReq proto.InternalMessageInfo

func (m *FriendShieldUserReq) GetShieldUid() uint64 {
	if m != nil {
		return m.ShieldUid
	}
	return 0
}

func (m *FriendShieldUserReq) GetIsCancelShield() bool {
	if m != nil {
		return m.IsCancelShield
	}
	return false
}

type FriendShieldUserRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ShieldUid            uint64   `protobuf:"varint,2,opt,name=shield_uid,json=shieldUid,proto3" json:"shield_uid,omitempty"`
	IsCancelShield       bool     `protobuf:"varint,3,opt,name=is_cancel_shield,json=isCancelShield,proto3" json:"is_cancel_shield,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendShieldUserRsp) Reset()         { *m = FriendShieldUserRsp{} }
func (m *FriendShieldUserRsp) String() string { return proto.CompactTextString(m) }
func (*FriendShieldUserRsp) ProtoMessage()    {}
func (*FriendShieldUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{39}
}

func (m *FriendShieldUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendShieldUserRsp.Unmarshal(m, b)
}
func (m *FriendShieldUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendShieldUserRsp.Marshal(b, m, deterministic)
}
func (m *FriendShieldUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendShieldUserRsp.Merge(m, src)
}
func (m *FriendShieldUserRsp) XXX_Size() int {
	return xxx_messageInfo_FriendShieldUserRsp.Size(m)
}
func (m *FriendShieldUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendShieldUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FriendShieldUserRsp proto.InternalMessageInfo

func (m *FriendShieldUserRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *FriendShieldUserRsp) GetShieldUid() uint64 {
	if m != nil {
		return m.ShieldUid
	}
	return 0
}

func (m *FriendShieldUserRsp) GetIsCancelShield() bool {
	if m != nil {
		return m.IsCancelShield
	}
	return false
}

// FRIEND_SEARCH_ROLE_REQ
type FriendSearchRoleReq struct {
	SearchString         string   `protobuf:"bytes,1,opt,name=search_string,json=searchString,proto3" json:"search_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendSearchRoleReq) Reset()         { *m = FriendSearchRoleReq{} }
func (m *FriendSearchRoleReq) String() string { return proto.CompactTextString(m) }
func (*FriendSearchRoleReq) ProtoMessage()    {}
func (*FriendSearchRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{40}
}

func (m *FriendSearchRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendSearchRoleReq.Unmarshal(m, b)
}
func (m *FriendSearchRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendSearchRoleReq.Marshal(b, m, deterministic)
}
func (m *FriendSearchRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendSearchRoleReq.Merge(m, src)
}
func (m *FriendSearchRoleReq) XXX_Size() int {
	return xxx_messageInfo_FriendSearchRoleReq.Size(m)
}
func (m *FriendSearchRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendSearchRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_FriendSearchRoleReq proto.InternalMessageInfo

func (m *FriendSearchRoleReq) GetSearchString() string {
	if m != nil {
		return m.SearchString
	}
	return ""
}

type FriendSearchRoleRsp struct {
	Ret                  *Ret          `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	RoleList             []*PbIconDesc `protobuf:"bytes,2,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FriendSearchRoleRsp) Reset()         { *m = FriendSearchRoleRsp{} }
func (m *FriendSearchRoleRsp) String() string { return proto.CompactTextString(m) }
func (*FriendSearchRoleRsp) ProtoMessage()    {}
func (*FriendSearchRoleRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{41}
}

func (m *FriendSearchRoleRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendSearchRoleRsp.Unmarshal(m, b)
}
func (m *FriendSearchRoleRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendSearchRoleRsp.Marshal(b, m, deterministic)
}
func (m *FriendSearchRoleRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendSearchRoleRsp.Merge(m, src)
}
func (m *FriendSearchRoleRsp) XXX_Size() int {
	return xxx_messageInfo_FriendSearchRoleRsp.Size(m)
}
func (m *FriendSearchRoleRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendSearchRoleRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FriendSearchRoleRsp proto.InternalMessageInfo

func (m *FriendSearchRoleRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *FriendSearchRoleRsp) GetRoleList() []*PbIconDesc {
	if m != nil {
		return m.RoleList
	}
	return nil
}

func init() {
	proto.RegisterType((*ScKickOut)(nil), "g1.protocol.ScKickOut")
	proto.RegisterType((*ScSyncUserData)(nil), "g1.protocol.ScSyncUserData")
	proto.RegisterType((*ScChat)(nil), "g1.protocol.ScChat")
	proto.RegisterType((*ScDataChangeNotify)(nil), "g1.protocol.ScDataChangeNotify")
	proto.RegisterType((*LoginReq)(nil), "g1.protocol.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "g1.protocol.LoginRsp")
	proto.RegisterType((*LogoutReq)(nil), "g1.protocol.LogoutReq")
	proto.RegisterType((*LogoutRsp)(nil), "g1.protocol.LogoutRsp")
	proto.RegisterType((*HeartBeatReq)(nil), "g1.protocol.HeartBeatReq")
	proto.RegisterType((*HeartBeatRsp)(nil), "g1.protocol.HeartBeatRsp")
	proto.RegisterType((*ItemUseReq)(nil), "g1.protocol.ItemUseReq")
	proto.RegisterType((*ItemUseRsp)(nil), "g1.protocol.ItemUseRsp")
	proto.RegisterType((*ChangeNameReq)(nil), "g1.protocol.ChangeNameReq")
	proto.RegisterType((*ChangeNameRsp)(nil), "g1.protocol.ChangeNameRsp")
	proto.RegisterType((*InfoGetBriefInfoReq)(nil), "g1.protocol.InfoGetBriefInfoReq")
	proto.RegisterType((*InfoGetBriefInfoRsp)(nil), "g1.protocol.InfoGetBriefInfoRsp")
	proto.RegisterType((*InfoGetIconDescReq)(nil), "g1.protocol.InfoGetIconDescReq")
	proto.RegisterType((*InfoGetIconDescRsp)(nil), "g1.protocol.InfoGetIconDescRsp")
	proto.RegisterType((*GetMailListReq)(nil), "g1.protocol.GetMailListReq")
	proto.RegisterType((*GetMailListRsp)(nil), "g1.protocol.GetMailListRsp")
	proto.RegisterType((*ReadMailReq)(nil), "g1.protocol.ReadMailReq")
	proto.RegisterType((*ReadMailRsp)(nil), "g1.protocol.ReadMailRsp")
	proto.RegisterType((*DelMailReq)(nil), "g1.protocol.DelMailReq")
	proto.RegisterType((*DelMailRsp)(nil), "g1.protocol.DelMailRsp")
	proto.RegisterType((*GetMailAttachReq)(nil), "g1.protocol.GetMailAttachReq")
	proto.RegisterType((*GetMailAttachRsp)(nil), "g1.protocol.GetMailAttachRsp")
	proto.RegisterType((*ChatChatReq)(nil), "g1.protocol.ChatChatReq")
	proto.RegisterType((*ChatChatRsp)(nil), "g1.protocol.ChatChatRsp")
	proto.RegisterType((*ChatGetChatInfoReq)(nil), "g1.protocol.ChatGetChatInfoReq")
	proto.RegisterType((*ChatGetChatInfoRsp)(nil), "g1.protocol.ChatGetChatInfoRsp")
	proto.RegisterType((*ChatDelChatReq)(nil), "g1.protocol.ChatDelChatReq")
	proto.RegisterType((*ChatDelChatRsp)(nil), "g1.protocol.ChatDelChatRsp")
	proto.RegisterType((*FriendGetFriendInfoReq)(nil), "g1.protocol.FriendGetFriendInfoReq")
	proto.RegisterType((*FriendGetFriendInfoRsp)(nil), "g1.protocol.FriendGetFriendInfoRsp")
	proto.RegisterType((*FriendAddFriendReq)(nil), "g1.protocol.FriendAddFriendReq")
	proto.RegisterType((*FriendAddFriendRsp)(nil), "g1.protocol.FriendAddFriendRsp")
	proto.RegisterType((*FriendConfirmFriendReq)(nil), "g1.protocol.FriendConfirmFriendReq")
	proto.RegisterType((*FriendConfirmFriendRsp)(nil), "g1.protocol.FriendConfirmFriendRsp")
	proto.RegisterType((*FriendShieldUserReq)(nil), "g1.protocol.FriendShieldUserReq")
	proto.RegisterType((*FriendShieldUserRsp)(nil), "g1.protocol.FriendShieldUserRsp")
	proto.RegisterType((*FriendSearchRoleReq)(nil), "g1.protocol.FriendSearchRoleReq")
	proto.RegisterType((*FriendSearchRoleRsp)(nil), "g1.protocol.FriendSearchRoleRsp")
}

func init() {
	proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c)
}

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 1053 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x51, 0x6f, 0x23, 0x35,
	0x10, 0x56, 0xb2, 0xbd, 0x5e, 0x76, 0xd2, 0xe6, 0xa2, 0xed, 0xd1, 0x96, 0x16, 0x10, 0xda, 0xd3,
	0x9d, 0x2a, 0x21, 0xb5, 0x77, 0xe9, 0x49, 0x08, 0x84, 0x50, 0x7b, 0x0d, 0x94, 0x40, 0x7b, 0xa0,
	0x8d, 0x2a, 0x9e, 0x60, 0xe5, 0x7a, 0x9d, 0xc4, 0xb0, 0x6b, 0xb7, 0x6b, 0xb7, 0x55, 0xe1, 0x09,
	0x1e, 0xf8, 0x1b, 0xfc, 0x55, 0x34, 0xb6, 0x93, 0xec, 0xb6, 0x81, 0x5a, 0x3a, 0x1e, 0x56, 0xb2,
	0xc7, 0x33, 0xf3, 0x7d, 0xdf, 0x78, 0xd6, 0x36, 0xac, 0xd0, 0x9c, 0x33, 0xa1, 0x77, 0x2f, 0x4a,
	0xa9, 0x65, 0xd4, 0x1e, 0xbf, 0xb2, 0x23, 0x2a, 0xf3, 0xad, 0x15, 0x2a, 0x8b, 0x42, 0x0a, 0x6b,
	0xd8, 0x82, 0x52, 0xe6, 0xcc, 0x8d, 0x57, 0xb9, 0x18, 0x49, 0x75, 0x5d, 0x4e, 0xa7, 0x05, 0xe1,
	0x79, 0x65, 0x4a, 0x27, 0x44, 0xcf, 0xa7, 0x4f, 0x46, 0x25, 0x67, 0x22, 0x9b, 0x19, 0xe2, 0x03,
	0x08, 0x87, 0xf4, 0x3b, 0x4e, 0x7f, 0xfd, 0xfe, 0x4a, 0x47, 0xfb, 0xb0, 0x5c, 0x32, 0xa2, 0xa4,
	0xd8, 0x6c, 0x7c, 0xdc, 0xd8, 0xe9, 0xf4, 0xb6, 0x77, 0x2b, 0x14, 0x76, 0xbf, 0x72, 0x6e, 0x89,
	0x71, 0x49, 0x9c, 0x6b, 0xdc, 0x87, 0xce, 0x90, 0x0e, 0x6f, 0x05, 0x3d, 0x53, 0xac, 0xec, 0x13,
	0x4d, 0xa2, 0x1e, 0x84, 0xc8, 0x2f, 0x45, 0x62, 0x26, 0x53, 0xbb, 0xf7, 0x5e, 0x2d, 0x53, 0x22,
	0x73, 0x36, 0x10, 0x23, 0x99, 0xb4, 0x4a, 0x37, 0x8a, 0x7b, 0xb0, 0x3c, 0xa4, 0x47, 0x13, 0xa2,
	0xa3, 0x1d, 0x08, 0x0a, 0x35, 0x76, 0x71, 0xeb, 0xb5, 0xb8, 0x1f, 0xce, 0xd1, 0xe3, 0x54, 0x8d,
	0x13, 0x74, 0x89, 0x5f, 0x40, 0x34, 0xa4, 0x88, 0x78, 0x34, 0x21, 0x62, 0xcc, 0xde, 0x4a, 0xcd,
	0x47, 0xb7, 0x51, 0x17, 0x02, 0x5a, 0x64, 0x26, 0xfe, 0x51, 0x82, 0xc3, 0xf8, 0x27, 0x68, 0x9d,
	0xc8, 0x31, 0x17, 0x09, 0xbb, 0x8c, 0x36, 0xe1, 0x31, 0xa1, 0x54, 0x5e, 0x09, 0x6d, 0x3c, 0xc2,
	0x64, 0x3a, 0x8d, 0xb6, 0xa0, 0x75, 0x41, 0x94, 0xba, 0x91, 0x65, 0xb6, 0xd9, 0x34, 0x4b, 0xb3,
	0x79, 0xb4, 0x0d, 0xa1, 0x62, 0xe5, 0x35, 0x2b, 0x53, 0x9e, 0x6d, 0x06, 0x76, 0xd1, 0x1a, 0x06,
	0x59, 0xfc, 0x67, 0x63, 0x9a, 0x5f, 0x5d, 0x44, 0x31, 0x04, 0x25, 0xd3, 0x8e, 0x7d, 0xb7, 0xae,
	0x9a, 0xe9, 0x04, 0x17, 0xa3, 0x8f, 0xa0, 0xad, 0x79, 0xc1, 0x52, 0x21, 0x6f, 0xd2, 0x42, 0x19,
	0xb0, 0x20, 0x09, 0xd1, 0xf4, 0x56, 0xde, 0x9c, 0xaa, 0x7a, 0xfd, 0x02, 0xbf, 0xfa, 0x1d, 0x40,
	0x78, 0x22, 0xc7, 0x12, 0x77, 0xe7, 0x12, 0xe9, 0x9e, 0xdf, 0xa6, 0x96, 0xa0, 0xa1, 0xd2, 0x4a,
	0x5a, 0xe7, 0xb7, 0x43, 0x33, 0x8f, 0xd6, 0x67, 0x9b, 0x6c, 0x55, 0x4e, 0xf7, 0x71, 0x6f, 0x96,
	0xc1, 0x4f, 0x46, 0xdc, 0x83, 0x95, 0x6f, 0x18, 0x29, 0xf5, 0x1b, 0x46, 0x0c, 0x6a, 0x0c, 0xab,
	0xb6, 0x7f, 0xeb, 0xc2, 0xda, 0xd6, 0x68, 0xa4, 0xc5, 0x7f, 0x35, 0xaa, 0x41, 0x9e, 0xf5, 0xda,
	0x85, 0xa7, 0xb5, 0xc4, 0x29, 0x17, 0x69, 0xc9, 0x2e, 0x5d, 0xfe, 0x6e, 0x25, 0xff, 0x40, 0x38,
	0x22, 0x6e, 0xb7, 0x1c, 0x91, 0xc0, 0x12, 0xb1, 0x46, 0x4b, 0xe4, 0x4b, 0x80, 0x81, 0x66, 0xc5,
	0x99, 0x62, 0x18, 0xf1, 0x12, 0x42, 0xae, 0x59, 0x91, 0xe6, 0x5c, 0x21, 0x97, 0x60, 0xa7, 0xdd,
	0x5b, 0xbb, 0xd3, 0x79, 0xe8, 0x9d, 0xb4, 0xd0, 0xeb, 0x84, 0x2b, 0x1d, 0x97, 0xf3, 0x78, 0x4f,
	0x15, 0x07, 0x10, 0x95, 0x8c, 0xe4, 0x29, 0xc9, 0xb2, 0x74, 0x0e, 0xd6, 0xfc, 0x77, 0xb0, 0x27,
	0xe8, 0x7e, 0x98, 0x65, 0x83, 0x29, 0xe6, 0x33, 0x58, 0x75, 0x9d, 0x4e, 0x0a, 0x43, 0x3b, 0x82,
	0x25, 0x41, 0x0a, 0xe6, 0x3a, 0xd9, 0x8c, 0xe3, 0xfd, 0x9a, 0x93, 0xe7, 0x56, 0xbe, 0x84, 0x35,
	0xec, 0xa2, 0x63, 0xa6, 0xdf, 0x94, 0x9c, 0x8d, 0x4c, 0x6f, 0xb1, 0xcb, 0xe8, 0x7d, 0x68, 0x5d,
	0xf1, 0x6c, 0x5e, 0x95, 0xa5, 0xe4, 0xf1, 0x15, 0xcf, 0x0c, 0x17, 0xbd, 0x20, 0xc2, 0xb3, 0x10,
	0x9f, 0x41, 0x88, 0x9d, 0x5d, 0xd5, 0xff, 0xc1, 0x1d, 0xfd, 0xd8, 0xe0, 0xf3, 0xbc, 0x2d, 0x74,
	0x37, 0xa8, 0x7b, 0x10, 0x39, 0xd4, 0x01, 0x95, 0xa2, 0xcf, 0x14, 0x7d, 0x80, 0xa6, 0xb8, 0x1f,
	0xe0, 0xc9, 0xf2, 0x35, 0x84, 0x9c, 0x4a, 0x51, 0x65, 0xb9, 0x71, 0x77, 0x97, 0xa6, 0x29, 0x5b,
	0xe8, 0x69, 0xf0, 0xba, 0xd0, 0x39, 0x66, 0xfa, 0x94, 0xf0, 0x1c, 0xa7, 0x09, 0xbb, 0x8c, 0x27,
	0x75, 0x8b, 0x27, 0x7a, 0x0f, 0x42, 0x3c, 0xc7, 0xed, 0x11, 0xd0, 0x5c, 0x70, 0x04, 0x60, 0x42,
	0x5b, 0x9c, 0xc2, 0x8d, 0xe2, 0x17, 0xd0, 0x4e, 0x18, 0xc9, 0x70, 0x05, 0xab, 0xb2, 0x01, 0x8f,
	0xab, 0x45, 0x79, 0x94, 0x2c, 0xbb, 0x9a, 0x7c, 0x5b, 0xf1, 0xf3, 0xa4, 0x53, 0xc9, 0xd5, 0xac,
	0xe5, 0x7a, 0x0e, 0xd0, 0x67, 0xf9, 0x83, 0x90, 0x83, 0xb9, 0xdb, 0xbb, 0x22, 0x7e, 0x02, 0x5d,
	0x57, 0xcf, 0x43, 0xad, 0x09, 0x9d, 0xfc, 0x27, 0xee, 0x1f, 0x8d, 0xbb, 0xde, 0xef, 0x08, 0x5f,
	0x3f, 0x29, 0x02, 0x9f, 0x93, 0xe2, 0x53, 0x68, 0xe3, 0xad, 0x85, 0x1f, 0x72, 0xf5, 0xbf, 0xde,
	0x5e, 0x55, 0x02, 0x3d, 0xff, 0xe3, 0xa7, 0x10, 0xa1, 0xfb, 0x31, 0x33, 0x51, 0xee, 0x37, 0xc6,
	0x9f, 0xe0, 0xae, 0xd5, 0xff, 0x27, 0xc0, 0xf7, 0x43, 0xb5, 0x0d, 0x37, 0x16, 0x50, 0xb6, 0x8d,
	0x48, 0xdd, 0x28, 0xde, 0x83, 0x0e, 0x5a, 0xfb, 0x2c, 0x9f, 0x8a, 0xfe, 0x10, 0xc0, 0x3e, 0x3c,
	0xd2, 0x2b, 0x6e, 0xaf, 0xe6, 0xa5, 0x24, 0xb4, 0x96, 0x33, 0x9e, 0xc5, 0xaf, 0xeb, 0x01, 0x9e,
	0x62, 0x37, 0x61, 0xfd, 0x6b, 0x93, 0xe2, 0x98, 0x69, 0x3b, 0x98, 0x0a, 0xfe, 0x6d, 0xf1, 0x8a,
	0xa7, 0xe8, 0x2f, 0xa0, 0xed, 0xc8, 0x56, 0x64, 0x6f, 0xdf, 0xbb, 0x80, 0x2b, 0x89, 0x9d, 0x38,
	0x23, 0xfe, 0x47, 0x88, 0xec, 0xca, 0x61, 0x96, 0xd9, 0xc1, 0xc3, 0x05, 0xc0, 0x1b, 0x8b, 0xab,
	0x34, 0x63, 0x79, 0x6a, 0x6d, 0x06, 0xb4, 0x95, 0xb4, 0xb9, 0xea, 0xb3, 0xdc, 0x66, 0x89, 0x7f,
	0xbf, 0x9f, 0xd8, 0x53, 0x50, 0x1d, 0xbc, 0xf9, 0x20, 0x78, 0xb0, 0x08, 0xdc, 0x55, 0xf4, 0x48,
	0x8a, 0x11, 0x2f, 0x0b, 0x6f, 0x65, 0xdb, 0x10, 0x72, 0x95, 0x96, 0xec, 0x17, 0x46, 0xb5, 0x53,
	0xd5, 0xe2, 0x2a, 0x31, 0xf3, 0xe8, 0x39, 0x74, 0x48, 0x8e, 0x87, 0xdc, 0x35, 0xd7, 0x44, 0x73,
	0x29, 0x1c, 0xf4, 0x2a, 0xc9, 0xf3, 0xc1, 0xcc, 0x18, 0xff, 0xdd, 0x58, 0x8c, 0xfe, 0xff, 0xc8,
	0xaf, 0x31, 0x0c, 0x1e, 0x64, 0xb8, 0xb4, 0x88, 0xe1, 0xcf, 0xb0, 0x66, 0x39, 0x0d, 0x27, 0x9c,
	0xe5, 0x19, 0xbe, 0x84, 0x5d, 0x6d, 0x94, 0x31, 0x54, 0x6b, 0x63, 0x2d, 0x88, 0xbc, 0x03, 0x5d,
	0xae, 0x52, 0x4a, 0x04, 0x65, 0x79, 0x6a, 0xcd, 0xae, 0x44, 0x1d, 0xae, 0x8e, 0x8c, 0xd9, 0xe6,
	0xc3, 0x27, 0xe6, 0x7d, 0x00, 0x7f, 0xf9, 0x15, 0x12, 0x4d, 0x1f, 0x12, 0xc1, 0x42, 0x12, 0x9f,
	0xcf, 0x38, 0x30, 0x52, 0xd2, 0x09, 0xfe, 0x03, 0x28, 0xf2, 0x19, 0xbe, 0xb6, 0xd0, 0x90, 0x2a,
	0x5d, 0x72, 0x31, 0x76, 0xaf, 0x91, 0x15, 0x6b, 0x1c, 0x1a, 0x5b, 0x2c, 0x17, 0xc4, 0xfa, 0x9f,
	0x41, 0xe6, 0x35, 0xec, 0x75, 0x11, 0xa3, 0x27, 0x9e, 0xba, 0xe7, 0xcb, 0x66, 0x79, 0xff, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x95, 0x4d, 0x1e, 0x53, 0x0d, 0x00, 0x00,
}
