// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMD int32

const (
	CMD__CMD_ZERO CMD = 0
	// 强制下线
	CMD_SC_KICK_OUT CMD = 12289
	// 同步玩家数据
	CMD_SC_SYNC_USER_DATA CMD = 12290
	// 聊天信息推送
	CMD_SC_CHAT CMD = 12291
	// 通知客户端数据有变动
	CMD_SC_DATA_CHANGE_NOTIFY CMD = 12292
	CMD_CONN_KICK_OUT_REQ     CMD = 69632
	CMD_CONN_KICK_OUT_RSP     CMD = 65537
	CMD_CONN_BROADCAST_REQ    CMD = 69634
	CMD_CONN_BROADCAST_RSP    CMD = 69635
	// 登陆
	CMD_MAIN_LOGIN_REQ CMD = 131072
	CMD_MAIN_LOGIN_RSP CMD = 131073
	// 登出
	CMD_MAIN_LOGOUT_REQ    CMD = 131074
	CMD_MAIN_LOGOUT_RSP    CMD = 131075
	CMD_MAIN_HEARTBEAT_REQ CMD = 131076
	CMD_MAIN_HEARTBEAT_RSP CMD = 131077
	// 道具使用
	CMD_MAIN_ITEM_USE_REQ CMD = 131078
	CMD_MAIN_ITEM_USE_RSP CMD = 131079
	// 改名
	CMD_MAIN_CHANGE_NAME_REQ CMD = 131080
	CMD_MAIN_CHANGE_NAME_RSP CMD = 131081
	// 改头像
	CMD_MAIN_CHANGE_ICON_REQ CMD = 131082
	CMD_MAIN_CHANGE_ICON_RSP CMD = 131083
	// 消红点
	CMD_MAIN_TOUCH_RED_POINT_REQ CMD = 131084
	CMD_MAIN_TOUCH_RED_POINT_RSP CMD = 131085
	// 英雄道具使用
	CMD_MAIN_HERO_ITEM_USE_REQ CMD = 131086
	CMD_MAIN_HERO_ITEM_USE_RSP CMD = 131087
	// 英雄招募
	CMD_MAIN_HERO_RECRUIT_REQ CMD = 131088
	CMD_MAIN_HERO_RECRUIT_RSP CMD = 131089
	// 买招募券
	CMD_MAIN_BUY_HERO_RECRUIT_TICKET_REQ CMD = 131090
	CMD_MAIN_BUY_HERO_RECRUIT_TICKET_RSP CMD = 131091
	// 物品合成
	CMD_MAIN_ITEM_COMPOSE_REQ CMD = 131092
	CMD_MAIN_ITEM_COMPOSE_RSP CMD = 131093
	// 羁绊升级
	CMD_MAIN_CARD_COMBINE_LEVEL_UP_REQ CMD = 131094
	CMD_MAIN_CARD_COMBINE_LEVEL_UP_RSP CMD = 131095
	// 购买礼包
	CMD_MAIN_MALL_BUY_PACKAGE_REQ CMD = 131504
	CMD_MAIN_MALL_BUY_PACKAGE_RSP CMD = 131505
	// 充值
	CMD_MAIN_MALL_RECHARGE_REQ CMD = 131506
	CMD_MAIN_MALL_RECHARGE_RSP CMD = 131507
	// 完成主线任务
	CMD_MAIN_MAIN_TASK_FINISH_REQ CMD = 131536
	CMD_MAIN_MAIN_TASK_FINISH_RSP CMD = 131537
	// ~~~~~~~~~~~~引导功能~~~~~~~~~~~~~~~~~~
	// 发送已经完成的ID
	CMD_GUIDE_COMPLETED_REQ CMD = 131616
	CMD_GUIDE_COMPLETED_RSP CMD = 131617
	// 发送正在进行的ID
	CMD_GUIDE_IN_PROGRESS_REQ CMD = 131618
	CMD_GUIDE_IN_PROGRESS_RSP CMD = 131619
	//单个任务更新通知
	CMD_MAIN_ACTIVITY_TASK_SINGLE_UPDATE_NOTIFY CMD = 131657
	// 设置角色信息
	CMD_MAIN_GM_GET_ROLE_REQ             CMD = 172032
	CMD_MAIN_GM_GET_ROLE_RSP             CMD = 172033
	CMD_MAIN_GM_SET_ROLE_REQ             CMD = 172034
	CMD_MAIN_GM_SET_ROLE_RSP             CMD = 172035
	CMD_MAIN_GM_ADD_ITEM_REQ             CMD = 172036
	CMD_MAIN_GM_ADD_ITEM_RSP             CMD = 172037
	CMD_DB_INNER_UID_GET_REQ             CMD = 200704
	CMD_DB_INNER_UID_GET_RSP             CMD = 200705
	CMD_DB_INNER_UID_SET_REQ             CMD = 200706
	CMD_DB_INNER_UID_SET_RSP             CMD = 200707
	CMD_DB_INNER_UID_MGET_REQ            CMD = 200708
	CMD_DB_INNER_UID_MGET_RSP            CMD = 200709
	CMD_DB_INNER_COMM_GET_REQ            CMD = 200710
	CMD_DB_INNER_COMM_GET_RSP            CMD = 200711
	CMD_DB_INNER_COMM_SET_REQ            CMD = 200712
	CMD_DB_INNER_COMM_SET_RSP            CMD = 200713
	CMD_DB_INNER_COMM_MGET_REQ           CMD = 200714
	CMD_DB_INNER_COMM_MGET_RSP           CMD = 200715
	CMD_DB_INNER_COMM_DEL_REQ            CMD = 200716
	CMD_DB_INNER_COMM_DEL_RSP            CMD = 200717
	CMD_DB_INNER_COMM_INCR_REQ           CMD = 200718
	CMD_DB_INNER_COMM_INCR_RSP           CMD = 200719
	CMD_DB_INNER_COMM_ZSET_SET_REQ       CMD = 200736
	CMD_DB_INNER_COMM_ZSET_SET_RSP       CMD = 200737
	CMD_DB_INNER_COMM_ZSET_GET_REQ       CMD = 200738
	CMD_DB_INNER_COMM_ZSET_GET_RSP       CMD = 200739
	CMD_MYSQL_INNER_UPDATE_ROLE_INFO_REQ CMD = 266240
	CMD_MYSQL_INNER_UPDATE_ROLE_INFO_RSP CMD = 266241
	CMD_MYSQL_INNER_SEARCH_ROLE_REQ      CMD = 266242
	CMD_MYSQL_INNER_SEARCH_ROLE_RSP      CMD = 266243
	// 向数据库查询礼包码
	CMD_MYSQL_INNER_SEARCH_GIFT_CODE_REQ CMD = 266244
	CMD_MYSQL_INNER_SEARCH_GIFT_CODE_RSP CMD = 266245
	// 获取邮件
	CMD_MAIL_GET_MAIL_LIST_REQ CMD = 655360
	CMD_MAIL_GET_MAIL_LIST_RSP CMD = 655361
	// 阅读邮件
	CMD_MAIL_READ_MAIL_REQ CMD = 655362
	CMD_MAIL_READ_MAIL_RSP CMD = 655363
	// 删除邮件
	CMD_MAIL_DEL_MAIL_REQ CMD = 655364
	CMD_MAIL_DEL_MAIL_RSP CMD = 655365
	// 领取附件
	CMD_MAIL_GET_MAIL_ATTACH_REQ CMD = 655366
	CMD_MAIL_GET_MAIL_ATTACH_RSP CMD = 655367
	// 添加邮件
	CMD_MAIL_INNER_ADD_MAIL_REQ       CMD = 659456
	CMD_MAIL_INNER_ADD_MAIL_RSP       CMD = 659457
	CMD_INFO_GET_BRIEF_INFO_REQ       CMD = 458752
	CMD_INFO_GET_BRIEF_INFO_RSP       CMD = 458753
	CMD_INFO_GET_ICON_DESC_REQ        CMD = 458754
	CMD_INFO_GET_ICON_DESC_RSP        CMD = 458755
	CMD_INFO_INNER_SET_BRIEF_INFO_REQ CMD = 462848
	CMD_INFO_INNER_SET_BRIEF_INFO_RSP CMD = 462849
	// 发送聊天
	CMD_CHAT_CHAT_REQ CMD = 720896
	CMD_CHAT_CHAT_RSP CMD = 720897
	// 获取聊天信息
	CMD_CHAT_GET_CHAT_INFO_REQ CMD = 720898
	CMD_CHAT_GET_CHAT_INFO_RSP CMD = 720899
	// 删除好友聊天数据
	CMD_CHAT_DEL_CHAT_REQ CMD = 720900
	CMD_CHAT_DEL_CHAT_RSP CMD = 720901
	// 获取社交信息
	CMD_FRIEND_GET_FRIEND_INFO_REQ CMD = 786432
	CMD_FRIEND_GET_FRIEND_INFO_RSP CMD = 786433
	// 添加好友
	CMD_FRIEND_ADD_FRIEND_REQ CMD = 786434
	CMD_FRIEND_ADD_FRIEND_RSP CMD = 786435
	// 确认添加好友
	CMD_FRIEND_CONFIRM_FRIEND_REQ CMD = 786436
	CMD_FRIEND_CONFIRM_FRIEND_RSP CMD = 786437
	// 屏蔽玩家
	CMD_FRIEND_SHIELD_USER_REQ CMD = 786438
	CMD_FRIEND_SHIELD_USER_RSP CMD = 786439
	// 搜索玩家
	CMD_FRIEND_SEARCH_ROLE_REQ          CMD = 786440
	CMD_FRIEND_SEARCH_ROLE_RSP          CMD = 786441
	CMD_FRIEND_INNER_ADD_FRIEND_REQ     CMD = 790528
	CMD_FRIEND_INNER_ADD_FRIEND_RSP     CMD = 790529
	CMD_FRIEND_INNER_CONFIRM_FRIEND_REQ CMD = 790530
	CMD_FRIEND_INNER_CONFIRM_FRIEND_RSP CMD = 790531
)

var CMD_name = map[int32]string{
	0:      "_CMD_ZERO",
	12289:  "SC_KICK_OUT",
	12290:  "SC_SYNC_USER_DATA",
	12291:  "SC_CHAT",
	12292:  "SC_DATA_CHANGE_NOTIFY",
	69632:  "CONN_KICK_OUT_REQ",
	65537:  "CONN_KICK_OUT_RSP",
	69634:  "CONN_BROADCAST_REQ",
	69635:  "CONN_BROADCAST_RSP",
	131072: "MAIN_LOGIN_REQ",
	131073: "MAIN_LOGIN_RSP",
	131074: "MAIN_LOGOUT_REQ",
	131075: "MAIN_LOGOUT_RSP",
	131076: "MAIN_HEARTBEAT_REQ",
	131077: "MAIN_HEARTBEAT_RSP",
	131078: "MAIN_ITEM_USE_REQ",
	131079: "MAIN_ITEM_USE_RSP",
	131080: "MAIN_CHANGE_NAME_REQ",
	131081: "MAIN_CHANGE_NAME_RSP",
	131082: "MAIN_CHANGE_ICON_REQ",
	131083: "MAIN_CHANGE_ICON_RSP",
	131084: "MAIN_TOUCH_RED_POINT_REQ",
	131085: "MAIN_TOUCH_RED_POINT_RSP",
	131086: "MAIN_HERO_ITEM_USE_REQ",
	131087: "MAIN_HERO_ITEM_USE_RSP",
	131088: "MAIN_HERO_RECRUIT_REQ",
	131089: "MAIN_HERO_RECRUIT_RSP",
	131090: "MAIN_BUY_HERO_RECRUIT_TICKET_REQ",
	131091: "MAIN_BUY_HERO_RECRUIT_TICKET_RSP",
	131092: "MAIN_ITEM_COMPOSE_REQ",
	131093: "MAIN_ITEM_COMPOSE_RSP",
	131094: "MAIN_CARD_COMBINE_LEVEL_UP_REQ",
	131095: "MAIN_CARD_COMBINE_LEVEL_UP_RSP",
	131504: "MAIN_MALL_BUY_PACKAGE_REQ",
	131505: "MAIN_MALL_BUY_PACKAGE_RSP",
	131506: "MAIN_MALL_RECHARGE_REQ",
	131507: "MAIN_MALL_RECHARGE_RSP",
	131536: "MAIN_MAIN_TASK_FINISH_REQ",
	131537: "MAIN_MAIN_TASK_FINISH_RSP",
	131616: "GUIDE_COMPLETED_REQ",
	131617: "GUIDE_COMPLETED_RSP",
	131618: "GUIDE_IN_PROGRESS_REQ",
	131619: "GUIDE_IN_PROGRESS_RSP",
	131657: "MAIN_ACTIVITY_TASK_SINGLE_UPDATE_NOTIFY",
	172032: "MAIN_GM_GET_ROLE_REQ",
	172033: "MAIN_GM_GET_ROLE_RSP",
	172034: "MAIN_GM_SET_ROLE_REQ",
	172035: "MAIN_GM_SET_ROLE_RSP",
	172036: "MAIN_GM_ADD_ITEM_REQ",
	172037: "MAIN_GM_ADD_ITEM_RSP",
	200704: "DB_INNER_UID_GET_REQ",
	200705: "DB_INNER_UID_GET_RSP",
	200706: "DB_INNER_UID_SET_REQ",
	200707: "DB_INNER_UID_SET_RSP",
	200708: "DB_INNER_UID_MGET_REQ",
	200709: "DB_INNER_UID_MGET_RSP",
	200710: "DB_INNER_COMM_GET_REQ",
	200711: "DB_INNER_COMM_GET_RSP",
	200712: "DB_INNER_COMM_SET_REQ",
	200713: "DB_INNER_COMM_SET_RSP",
	200714: "DB_INNER_COMM_MGET_REQ",
	200715: "DB_INNER_COMM_MGET_RSP",
	200716: "DB_INNER_COMM_DEL_REQ",
	200717: "DB_INNER_COMM_DEL_RSP",
	200718: "DB_INNER_COMM_INCR_REQ",
	200719: "DB_INNER_COMM_INCR_RSP",
	200736: "DB_INNER_COMM_ZSET_SET_REQ",
	200737: "DB_INNER_COMM_ZSET_SET_RSP",
	200738: "DB_INNER_COMM_ZSET_GET_REQ",
	200739: "DB_INNER_COMM_ZSET_GET_RSP",
	266240: "MYSQL_INNER_UPDATE_ROLE_INFO_REQ",
	266241: "MYSQL_INNER_UPDATE_ROLE_INFO_RSP",
	266242: "MYSQL_INNER_SEARCH_ROLE_REQ",
	266243: "MYSQL_INNER_SEARCH_ROLE_RSP",
	266244: "MYSQL_INNER_SEARCH_GIFT_CODE_REQ",
	266245: "MYSQL_INNER_SEARCH_GIFT_CODE_RSP",
	655360: "MAIL_GET_MAIL_LIST_REQ",
	655361: "MAIL_GET_MAIL_LIST_RSP",
	655362: "MAIL_READ_MAIL_REQ",
	655363: "MAIL_READ_MAIL_RSP",
	655364: "MAIL_DEL_MAIL_REQ",
	655365: "MAIL_DEL_MAIL_RSP",
	655366: "MAIL_GET_MAIL_ATTACH_REQ",
	655367: "MAIL_GET_MAIL_ATTACH_RSP",
	659456: "MAIL_INNER_ADD_MAIL_REQ",
	659457: "MAIL_INNER_ADD_MAIL_RSP",
	458752: "INFO_GET_BRIEF_INFO_REQ",
	458753: "INFO_GET_BRIEF_INFO_RSP",
	458754: "INFO_GET_ICON_DESC_REQ",
	458755: "INFO_GET_ICON_DESC_RSP",
	462848: "INFO_INNER_SET_BRIEF_INFO_REQ",
	462849: "INFO_INNER_SET_BRIEF_INFO_RSP",
	720896: "CHAT_CHAT_REQ",
	720897: "CHAT_CHAT_RSP",
	720898: "CHAT_GET_CHAT_INFO_REQ",
	720899: "CHAT_GET_CHAT_INFO_RSP",
	720900: "CHAT_DEL_CHAT_REQ",
	720901: "CHAT_DEL_CHAT_RSP",
	786432: "FRIEND_GET_FRIEND_INFO_REQ",
	786433: "FRIEND_GET_FRIEND_INFO_RSP",
	786434: "FRIEND_ADD_FRIEND_REQ",
	786435: "FRIEND_ADD_FRIEND_RSP",
	786436: "FRIEND_CONFIRM_FRIEND_REQ",
	786437: "FRIEND_CONFIRM_FRIEND_RSP",
	786438: "FRIEND_SHIELD_USER_REQ",
	786439: "FRIEND_SHIELD_USER_RSP",
	786440: "FRIEND_SEARCH_ROLE_REQ",
	786441: "FRIEND_SEARCH_ROLE_RSP",
	790528: "FRIEND_INNER_ADD_FRIEND_REQ",
	790529: "FRIEND_INNER_ADD_FRIEND_RSP",
	790530: "FRIEND_INNER_CONFIRM_FRIEND_REQ",
	790531: "FRIEND_INNER_CONFIRM_FRIEND_RSP",
}

var CMD_value = map[string]int32{
	"_CMD_ZERO":                               0,
	"SC_KICK_OUT":                             12289,
	"SC_SYNC_USER_DATA":                       12290,
	"SC_CHAT":                                 12291,
	"SC_DATA_CHANGE_NOTIFY":                   12292,
	"CONN_KICK_OUT_REQ":                       69632,
	"CONN_KICK_OUT_RSP":                       65537,
	"CONN_BROADCAST_REQ":                      69634,
	"CONN_BROADCAST_RSP":                      69635,
	"MAIN_LOGIN_REQ":                          131072,
	"MAIN_LOGIN_RSP":                          131073,
	"MAIN_LOGOUT_REQ":                         131074,
	"MAIN_LOGOUT_RSP":                         131075,
	"MAIN_HEARTBEAT_REQ":                      131076,
	"MAIN_HEARTBEAT_RSP":                      131077,
	"MAIN_ITEM_USE_REQ":                       131078,
	"MAIN_ITEM_USE_RSP":                       131079,
	"MAIN_CHANGE_NAME_REQ":                    131080,
	"MAIN_CHANGE_NAME_RSP":                    131081,
	"MAIN_CHANGE_ICON_REQ":                    131082,
	"MAIN_CHANGE_ICON_RSP":                    131083,
	"MAIN_TOUCH_RED_POINT_REQ":                131084,
	"MAIN_TOUCH_RED_POINT_RSP":                131085,
	"MAIN_HERO_ITEM_USE_REQ":                  131086,
	"MAIN_HERO_ITEM_USE_RSP":                  131087,
	"MAIN_HERO_RECRUIT_REQ":                   131088,
	"MAIN_HERO_RECRUIT_RSP":                   131089,
	"MAIN_BUY_HERO_RECRUIT_TICKET_REQ":        131090,
	"MAIN_BUY_HERO_RECRUIT_TICKET_RSP":        131091,
	"MAIN_ITEM_COMPOSE_REQ":                   131092,
	"MAIN_ITEM_COMPOSE_RSP":                   131093,
	"MAIN_CARD_COMBINE_LEVEL_UP_REQ":          131094,
	"MAIN_CARD_COMBINE_LEVEL_UP_RSP":          131095,
	"MAIN_MALL_BUY_PACKAGE_REQ":               131504,
	"MAIN_MALL_BUY_PACKAGE_RSP":               131505,
	"MAIN_MALL_RECHARGE_REQ":                  131506,
	"MAIN_MALL_RECHARGE_RSP":                  131507,
	"MAIN_MAIN_TASK_FINISH_REQ":               131536,
	"MAIN_MAIN_TASK_FINISH_RSP":               131537,
	"GUIDE_COMPLETED_REQ":                     131616,
	"GUIDE_COMPLETED_RSP":                     131617,
	"GUIDE_IN_PROGRESS_REQ":                   131618,
	"GUIDE_IN_PROGRESS_RSP":                   131619,
	"MAIN_ACTIVITY_TASK_SINGLE_UPDATE_NOTIFY": 131657,
	"MAIN_GM_GET_ROLE_REQ":                    172032,
	"MAIN_GM_GET_ROLE_RSP":                    172033,
	"MAIN_GM_SET_ROLE_REQ":                    172034,
	"MAIN_GM_SET_ROLE_RSP":                    172035,
	"MAIN_GM_ADD_ITEM_REQ":                    172036,
	"MAIN_GM_ADD_ITEM_RSP":                    172037,
	"DB_INNER_UID_GET_REQ":                    200704,
	"DB_INNER_UID_GET_RSP":                    200705,
	"DB_INNER_UID_SET_REQ":                    200706,
	"DB_INNER_UID_SET_RSP":                    200707,
	"DB_INNER_UID_MGET_REQ":                   200708,
	"DB_INNER_UID_MGET_RSP":                   200709,
	"DB_INNER_COMM_GET_REQ":                   200710,
	"DB_INNER_COMM_GET_RSP":                   200711,
	"DB_INNER_COMM_SET_REQ":                   200712,
	"DB_INNER_COMM_SET_RSP":                   200713,
	"DB_INNER_COMM_MGET_REQ":                  200714,
	"DB_INNER_COMM_MGET_RSP":                  200715,
	"DB_INNER_COMM_DEL_REQ":                   200716,
	"DB_INNER_COMM_DEL_RSP":                   200717,
	"DB_INNER_COMM_INCR_REQ":                  200718,
	"DB_INNER_COMM_INCR_RSP":                  200719,
	"DB_INNER_COMM_ZSET_SET_REQ":              200736,
	"DB_INNER_COMM_ZSET_SET_RSP":              200737,
	"DB_INNER_COMM_ZSET_GET_REQ":              200738,
	"DB_INNER_COMM_ZSET_GET_RSP":              200739,
	"MYSQL_INNER_UPDATE_ROLE_INFO_REQ":        266240,
	"MYSQL_INNER_UPDATE_ROLE_INFO_RSP":        266241,
	"MYSQL_INNER_SEARCH_ROLE_REQ":             266242,
	"MYSQL_INNER_SEARCH_ROLE_RSP":             266243,
	"MYSQL_INNER_SEARCH_GIFT_CODE_REQ":        266244,
	"MYSQL_INNER_SEARCH_GIFT_CODE_RSP":        266245,
	"MAIL_GET_MAIL_LIST_REQ":                  655360,
	"MAIL_GET_MAIL_LIST_RSP":                  655361,
	"MAIL_READ_MAIL_REQ":                      655362,
	"MAIL_READ_MAIL_RSP":                      655363,
	"MAIL_DEL_MAIL_REQ":                       655364,
	"MAIL_DEL_MAIL_RSP":                       655365,
	"MAIL_GET_MAIL_ATTACH_REQ":                655366,
	"MAIL_GET_MAIL_ATTACH_RSP":                655367,
	"MAIL_INNER_ADD_MAIL_REQ":                 659456,
	"MAIL_INNER_ADD_MAIL_RSP":                 659457,
	"INFO_GET_BRIEF_INFO_REQ":                 458752,
	"INFO_GET_BRIEF_INFO_RSP":                 458753,
	"INFO_GET_ICON_DESC_REQ":                  458754,
	"INFO_GET_ICON_DESC_RSP":                  458755,
	"INFO_INNER_SET_BRIEF_INFO_REQ":           462848,
	"INFO_INNER_SET_BRIEF_INFO_RSP":           462849,
	"CHAT_CHAT_REQ":                           720896,
	"CHAT_CHAT_RSP":                           720897,
	"CHAT_GET_CHAT_INFO_REQ":                  720898,
	"CHAT_GET_CHAT_INFO_RSP":                  720899,
	"CHAT_DEL_CHAT_REQ":                       720900,
	"CHAT_DEL_CHAT_RSP":                       720901,
	"FRIEND_GET_FRIEND_INFO_REQ":              786432,
	"FRIEND_GET_FRIEND_INFO_RSP":              786433,
	"FRIEND_ADD_FRIEND_REQ":                   786434,
	"FRIEND_ADD_FRIEND_RSP":                   786435,
	"FRIEND_CONFIRM_FRIEND_REQ":               786436,
	"FRIEND_CONFIRM_FRIEND_RSP":               786437,
	"FRIEND_SHIELD_USER_REQ":                  786438,
	"FRIEND_SHIELD_USER_RSP":                  786439,
	"FRIEND_SEARCH_ROLE_REQ":                  786440,
	"FRIEND_SEARCH_ROLE_RSP":                  786441,
	"FRIEND_INNER_ADD_FRIEND_REQ":             790528,
	"FRIEND_INNER_ADD_FRIEND_RSP":             790529,
	"FRIEND_INNER_CONFIRM_FRIEND_REQ":         790530,
	"FRIEND_INNER_CONFIRM_FRIEND_RSP":         790531,
}

func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}

func (CMD) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{0}
}

func init() {
	proto.RegisterEnum("g1.protocol.CMD", CMD_name, CMD_value)
}

func init() {
	proto.RegisterFile("cmd.proto", fileDescriptor_7520252fb01eaf30)
}

var fileDescriptor_7520252fb01eaf30 = []byte{
	// 1084 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x97, 0x5b, 0x6f, 0x1c, 0x35,
	0x14, 0xc7, 0x91, 0x88, 0x60, 0xea, 0x6e, 0xc1, 0x75, 0x9b, 0x5e, 0xd2, 0xf4, 0x82, 0xb8, 0x45,
	0x28, 0xa0, 0x45, 0x7c, 0x02, 0xaf, 0xc7, 0xbb, 0x6b, 0x65, 0x2e, 0xee, 0x78, 0xb6, 0x52, 0xfa,
	0xe2, 0x88, 0x22, 0xf1, 0x02, 0x0a, 0x42, 0x7c, 0x80, 0xe9, 0x66, 0x29, 0xa1, 0xdc, 0xaf, 0x7d,
	0x1d, 0xca, 0x17, 0xe0, 0xf2, 0x05, 0x78, 0xe5, 0x0d, 0xbe, 0x51, 0x75, 0x8e, 0x3d, 0x93, 0x9d,
	0x64, 0xbc, 0xc9, 0xdb, 0xac, 0x7f, 0xc7, 0xf6, 0xdf, 0xc7, 0x67, 0xfe, 0x73, 0x96, 0x9c, 0x7b,
	0xf0, 0xf1, 0x07, 0xef, 0x7c, 0xf2, 0xe9, 0xfe, 0x67, 0xfb, 0xec, 0xfc, 0x87, 0xef, 0xba, 0xa7,
	0x07, 0xfb, 0x1f, 0xbd, 0xf5, 0x64, 0x83, 0x3c, 0x2f, 0xd2, 0x98, 0x5d, 0x20, 0xe7, 0xac, 0x48,
	0x63, 0x7b, 0x5f, 0x16, 0x39, 0x7d, 0x8e, 0x51, 0x72, 0xde, 0x08, 0xbb, 0xa3, 0xc4, 0x8e, 0xcd,
	0x67, 0x25, 0x7d, 0xb8, 0xc7, 0xae, 0x90, 0x8b, 0x46, 0x58, 0xb3, 0x9b, 0x09, 0x3b, 0x33, 0xb2,
	0xb0, 0x31, 0x2f, 0x39, 0x9d, 0xef, 0xb1, 0x01, 0x79, 0xd1, 0x08, 0x2b, 0xa6, 0xbc, 0xa4, 0x07,
	0x7b, 0x6c, 0x83, 0xac, 0x1b, 0x81, 0x0c, 0x86, 0xb2, 0x89, 0xb4, 0x59, 0x5e, 0xaa, 0xf1, 0x2e,
	0x5d, 0xec, 0xb1, 0xab, 0xe4, 0xa2, 0xc8, 0xb3, 0xac, 0x5d, 0xd5, 0x16, 0xf2, 0x2e, 0xad, 0xea,
	0xb5, 0x1e, 0x60, 0x34, 0x7d, 0x58, 0xad, 0xb1, 0x6b, 0x84, 0x21, 0x18, 0x15, 0x39, 0x8f, 0x05,
	0x37, 0x6e, 0xca, 0xbc, 0xee, 0x25, 0x46, 0xd3, 0x83, 0x7a, 0x8d, 0x5d, 0x26, 0x2f, 0xa5, 0x5c,
	0x65, 0x36, 0xc9, 0x27, 0x2a, 0x73, 0x5b, 0x54, 0xd1, 0xf1, 0x51, 0x5c, 0x3f, 0x62, 0xeb, 0xe4,
	0xe5, 0x66, 0xb4, 0xd1, 0x33, 0xef, 0x19, 0x86, 0x95, 0xab, 0x08, 0xf6, 0xc4, 0xe1, 0xa9, 0xe4,
	0x45, 0x39, 0x92, 0xdc, 0x4d, 0x58, 0xf4, 0x13, 0xa3, 0xe9, 0xe7, 0x55, 0x04, 0x47, 0x43, 0xa2,
	0x4a, 0x99, 0x42, 0xde, 0x70, 0xca, 0xa3, 0x5e, 0x60, 0x34, 0xfd, 0xa2, 0x8a, 0xd8, 0x06, 0xb9,
	0x8c, 0xa0, 0x49, 0x1f, 0x4f, 0xdd, 0xa4, 0xc3, 0x10, 0x33, 0x9a, 0x7e, 0x79, 0x92, 0x29, 0x91,
	0xbb, 0xd3, 0x3f, 0x0e, 0x31, 0xa3, 0xe9, 0x57, 0x55, 0xc4, 0x6e, 0x91, 0x6b, 0xc8, 0xca, 0x7c,
	0x26, 0xa6, 0xb6, 0x90, 0xb1, 0xd5, 0xb9, 0xca, 0xdc, 0xd9, 0xbe, 0x5e, 0xc5, 0x8d, 0xa6, 0xdf,
	0x54, 0x11, 0xdb, 0x24, 0x57, 0xfc, 0xd9, 0x8b, 0xbc, 0x7b, 0xcc, 0x6f, 0xc3, 0xd4, 0x68, 0xfa,
	0x5d, 0x15, 0xb1, 0x1b, 0x64, 0xfd, 0x88, 0x16, 0x52, 0x14, 0x33, 0xe5, 0x36, 0xfe, 0x3e, 0x08,
	0x8d, 0xa6, 0x3f, 0x54, 0x11, 0x7b, 0x83, 0xdc, 0x41, 0x38, 0x9a, 0xed, 0x76, 0x03, 0x4a, 0x25,
	0x76, 0xa4, 0x5b, 0xe4, 0xc7, 0xb3, 0xc4, 0x19, 0x4d, 0x7f, 0x5a, 0xda, 0x0c, 0x25, 0x8a, 0x3c,
	0xd5, 0xb9, 0x3f, 0xc4, 0xcf, 0x41, 0x68, 0x34, 0xfd, 0xa5, 0x8a, 0xd8, 0x6b, 0xe4, 0x96, 0xcb,
	0x2d, 0x2f, 0x62, 0x80, 0x23, 0x95, 0x49, 0x9b, 0xc8, 0x7b, 0x32, 0xb1, 0x33, 0x8d, 0x4b, 0xfc,
	0x7a, 0x7a, 0x94, 0xd1, 0xf4, 0x49, 0x15, 0xb1, 0xdb, 0xe4, 0x3a, 0x46, 0xa5, 0x3c, 0x49, 0x50,
	0xb2, 0xe6, 0x62, 0x87, 0x4f, 0x9c, 0x92, 0x3f, 0x0e, 0x56, 0x05, 0x18, 0x4d, 0xff, 0x3c, 0x38,
	0xca, 0x37, 0x06, 0x14, 0x52, 0x4c, 0x79, 0xe1, 0xa7, 0xff, 0x15, 0xa6, 0x46, 0xd3, 0xbf, 0x3b,
	0x8b, 0xc3, 0x75, 0x73, 0xb3, 0x63, 0xc7, 0x2a, 0x53, 0x66, 0x8a, 0xd3, 0xff, 0x5b, 0x19, 0x60,
	0x34, 0xfd, 0xff, 0x20, 0x62, 0xd7, 0xc9, 0xa5, 0xc9, 0x4c, 0xc5, 0x12, 0x93, 0x94, 0xc8, 0x52,
	0xc6, 0x38, 0xb7, 0x5e, 0xf4, 0x23, 0xa3, 0xe9, 0x6f, 0x0b, 0x4c, 0xaf, 0x43, 0x2a, 0xb3, 0xba,
	0xc8, 0x27, 0x85, 0x34, 0x06, 0xe7, 0x3d, 0x0d, 0x42, 0xa3, 0xe9, 0xef, 0x8b, 0x88, 0xbd, 0x4d,
	0xde, 0x44, 0x2d, 0x5c, 0x94, 0xea, 0x9e, 0x2a, 0x77, 0x9d, 0x28, 0xa3, 0xb2, 0x49, 0x22, 0xed,
	0x4c, 0xc7, 0xbc, 0x6c, 0xfd, 0xe7, 0xdf, 0xc5, 0xd1, 0x6b, 0x30, 0x49, 0xed, 0x04, 0xee, 0x3e,
	0x4f, 0x5c, 0x6a, 0xaa, 0x7f, 0x48, 0x3f, 0x03, 0x9b, 0xe8, 0x32, 0xb3, 0x3c, 0x6f, 0x1e, 0x62,
	0x60, 0x18, 0x5d, 0xc6, 0xe3, 0xd8, 0x95, 0x0f, 0x5a, 0x46, 0x88, 0x81, 0x69, 0x38, 0x16, 0x8f,
	0xac, 0xca, 0x32, 0x59, 0xd8, 0x99, 0x8a, 0x9d, 0x20, 0xf4, 0xca, 0x41, 0x3f, 0x03, 0x9d, 0x3d,
	0xcc, 0xc8, 0xc6, 0x30, 0x03, 0x0c, 0x2d, 0x73, 0x00, 0x39, 0xee, 0xb0, 0xb4, 0xd9, 0x70, 0x11,
	0x84, 0xa0, 0xf4, 0x18, 0x14, 0x79, 0x9a, 0xb6, 0x52, 0x1f, 0x05, 0x21, 0xd8, 0x5c, 0x1f, 0x6c,
	0xc4, 0x1e, 0x06, 0x21, 0x18, 0x5d, 0x3d, 0x80, 0x22, 0xee, 0xc2, 0x56, 0xee, 0xe3, 0x30, 0x05,
	0xb3, 0xeb, 0x5b, 0x38, 0x96, 0x89, 0x73, 0xba, 0x20, 0x04, 0x9b, 0xeb, 0x5b, 0x57, 0x65, 0xa2,
	0x70, 0x36, 0x17, 0xa6, 0x60, 0x73, 0xf5, 0x80, 0xdd, 0x21, 0x1b, 0x5d, 0x7a, 0x1f, 0xce, 0xd3,
	0x1c, 0xb8, 0x5e, 0x1d, 0x01, 0x2f, 0x49, 0x30, 0xa2, 0x39, 0xf9, 0xd3, 0xd5, 0x11, 0xf0, 0xba,
	0xd4, 0x03, 0x34, 0xc3, 0x5d, 0x73, 0x37, 0x69, 0x6e, 0xd3, 0xbd, 0x20, 0x58, 0xb2, 0x2a, 0x1b,
	0xe7, 0xbe, 0xc6, 0xe8, 0xe9, 0x71, 0x58, 0x6f, 0x94, 0xbd, 0x42, 0x6e, 0x2c, 0xc7, 0x19, 0xc9,
	0x0b, 0xf8, 0x44, 0xb4, 0xaf, 0xc7, 0x29, 0x21, 0x58, 0x7d, 0x27, 0x76, 0xf3, 0x21, 0x13, 0x35,
	0x2e, 0xad, 0xc8, 0x63, 0xe9, 0x0b, 0xf1, 0x0c, 0x71, 0x58, 0x93, 0xd4, 0x9b, 0x5c, 0x82, 0x27,
	0xc7, 0x87, 0x44, 0xf9, 0xc6, 0xa1, 0xaa, 0xb6, 0x42, 0x14, 0x1b, 0x82, 0x2d, 0xff, 0x21, 0x87,
	0x92, 0xe0, 0xb1, 0xf5, 0x4f, 0xd0, 0x13, 0xf4, 0x12, 0x6c, 0x0b, 0xb6, 0xfc, 0x97, 0x3c, 0xc1,
	0x6a, 0x69, 0xa7, 0x2c, 0x7a, 0x01, 0x36, 0x05, 0x5b, 0xfe, 0x93, 0xba, 0xa4, 0x81, 0x97, 0x25,
	0x17, 0x53, 0xdf, 0x1b, 0xac, 0xe0, 0xd8, 0x22, 0x6c, 0xb1, 0x9b, 0xe4, 0x2a, 0x0e, 0xbb, 0x44,
	0x80, 0x7d, 0xb4, 0xfb, 0x56, 0x75, 0x18, 0xe3, 0xad, 0x21, 0xc6, 0x5b, 0x84, 0xd5, 0x47, 0x85,
	0x92, 0xe3, 0xa5, 0xcb, 0xaf, 0x36, 0x83, 0x18, 0x33, 0xb4, 0x09, 0xf9, 0x6b, 0x31, 0xf6, 0x11,
	0xb1, 0x34, 0xc2, 0x67, 0x29, 0x48, 0x31, 0x53, 0x9b, 0xec, 0x55, 0x72, 0x13, 0x69, 0x73, 0x81,
	0x27, 0xf7, 0xaf, 0x4f, 0x0b, 0xc2, 0x33, 0x6c, 0xb2, 0x4b, 0xe4, 0x02, 0x74, 0x9c, 0xd8, 0x76,
	0x7a, 0xe5, 0xdb, 0xc7, 0x06, 0x51, 0xef, 0x36, 0x28, 0xc2, 0xdf, 0xa0, 0x08, 0x1f, 0xda, 0xcd,
	0xe6, 0x61, 0x8a, 0x7a, 0xb7, 0xb1, 0x2f, 0x85, 0x41, 0xb8, 0xc0, 0x76, 0xa7, 0x45, 0x2f, 0xc0,
	0x9b, 0xdd, 0x86, 0x77, 0x70, 0x5c, 0x28, 0x99, 0x39, 0x5f, 0xf6, 0x8f, 0x4b, 0xe9, 0x1d, 0xae,
	0x8a, 0x40, 0xc5, 0x43, 0xb0, 0x21, 0x3f, 0x0c, 0x57, 0xe7, 0x1f, 0x9d, 0xe0, 0x10, 0x44, 0xbd,
	0x43, 0xf8, 0x3e, 0xfb, 0x11, 0x91, 0x67, 0x63, 0x55, 0xa4, 0xcb, 0xb3, 0x17, 0x2b, 0x03, 0x50,
	0xff, 0x10, 0xf2, 0xe1, 0x47, 0xcc, 0x54, 0xc9, 0x24, 0x76, 0xad, 0xbe, 0xab, 0xcb, 0x20, 0xc5,
	0xaa, 0xec, 0xd0, 0x63, 0x46, 0x70, 0x18, 0xa6, 0xd8, 0xbc, 0x0e, 0xc1, 0x26, 0xda, 0x54, 0x34,
	0x45, 0xbb, 0xa4, 0xbd, 0xaa, 0x57, 0x87, 0x60, 0x55, 0x0c, 0xd9, 0xeb, 0xe4, 0x76, 0x27, 0xa4,
	0x27, 0x0b, 0xf3, 0x33, 0x84, 0xa1, 0x2f, 0x0d, 0xdf, 0x7f, 0x01, 0xff, 0x23, 0xbd, 0xf7, 0x2c,
	0x00, 0x00, 0xff, 0xff, 0x60, 0x5b, 0x5c, 0x06, 0x3a, 0x0d, 0x00, 0x00,
}
