// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EKickOutReason int32

const (
	EKickOutReason_UNKNOWN           EKickOutReason = 0
	EKickOutReason_HEARTBEAT_TIMEOUT EKickOutReason = 1
	EKickOutReason_MULTI_PLACE_LOGIN EKickOutReason = 2
)

var EKickOutReason_name = map[int32]string{
	0: "UNKNOWN",
	1: "HEARTBEAT_TIMEOUT",
	2: "MULTI_PLACE_LOGIN",
}

var EKickOutReason_value = map[string]int32{
	"UNKNOWN":           0,
	"HEARTBEAT_TIMEOUT": 1,
	"MULTI_PLACE_LOGIN": 2,
}

func (x EKickOutReason) String() string {
	return proto.EnumName(EKickOutReason_name, int32(x))
}

func (EKickOutReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

// 玩家数据段
type ERoleSectionFlag int32

const (
	ERoleSectionFlag__ERoleSectionFlag_ZERO ERoleSectionFlag = 0
	ERoleSectionFlag_ALL                    ERoleSectionFlag = -1
	ERoleSectionFlag_REGISTER_INFO          ERoleSectionFlag = 1
	ERoleSectionFlag_LOGIN_INFO             ERoleSectionFlag = 2
	ERoleSectionFlag_DESC_INFO              ERoleSectionFlag = 4
	ERoleSectionFlag_BASIC_INFO             ERoleSectionFlag = 8
	ERoleSectionFlag_INVENTORY_INFO         ERoleSectionFlag = 16
	ERoleSectionFlag_ICON_INFO              ERoleSectionFlag = 32
	ERoleSectionFlag_MALL_INFO              ERoleSectionFlag = 64
	ERoleSectionFlag_MAIN_TASK_INFO         ERoleSectionFlag = 128
	ERoleSectionFlag_GUILD_INFO             ERoleSectionFlag = 256
	ERoleSectionFlag_GUIDE_INFO             ERoleSectionFlag = 512
	ERoleSectionFlag_OPEN_FUNC_INFO         ERoleSectionFlag = 1024
	ERoleSectionFlag_ACTVITY_TASK_INFO      ERoleSectionFlag = 2048
)

var ERoleSectionFlag_name = map[int32]string{
	0:    "_ERoleSectionFlag_ZERO",
	-1:   "ALL",
	1:    "REGISTER_INFO",
	2:    "LOGIN_INFO",
	4:    "DESC_INFO",
	8:    "BASIC_INFO",
	16:   "INVENTORY_INFO",
	32:   "ICON_INFO",
	64:   "MALL_INFO",
	128:  "MAIN_TASK_INFO",
	256:  "GUILD_INFO",
	512:  "GUIDE_INFO",
	1024: "OPEN_FUNC_INFO",
	2048: "ACTVITY_TASK_INFO",
}

var ERoleSectionFlag_value = map[string]int32{
	"_ERoleSectionFlag_ZERO": 0,
	"ALL":                    -1,
	"REGISTER_INFO":          1,
	"LOGIN_INFO":             2,
	"DESC_INFO":              4,
	"BASIC_INFO":             8,
	"INVENTORY_INFO":         16,
	"ICON_INFO":              32,
	"MALL_INFO":              64,
	"MAIN_TASK_INFO":         128,
	"GUILD_INFO":             256,
	"GUIDE_INFO":             512,
	"OPEN_FUNC_INFO":         1024,
	"ACTVITY_TASK_INFO":      2048,
}

func (x ERoleSectionFlag) String() string {
	return proto.EnumName(ERoleSectionFlag_name, int32(x))
}

func (ERoleSectionFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

// 一些常用的道具ID
type EItemID int32

const (
	EItemID__ITEM_ID_NONE    EItemID = 0
	EItemID_GOLD             EItemID = 10101002
	EItemID_DIAMOND          EItemID = 10101003
	EItemID_MONEY            EItemID = 10101004
	EItemID_GUILDGOLD        EItemID = 10101007
	EItemID_GUILDEXP         EItemID = 10101008
	EItemID_LIVENESS         EItemID = 10101009
	EItemID_SINEW            EItemID = 10101001
	EItemID_EXP              EItemID = 10201001
	EItemID_CHANGE_NAME_CARD EItemID = 20101001
)

var EItemID_name = map[int32]string{
	0:        "_ITEM_ID_NONE",
	10101002: "GOLD",
	10101003: "DIAMOND",
	10101004: "MONEY",
	10101007: "GUILDGOLD",
	10101008: "GUILDEXP",
	10101009: "LIVENESS",
	10101001: "SINEW",
	10201001: "EXP",
	20101001: "CHANGE_NAME_CARD",
}

var EItemID_value = map[string]int32{
	"_ITEM_ID_NONE":    0,
	"GOLD":             10101002,
	"DIAMOND":          10101003,
	"MONEY":            10101004,
	"GUILDGOLD":        10101007,
	"GUILDEXP":         10101008,
	"LIVENESS":         10101009,
	"SINEW":            10101001,
	"EXP":              10201001,
	"CHANGE_NAME_CARD": 20101001,
}

func (x EItemID) String() string {
	return proto.EnumName(EItemID_name, int32(x))
}

func (EItemID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

type EItemType int32

const (
	EItemType__ITEM_TYPE_NONE EItemType = 0
	EItemType_DROP            EItemType = 9
)

var EItemType_name = map[int32]string{
	0: "_ITEM_TYPE_NONE",
	9: "DROP",
}

var EItemType_value = map[string]int32{
	"_ITEM_TYPE_NONE": 0,
	"DROP":            9,
}

func (x EItemType) String() string {
	return proto.EnumName(EItemType_name, int32(x))
}

func (EItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

// 道具类型
type EItemMainType int32

const (
	EItemMainType__ITEM_MAIN_TYPE_NONE EItemMainType = 0
	EItemMainType_ICON                 EItemMainType = 701
	EItemMainType_HERO_CARD            EItemMainType = 401
	EItemMainType_EQUIP                EItemMainType = 501
	EItemMainType_ARTIFACT             EItemMainType = 601
	EItemMainType_PACKAGE              EItemMainType = 901
)

var EItemMainType_name = map[int32]string{
	0:   "_ITEM_MAIN_TYPE_NONE",
	701: "ICON",
	401: "HERO_CARD",
	501: "EQUIP",
	601: "ARTIFACT",
	901: "PACKAGE",
}

var EItemMainType_value = map[string]int32{
	"_ITEM_MAIN_TYPE_NONE": 0,
	"ICON":                 701,
	"HERO_CARD":            401,
	"EQUIP":                501,
	"ARTIFACT":             601,
	"PACKAGE":              901,
}

func (x EItemMainType) String() string {
	return proto.EnumName(EItemMainType_name, int32(x))
}

func (EItemMainType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

type EItemSubType int32

const (
	EItemSubType__ITEM_SUB_TYPE_NONE EItemSubType = 0
	EItemSubType_ICON_ICON           EItemSubType = 70101
	EItemSubType_ICON_FRAME          EItemSubType = 70102
)

var EItemSubType_name = map[int32]string{
	0:     "_ITEM_SUB_TYPE_NONE",
	70101: "ICON_ICON",
	70102: "ICON_FRAME",
}

var EItemSubType_value = map[string]int32{
	"_ITEM_SUB_TYPE_NONE": 0,
	"ICON_ICON":           70101,
	"ICON_FRAME":          70102,
}

func (x EItemSubType) String() string {
	return proto.EnumName(EItemSubType_name, int32(x))
}

func (EItemSubType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

// 红点系统枚举
type ERedPointSystem int32

const (
	ERedPointSystem__RED_POINT_SYSTEM_NONE ERedPointSystem = 0
	ERedPointSystem_RED_POINT_ICON         ERedPointSystem = 1
	ERedPointSystem_RED_POINT_FRAME        ERedPointSystem = 2
	ERedPointSystem_RED_POINT_CARD         ERedPointSystem = 3
	ERedPointSystem_RED_POINT_ACHIEVEMENT  ERedPointSystem = 4
)

var ERedPointSystem_name = map[int32]string{
	0: "_RED_POINT_SYSTEM_NONE",
	1: "RED_POINT_ICON",
	2: "RED_POINT_FRAME",
	3: "RED_POINT_CARD",
	4: "RED_POINT_ACHIEVEMENT",
}

var ERedPointSystem_value = map[string]int32{
	"_RED_POINT_SYSTEM_NONE": 0,
	"RED_POINT_ICON":         1,
	"RED_POINT_FRAME":        2,
	"RED_POINT_CARD":         3,
	"RED_POINT_ACHIEVEMENT":  4,
}

func (x ERedPointSystem) String() string {
	return proto.EnumName(ERedPointSystem_name, int32(x))
}

func (ERedPointSystem) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

type MailType int32

const (
	MailType__MAIL_TYPE_NONE           MailType = 0
	MailType_MAIL_TYPE_SYSTEM          MailType = 1
	MailType_MAIL_TYPE_SYSTEM_TEMPLATE MailType = 2
	MailType_MAIL_TYPE_USER            MailType = 3
)

var MailType_name = map[int32]string{
	0: "_MAIL_TYPE_NONE",
	1: "MAIL_TYPE_SYSTEM",
	2: "MAIL_TYPE_SYSTEM_TEMPLATE",
	3: "MAIL_TYPE_USER",
}

var MailType_value = map[string]int32{
	"_MAIL_TYPE_NONE":           0,
	"MAIL_TYPE_SYSTEM":          1,
	"MAIL_TYPE_SYSTEM_TEMPLATE": 2,
	"MAIL_TYPE_USER":            3,
}

func (x MailType) String() string {
	return proto.EnumName(MailType_name, int32(x))
}

func (MailType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

// 聊天频道
type ChatChannel int32

const (
	ChatChannel__CHAT_CHANNEL_NONE  ChatChannel = 0
	ChatChannel_CHAT_CHANNEL_HALL   ChatChannel = 1
	ChatChannel_CHAT_CHANNEL_GUILD  ChatChannel = 2
	ChatChannel_CHAT_CHANNEL_FRIEND ChatChannel = 3
)

var ChatChannel_name = map[int32]string{
	0: "_CHAT_CHANNEL_NONE",
	1: "CHAT_CHANNEL_HALL",
	2: "CHAT_CHANNEL_GUILD",
	3: "CHAT_CHANNEL_FRIEND",
}

var ChatChannel_value = map[string]int32{
	"_CHAT_CHANNEL_NONE":  0,
	"CHAT_CHANNEL_HALL":   1,
	"CHAT_CHANNEL_GUILD":  2,
	"CHAT_CHANNEL_FRIEND": 3,
}

func (x ChatChannel) String() string {
	return proto.EnumName(ChatChannel_name, int32(x))
}

func (ChatChannel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

// 任务更新方法
type TaskCountType int32

const (
	TaskCountType__TASK_COUNT_TYPE_NONE TaskCountType = 0
	TaskCountType_TASK_COUNT_TYPE_ADD   TaskCountType = 1
	TaskCountType_TASK_COUNT_TYPE_MAX   TaskCountType = 2
)

var TaskCountType_name = map[int32]string{
	0: "_TASK_COUNT_TYPE_NONE",
	1: "TASK_COUNT_TYPE_ADD",
	2: "TASK_COUNT_TYPE_MAX",
}

var TaskCountType_value = map[string]int32{
	"_TASK_COUNT_TYPE_NONE": 0,
	"TASK_COUNT_TYPE_ADD":   1,
	"TASK_COUNT_TYPE_MAX":   2,
}

func (x TaskCountType) String() string {
	return proto.EnumName(TaskCountType_name, int32(x))
}

func (TaskCountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

type TaskName int32

const (
	TaskName__TASK_NAME_NONE       TaskName = 0
	TaskName_TASK_ROLE_LEVEL       TaskName = 1
	TaskName_TASK_PASS_INSTANCE    TaskName = 2
	TaskName_TASK_USE_ITEM         TaskName = 3
	TaskName_TASK_GENREAL_INSTANCE TaskName = 4
	TaskName_TASK_ELITE_INSTANCE   TaskName = 5
	TaskName_TASK_EVERYDAY_LOGIN   TaskName = 6
	TaskName_TASK_TODAY_LOGIN      TaskName = 7
	TaskName_TASK_HERO_LEVEL       TaskName = 8
	TaskName_TASK_HERO_STAR        TaskName = 9
	TaskName_TASK_HERO_QUALITY     TaskName = 10
	TaskName_TASK_HERO_SKILL_LEVEL TaskName = 11
)

var TaskName_name = map[int32]string{
	0:  "_TASK_NAME_NONE",
	1:  "TASK_ROLE_LEVEL",
	2:  "TASK_PASS_INSTANCE",
	3:  "TASK_USE_ITEM",
	4:  "TASK_GENREAL_INSTANCE",
	5:  "TASK_ELITE_INSTANCE",
	6:  "TASK_EVERYDAY_LOGIN",
	7:  "TASK_TODAY_LOGIN",
	8:  "TASK_HERO_LEVEL",
	9:  "TASK_HERO_STAR",
	10: "TASK_HERO_QUALITY",
	11: "TASK_HERO_SKILL_LEVEL",
}

var TaskName_value = map[string]int32{
	"_TASK_NAME_NONE":       0,
	"TASK_ROLE_LEVEL":       1,
	"TASK_PASS_INSTANCE":    2,
	"TASK_USE_ITEM":         3,
	"TASK_GENREAL_INSTANCE": 4,
	"TASK_ELITE_INSTANCE":   5,
	"TASK_EVERYDAY_LOGIN":   6,
	"TASK_TODAY_LOGIN":      7,
	"TASK_HERO_LEVEL":       8,
	"TASK_HERO_STAR":        9,
	"TASK_HERO_QUALITY":     10,
	"TASK_HERO_SKILL_LEVEL": 11,
}

func (x TaskName) String() string {
	return proto.EnumName(TaskName_name, int32(x))
}

func (TaskName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

type ActvityTaskUpdateType int32

const (
	ActvityTaskUpdateType_AT_NULL_TYPE   ActvityTaskUpdateType = 0
	ActvityTaskUpdateType_AT_UPDATE_TYPE ActvityTaskUpdateType = 1
	ActvityTaskUpdateType_AT_DELETE_TYPE ActvityTaskUpdateType = 2
)

var ActvityTaskUpdateType_name = map[int32]string{
	0: "AT_NULL_TYPE",
	1: "AT_UPDATE_TYPE",
	2: "AT_DELETE_TYPE",
}

var ActvityTaskUpdateType_value = map[string]int32{
	"AT_NULL_TYPE":   0,
	"AT_UPDATE_TYPE": 1,
	"AT_DELETE_TYPE": 2,
}

func (x ActvityTaskUpdateType) String() string {
	return proto.EnumName(ActvityTaskUpdateType_name, int32(x))
}

func (ActvityTaskUpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

type ActvityTaskCompareType int32

const (
	ActvityTaskCompareType_C_NULL_TYPE          ActvityTaskCompareType = 0
	ActvityTaskCompareType_EQUAL_TYPE           ActvityTaskCompareType = 1
	ActvityTaskCompareType_BIG_AND_EQUAL_TYPE   ActvityTaskCompareType = 2
	ActvityTaskCompareType_SMALL_AND_EQUAL_TYPE ActvityTaskCompareType = 3
)

var ActvityTaskCompareType_name = map[int32]string{
	0: "C_NULL_TYPE",
	1: "EQUAL_TYPE",
	2: "BIG_AND_EQUAL_TYPE",
	3: "SMALL_AND_EQUAL_TYPE",
}

var ActvityTaskCompareType_value = map[string]int32{
	"C_NULL_TYPE":          0,
	"EQUAL_TYPE":           1,
	"BIG_AND_EQUAL_TYPE":   2,
	"SMALL_AND_EQUAL_TYPE": 3,
}

func (x ActvityTaskCompareType) String() string {
	return proto.EnumName(ActvityTaskCompareType_name, int32(x))
}

func (ActvityTaskCompareType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{12}
}

type ActvityTaskAwardType int32

const (
	ActvityTaskAwardType_A_NULL_TYPE    ActvityTaskAwardType = 0
	ActvityTaskAwardType_UNCLAIMED_TYPE ActvityTaskAwardType = 1
	ActvityTaskAwardType_AUTO_TYPE      ActvityTaskAwardType = 2
	ActvityTaskAwardType_ALREADY_TYPE   ActvityTaskAwardType = 3
)

var ActvityTaskAwardType_name = map[int32]string{
	0: "A_NULL_TYPE",
	1: "UNCLAIMED_TYPE",
	2: "AUTO_TYPE",
	3: "ALREADY_TYPE",
}

var ActvityTaskAwardType_value = map[string]int32{
	"A_NULL_TYPE":    0,
	"UNCLAIMED_TYPE": 1,
	"AUTO_TYPE":      2,
	"ALREADY_TYPE":   3,
}

func (x ActvityTaskAwardType) String() string {
	return proto.EnumName(ActvityTaskAwardType_name, int32(x))
}

func (ActvityTaskAwardType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{13}
}

type ActvityTaskReceiveType int32

const (
	ActvityTaskReceiveType_R_NULL_TYPE         ActvityTaskReceiveType = 0
	ActvityTaskReceiveType_MANUAL_RECEIVE_TYPE ActvityTaskReceiveType = 1
	ActvityTaskReceiveType_AUTO_RECEIVE_TYPE   ActvityTaskReceiveType = 2
)

var ActvityTaskReceiveType_name = map[int32]string{
	0: "R_NULL_TYPE",
	1: "MANUAL_RECEIVE_TYPE",
	2: "AUTO_RECEIVE_TYPE",
}

var ActvityTaskReceiveType_value = map[string]int32{
	"R_NULL_TYPE":         0,
	"MANUAL_RECEIVE_TYPE": 1,
	"AUTO_RECEIVE_TYPE":   2,
}

func (x ActvityTaskReceiveType) String() string {
	return proto.EnumName(ActvityTaskReceiveType_name, int32(x))
}

func (ActvityTaskReceiveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{14}
}

// 每个回包都需要包含的返回值
type Ret struct {
	Ret                  int32    `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Argv                 int32    `protobuf:"varint,3,opt,name=argv,proto3" json:"argv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ret) Reset()         { *m = Ret{} }
func (m *Ret) String() string { return proto.CompactTextString(m) }
func (*Ret) ProtoMessage()    {}
func (*Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ret.Unmarshal(m, b)
}
func (m *Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ret.Marshal(b, m, deterministic)
}
func (m *Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ret.Merge(m, src)
}
func (m *Ret) XXX_Size() int {
	return xxx_messageInfo_Ret.Size(m)
}
func (m *Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_Ret proto.InternalMessageInfo

func (m *Ret) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *Ret) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Ret) GetArgv() int32 {
	if m != nil {
		return m.Argv
	}
	return 0
}

func init() {
	proto.RegisterEnum("g1.protocol.EKickOutReason", EKickOutReason_name, EKickOutReason_value)
	proto.RegisterEnum("g1.protocol.ERoleSectionFlag", ERoleSectionFlag_name, ERoleSectionFlag_value)
	proto.RegisterEnum("g1.protocol.EItemID", EItemID_name, EItemID_value)
	proto.RegisterEnum("g1.protocol.EItemType", EItemType_name, EItemType_value)
	proto.RegisterEnum("g1.protocol.EItemMainType", EItemMainType_name, EItemMainType_value)
	proto.RegisterEnum("g1.protocol.EItemSubType", EItemSubType_name, EItemSubType_value)
	proto.RegisterEnum("g1.protocol.ERedPointSystem", ERedPointSystem_name, ERedPointSystem_value)
	proto.RegisterEnum("g1.protocol.MailType", MailType_name, MailType_value)
	proto.RegisterEnum("g1.protocol.ChatChannel", ChatChannel_name, ChatChannel_value)
	proto.RegisterEnum("g1.protocol.TaskCountType", TaskCountType_name, TaskCountType_value)
	proto.RegisterEnum("g1.protocol.TaskName", TaskName_name, TaskName_value)
	proto.RegisterEnum("g1.protocol.ActvityTaskUpdateType", ActvityTaskUpdateType_name, ActvityTaskUpdateType_value)
	proto.RegisterEnum("g1.protocol.ActvityTaskCompareType", ActvityTaskCompareType_name, ActvityTaskCompareType_value)
	proto.RegisterEnum("g1.protocol.ActvityTaskAwardType", ActvityTaskAwardType_name, ActvityTaskAwardType_value)
	proto.RegisterEnum("g1.protocol.ActvityTaskReceiveType", ActvityTaskReceiveType_name, ActvityTaskReceiveType_value)
	proto.RegisterType((*Ret)(nil), "g1.protocol.Ret")
}

func init() {
	proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206)
}

var fileDescriptor_555bd8c177793206 = []byte{
	// 1088 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x95, 0x3f, 0x6f, 0xdb, 0xc6,
	0x1b, 0xc7, 0x43, 0x4a, 0x8e, 0xa5, 0xc7, 0x96, 0x74, 0x3e, 0xc7, 0x7f, 0xf2, 0x03, 0x7e, 0x40,
	0xd0, 0x29, 0xe0, 0x50, 0xa0, 0xe8, 0x5c, 0xa0, 0x67, 0xf2, 0xb1, 0x74, 0xd5, 0xf1, 0xc8, 0x1c,
	0x8f, 0x4a, 0x54, 0x14, 0x20, 0x18, 0x85, 0x70, 0x84, 0x58, 0x92, 0x61, 0x33, 0x29, 0xb2, 0x65,
	0xc9, 0x90, 0xb6, 0x40, 0x9b, 0xad, 0x4b, 0xa7, 0x4c, 0x5d, 0xfa, 0x0e, 0xba, 0x74, 0xec, 0xd2,
	0xa9, 0x05, 0xfa, 0x0e, 0x3a, 0xb5, 0x53, 0xe7, 0x16, 0x77, 0xa4, 0x24, 0xcb, 0xa8, 0x07, 0x83,
	0xf7, 0x79, 0x1e, 0x7e, 0x9f, 0xef, 0xf3, 0xdc, 0xf1, 0x04, 0xbb, 0x93, 0xc5, 0x6c, 0xb6, 0x98,
	0xbf, 0x7f, 0x71, 0xb9, 0x28, 0x17, 0x74, 0xe7, 0xec, 0x83, 0xea, 0x69, 0xb2, 0x38, 0x7f, 0xef,
	0x23, 0x68, 0xa8, 0xa2, 0xa4, 0x04, 0x1a, 0x97, 0x45, 0x79, 0xec, 0xdc, 0x73, 0xee, 0x6f, 0x29,
	0xf3, 0x68, 0xc8, 0xec, 0xea, 0xec, 0xd8, 0xbd, 0xe7, 0xdc, 0x6f, 0x2b, 0xf3, 0x48, 0x29, 0x34,
	0xf3, 0xcb, 0xb3, 0x17, 0xc7, 0x0d, 0x9b, 0x64, 0x9f, 0xbd, 0x21, 0x74, 0x71, 0x38, 0x9d, 0x3c,
	0x8b, 0x9e, 0x97, 0xaa, 0xc8, 0xaf, 0x16, 0x73, 0xba, 0x03, 0xdb, 0xa9, 0x1c, 0xca, 0xe8, 0xa1,
	0x24, 0xb7, 0xe8, 0x01, 0xec, 0x0d, 0x90, 0x29, 0x7d, 0x82, 0x4c, 0x67, 0x9a, 0x87, 0x18, 0xa5,
	0x9a, 0x38, 0x06, 0x87, 0xa9, 0xd0, 0x3c, 0x8b, 0x05, 0xf3, 0x31, 0x13, 0x51, 0x9f, 0x4b, 0xe2,
	0x7a, 0xdf, 0xba, 0x40, 0x50, 0x2d, 0xce, 0x8b, 0xa4, 0x98, 0x94, 0xd3, 0xc5, 0xfc, 0xf4, 0x3c,
	0x3f, 0xa3, 0xff, 0x83, 0xc3, 0xec, 0x26, 0xcc, 0x3e, 0x45, 0x15, 0x91, 0x5b, 0xc6, 0x23, 0x13,
	0x82, 0xfc, 0xb3, 0xfc, 0x73, 0xe8, 0x1e, 0x74, 0x14, 0xf6, 0x79, 0xa2, 0x51, 0x65, 0x5c, 0x9e,
	0x46, 0xc4, 0xa1, 0x5d, 0x00, 0x5b, 0xa0, 0x5a, 0xbb, 0xb4, 0x03, 0xed, 0x00, 0x13, 0xbf, 0x5a,
	0x36, 0x4d, 0xf8, 0x84, 0x25, 0xbc, 0x5e, 0xb7, 0x28, 0x85, 0x2e, 0x97, 0x23, 0x94, 0x3a, 0x52,
	0xe3, 0x8a, 0x11, 0xf3, 0x0a, 0xf7, 0xa3, 0x5a, 0xe1, 0x9e, 0x59, 0x86, 0x4c, 0x88, 0x6a, 0xf9,
	0x31, 0xdd, 0x87, 0x6e, 0xc8, 0xb8, 0xcc, 0x34, 0x4b, 0x86, 0x15, 0x7b, 0xe5, 0xd0, 0x1e, 0x40,
	0x3f, 0xe5, 0x22, 0xa8, 0x81, 0x5b, 0x83, 0x00, 0x6b, 0xd0, 0x34, 0xaf, 0x45, 0x31, 0xca, 0xec,
	0x34, 0x95, 0x75, 0xf1, 0x57, 0x2d, 0x7a, 0x08, 0x7b, 0xcc, 0xd7, 0x23, 0xae, 0xc7, 0xd7, 0xe5,
	0x88, 0xf7, 0x83, 0x03, 0xdb, 0xc8, 0xcb, 0x62, 0xc6, 0x03, 0xd3, 0x63, 0xc6, 0x35, 0x86, 0x19,
	0x0f, 0x32, 0x19, 0x49, 0x24, 0xb7, 0xe8, 0x0e, 0x34, 0xfb, 0x91, 0x08, 0xc8, 0x17, 0x3f, 0xfd,
	0x61, 0x3a, 0xda, 0x0e, 0x38, 0x0b, 0x23, 0x19, 0x90, 0x2f, 0xcd, 0x7a, 0x17, 0xb6, 0xc2, 0x48,
	0xe2, 0x98, 0x7c, 0x65, 0x56, 0x04, 0xda, 0xd6, 0x98, 0xcd, 0xff, 0xda, 0x90, 0x1e, 0xb4, 0x2c,
	0xc1, 0x47, 0x31, 0xf9, 0xa6, 0x06, 0x82, 0x8f, 0x50, 0x62, 0x92, 0x90, 0xb7, 0xb5, 0x42, 0xc2,
	0x25, 0x3e, 0x24, 0x6f, 0xcc, 0x0a, 0xa0, 0x61, 0x52, 0xbf, 0xff, 0xe5, 0xcf, 0x26, 0x3d, 0x02,
	0xe2, 0x0f, 0x98, 0xec, 0x63, 0x26, 0x59, 0x88, 0x99, 0xcf, 0x54, 0x40, 0xde, 0xfc, 0xf5, 0x73,
	0xdb, 0xf3, 0xa0, 0x6d, 0xfd, 0xea, 0x97, 0x17, 0x05, 0xdd, 0x87, 0x5e, 0xe5, 0x58, 0x8f, 0x63,
	0x5c, 0x7a, 0x6e, 0x41, 0x33, 0x50, 0x51, 0x4c, 0xda, 0xde, 0x0c, 0x3a, 0x36, 0x37, 0xcc, 0xa7,
	0x73, 0x9b, 0x7f, 0x0c, 0x77, 0xaa, 0xfc, 0x6a, 0xae, 0xd7, 0x5e, 0x6a, 0x43, 0xd3, 0xec, 0x04,
	0xf9, 0x71, 0x8b, 0x76, 0xa1, 0x3d, 0x40, 0x15, 0x55, 0x35, 0xdf, 0x36, 0x28, 0xc0, 0x16, 0x3e,
	0x48, 0x79, 0x4c, 0xfe, 0x6e, 0xd0, 0x0e, 0xb4, 0x98, 0xd2, 0xfc, 0x94, 0xf9, 0x9a, 0xfc, 0x6e,
	0xfc, 0x6f, 0xc7, 0xcc, 0x1f, 0xb2, 0x3e, 0x92, 0xd7, 0xdb, 0xde, 0x27, 0xb0, 0x6b, 0xcb, 0x25,
	0xcf, 0x1f, 0xdb, 0x6a, 0x47, 0xb0, 0x5f, 0x55, 0x4b, 0xd2, 0x93, 0x8d, 0x62, 0xbd, 0xe5, 0xb6,
	0x9b, 0x8a, 0xbf, 0xbe, 0x33, 0xb3, 0x03, 0x0b, 0x4e, 0x15, 0x0b, 0x91, 0xfc, 0xf6, 0xae, 0xe9,
	0xbd, 0x76, 0xa0, 0x87, 0xaa, 0x78, 0x12, 0x2f, 0xa6, 0xf3, 0x32, 0x79, 0x79, 0x55, 0x16, 0x33,
	0x7b, 0x62, 0x15, 0x06, 0x59, 0x1c, 0x71, 0xa9, 0xb3, 0x64, 0x9c, 0x18, 0xed, 0x5a, 0x92, 0x42,
	0x77, 0x1d, 0xb2, 0xba, 0x8e, 0x99, 0xce, 0x9a, 0x55, 0xd2, 0xee, 0x66, 0xa2, 0x6d, 0xb1, 0x41,
	0xef, 0xc2, 0xc1, 0x9a, 0x31, 0x7f, 0xc0, 0x71, 0x84, 0x21, 0x4a, 0x4d, 0x9a, 0xde, 0x53, 0x68,
	0x85, 0xf9, 0xf4, 0x7c, 0x35, 0xed, 0x90, 0x71, 0xb1, 0xd1, 0xcb, 0x1d, 0x20, 0x6b, 0x56, 0x79,
	0x22, 0x0e, 0xfd, 0x3f, 0xdc, 0xbd, 0x49, 0x33, 0x8d, 0x61, 0x2c, 0x98, 0xae, 0x4d, 0xac, 0xc3,
	0x69, 0x82, 0x8a, 0x34, 0xbc, 0x19, 0xec, 0xf8, 0x4f, 0xf3, 0xd2, 0x7f, 0x9a, 0xcf, 0xe7, 0xc5,
	0x39, 0x3d, 0x04, 0x9a, 0xf9, 0x03, 0xa6, 0xcd, 0x3f, 0x29, 0x51, 0x2c, 0xeb, 0x1d, 0xc0, 0xde,
	0x06, 0x1e, 0x98, 0x0f, 0xd5, 0x31, 0xe9, 0x1b, 0xd8, 0x1e, 0x3c, 0xe2, 0x9a, 0x3d, 0xd8, 0xe0,
	0xa7, 0x8a, 0xa3, 0x0c, 0x48, 0xc3, 0xfb, 0x0c, 0x3a, 0x3a, 0xbf, 0x7a, 0xe6, 0x2f, 0x9e, 0xcf,
	0x4b, 0xdb, 0xdd, 0x5d, 0x38, 0xa8, 0x3e, 0x0d, 0x3f, 0x4a, 0xa5, 0xde, 0xe8, 0xf1, 0x08, 0xf6,
	0x6f, 0x46, 0x58, 0x10, 0x10, 0xe7, 0xbf, 0x02, 0x21, 0x7b, 0x44, 0x5c, 0xef, 0x3b, 0x17, 0x5a,
	0x46, 0x5e, 0xe6, 0xb3, 0x6a, 0x6e, 0x36, 0xcd, 0x1e, 0xe5, 0x5a, 0x73, 0x1f, 0x7a, 0x96, 0xa9,
	0x48, 0x60, 0x26, 0x70, 0x84, 0x75, 0x17, 0x16, 0xc6, 0x2c, 0x49, 0x32, 0x2e, 0x13, 0xcd, 0xa4,
	0x6f, 0xe6, 0xb5, 0x07, 0x1d, 0xcb, 0xd3, 0x04, 0xed, 0x89, 0xaa, 0xf6, 0xcc, 0xa2, 0x3e, 0x4a,
	0x85, 0x4c, 0xac, 0xb3, 0x9b, 0x2b, 0x57, 0x28, 0xb8, 0xc6, 0x75, 0x60, 0x6b, 0x1d, 0x18, 0xa1,
	0x1a, 0x07, 0x6c, 0x5c, 0x5f, 0x90, 0xb7, 0xcd, 0x26, 0xda, 0x80, 0x8e, 0xd6, 0x74, 0x7b, 0x65,
	0xd1, 0x7e, 0x0d, 0x95, 0x45, 0x7b, 0x8d, 0xad, 0x61, 0xa2, 0x99, 0x22, 0x6d, 0xb3, 0x27, 0x6b,
	0xf6, 0x20, 0x65, 0x82, 0xeb, 0x31, 0x81, 0x95, 0xc5, 0x2a, 0x75, 0xc8, 0x85, 0xa8, 0x55, 0x76,
	0xbc, 0x07, 0x70, 0xc0, 0x26, 0xe5, 0x8b, 0x69, 0xf9, 0xd2, 0x4c, 0x29, 0xbd, 0x78, 0x92, 0x97,
	0x85, 0xdd, 0x05, 0x02, 0xbb, 0x4c, 0x67, 0x32, 0x15, 0xd5, 0xe1, 0xa8, 0x4e, 0x36, 0xd3, 0x59,
	0x1a, 0x07, 0x4c, 0x63, 0xc5, 0x9c, 0x9a, 0x05, 0x28, 0x70, 0xc9, 0x5c, 0xef, 0x19, 0x1c, 0x5e,
	0x93, 0xf4, 0x17, 0xb3, 0x8b, 0xfc, 0xb2, 0xd2, 0xec, 0xc1, 0x8e, 0xbf, 0x21, 0xd9, 0x05, 0x40,
	0x63, 0x73, 0x29, 0x77, 0x08, 0xf4, 0x84, 0xf7, 0x33, 0x26, 0x83, 0xec, 0x1a, 0x77, 0xcd, 0x75,
	0x91, 0xd8, 0x0b, 0xf9, 0x46, 0xc4, 0x9c, 0x9e, 0x3b, 0xd7, 0x8a, 0xb1, 0xcf, 0xf3, 0xcb, 0x27,
	0xcb, 0x52, 0xec, 0xa6, 0xfb, 0x54, 0xfa, 0x82, 0xf1, 0x10, 0x83, 0x65, 0xb9, 0x0e, 0xb4, 0x59,
	0xaa, 0xa3, 0x65, 0x15, 0xd3, 0xb2, 0x50, 0xc8, 0x82, 0xf1, 0x52, 0x7d, 0xbc, 0xd1, 0x8a, 0x2a,
	0x26, 0xc5, 0xf4, 0xc5, 0xaa, 0x15, 0xb5, 0xa1, 0x7f, 0x04, 0xfb, 0x21, 0x93, 0xc6, 0x99, 0x42,
	0x1f, 0xf9, 0x68, 0x35, 0xa2, 0x03, 0xd8, 0xb3, 0x45, 0x36, 0xb0, 0xfb, 0xf8, 0xb6, 0xfd, 0x81,
	0xfe, 0xf0, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xe4, 0xca, 0x29, 0xba, 0x07, 0x00, 0x00,
}
