// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbsvr.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBType_EDBType int32

const (
	DBType__DB_ZERO           DBType_EDBType = 0
	DBType_DB_TYPE_ROLE       DBType_EDBType = 1
	DBType_DB_TYPE_ACCOUNT    DBType_EDBType = 2
	DBType_DB_TYPE_BRIEF_INFO DBType_EDBType = 3
	DBType_DB_TYPE_RANK       DBType_EDBType = 4
	DBType_DB_TYPE_GUILD      DBType_EDBType = 5
	DBType_DB_TYPE_MAIL       DBType_EDBType = 6
	DBType_DB_TYPE_CHAT       DBType_EDBType = 7
	DBType_DB_TYPE_FRIEND     DBType_EDBType = 8
	DBType_DB_TYPE_MISC       DBType_EDBType = 99
)

var DBType_EDBType_name = map[int32]string{
	0:  "_DB_ZERO",
	1:  "DB_TYPE_ROLE",
	2:  "DB_TYPE_ACCOUNT",
	3:  "DB_TYPE_BRIEF_INFO",
	4:  "DB_TYPE_RANK",
	5:  "DB_TYPE_GUILD",
	6:  "DB_TYPE_MAIL",
	7:  "DB_TYPE_CHAT",
	8:  "DB_TYPE_FRIEND",
	99: "DB_TYPE_MISC",
}

var DBType_EDBType_value = map[string]int32{
	"_DB_ZERO":           0,
	"DB_TYPE_ROLE":       1,
	"DB_TYPE_ACCOUNT":    2,
	"DB_TYPE_BRIEF_INFO": 3,
	"DB_TYPE_RANK":       4,
	"DB_TYPE_GUILD":      5,
	"DB_TYPE_MAIL":       6,
	"DB_TYPE_CHAT":       7,
	"DB_TYPE_FRIEND":     8,
	"DB_TYPE_MISC":       99,
}

func (x DBType_EDBType) String() string {
	return proto.EnumName(DBType_EDBType_name, int32(x))
}

func (DBType_EDBType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{0, 0}
}

type DBType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBType) Reset()         { *m = DBType{} }
func (m *DBType) String() string { return proto.CompactTextString(m) }
func (*DBType) ProtoMessage()    {}
func (*DBType) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{0}
}

func (m *DBType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBType.Unmarshal(m, b)
}
func (m *DBType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBType.Marshal(b, m, deterministic)
}
func (m *DBType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBType.Merge(m, src)
}
func (m *DBType) XXX_Size() int {
	return xxx_messageInfo_DBType.Size(m)
}
func (m *DBType) XXX_DiscardUnknown() {
	xxx_messageInfo_DBType.DiscardUnknown(m)
}

var xxx_messageInfo_DBType proto.InternalMessageInfo

// DB_UID_GET_REQ
type DBUidGetReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUidGetReq) Reset()         { *m = DBUidGetReq{} }
func (m *DBUidGetReq) String() string { return proto.CompactTextString(m) }
func (*DBUidGetReq) ProtoMessage()    {}
func (*DBUidGetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{1}
}

func (m *DBUidGetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUidGetReq.Unmarshal(m, b)
}
func (m *DBUidGetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUidGetReq.Marshal(b, m, deterministic)
}
func (m *DBUidGetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUidGetReq.Merge(m, src)
}
func (m *DBUidGetReq) XXX_Size() int {
	return xxx_messageInfo_DBUidGetReq.Size(m)
}
func (m *DBUidGetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUidGetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBUidGetReq proto.InternalMessageInfo

func (m *DBUidGetReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBUidGetReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type DBUidGetRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUidGetRsp) Reset()         { *m = DBUidGetRsp{} }
func (m *DBUidGetRsp) String() string { return proto.CompactTextString(m) }
func (*DBUidGetRsp) ProtoMessage()    {}
func (*DBUidGetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{2}
}

func (m *DBUidGetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUidGetRsp.Unmarshal(m, b)
}
func (m *DBUidGetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUidGetRsp.Marshal(b, m, deterministic)
}
func (m *DBUidGetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUidGetRsp.Merge(m, src)
}
func (m *DBUidGetRsp) XXX_Size() int {
	return xxx_messageInfo_DBUidGetRsp.Size(m)
}
func (m *DBUidGetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUidGetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBUidGetRsp proto.InternalMessageInfo

func (m *DBUidGetRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBUidGetRsp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// DB_UID_MGET_REQ
type DBUidMGetReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	UidList              []uint64 `protobuf:"varint,2,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUidMGetReq) Reset()         { *m = DBUidMGetReq{} }
func (m *DBUidMGetReq) String() string { return proto.CompactTextString(m) }
func (*DBUidMGetReq) ProtoMessage()    {}
func (*DBUidMGetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{3}
}

func (m *DBUidMGetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUidMGetReq.Unmarshal(m, b)
}
func (m *DBUidMGetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUidMGetReq.Marshal(b, m, deterministic)
}
func (m *DBUidMGetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUidMGetReq.Merge(m, src)
}
func (m *DBUidMGetReq) XXX_Size() int {
	return xxx_messageInfo_DBUidMGetReq.Size(m)
}
func (m *DBUidMGetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUidMGetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBUidMGetReq proto.InternalMessageInfo

func (m *DBUidMGetReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBUidMGetReq) GetUidList() []uint64 {
	if m != nil {
		return m.UidList
	}
	return nil
}

type DBUidMGetRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	DataList             [][]byte `protobuf:"bytes,2,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUidMGetRsp) Reset()         { *m = DBUidMGetRsp{} }
func (m *DBUidMGetRsp) String() string { return proto.CompactTextString(m) }
func (*DBUidMGetRsp) ProtoMessage()    {}
func (*DBUidMGetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{4}
}

func (m *DBUidMGetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUidMGetRsp.Unmarshal(m, b)
}
func (m *DBUidMGetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUidMGetRsp.Marshal(b, m, deterministic)
}
func (m *DBUidMGetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUidMGetRsp.Merge(m, src)
}
func (m *DBUidMGetRsp) XXX_Size() int {
	return xxx_messageInfo_DBUidMGetRsp.Size(m)
}
func (m *DBUidMGetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUidMGetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBUidMGetRsp proto.InternalMessageInfo

func (m *DBUidMGetRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBUidMGetRsp) GetDataList() [][]byte {
	if m != nil {
		return m.DataList
	}
	return nil
}

// DB_UID_SET_REQ
type DBUidSetReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	IgnoreRsp            bool     `protobuf:"varint,4,opt,name=ignore_rsp,json=ignoreRsp,proto3" json:"ignore_rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUidSetReq) Reset()         { *m = DBUidSetReq{} }
func (m *DBUidSetReq) String() string { return proto.CompactTextString(m) }
func (*DBUidSetReq) ProtoMessage()    {}
func (*DBUidSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{5}
}

func (m *DBUidSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUidSetReq.Unmarshal(m, b)
}
func (m *DBUidSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUidSetReq.Marshal(b, m, deterministic)
}
func (m *DBUidSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUidSetReq.Merge(m, src)
}
func (m *DBUidSetReq) XXX_Size() int {
	return xxx_messageInfo_DBUidSetReq.Size(m)
}
func (m *DBUidSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUidSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBUidSetReq proto.InternalMessageInfo

func (m *DBUidSetReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBUidSetReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DBUidSetReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DBUidSetReq) GetIgnoreRsp() bool {
	if m != nil {
		return m.IgnoreRsp
	}
	return false
}

type DBUidSetRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	DbType               uint32   `protobuf:"varint,2,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUidSetRsp) Reset()         { *m = DBUidSetRsp{} }
func (m *DBUidSetRsp) String() string { return proto.CompactTextString(m) }
func (*DBUidSetRsp) ProtoMessage()    {}
func (*DBUidSetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{6}
}

func (m *DBUidSetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUidSetRsp.Unmarshal(m, b)
}
func (m *DBUidSetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUidSetRsp.Marshal(b, m, deterministic)
}
func (m *DBUidSetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUidSetRsp.Merge(m, src)
}
func (m *DBUidSetRsp) XXX_Size() int {
	return xxx_messageInfo_DBUidSetRsp.Size(m)
}
func (m *DBUidSetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUidSetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBUidSetRsp proto.InternalMessageInfo

func (m *DBUidSetRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBUidSetRsp) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

// DB_COMM_GET_REQ
type DBCommGetReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommGetReq) Reset()         { *m = DBCommGetReq{} }
func (m *DBCommGetReq) String() string { return proto.CompactTextString(m) }
func (*DBCommGetReq) ProtoMessage()    {}
func (*DBCommGetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{7}
}

func (m *DBCommGetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommGetReq.Unmarshal(m, b)
}
func (m *DBCommGetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommGetReq.Marshal(b, m, deterministic)
}
func (m *DBCommGetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommGetReq.Merge(m, src)
}
func (m *DBCommGetReq) XXX_Size() int {
	return xxx_messageInfo_DBCommGetReq.Size(m)
}
func (m *DBCommGetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommGetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommGetReq proto.InternalMessageInfo

func (m *DBCommGetReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommGetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DBCommGetRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommGetRsp) Reset()         { *m = DBCommGetRsp{} }
func (m *DBCommGetRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommGetRsp) ProtoMessage()    {}
func (*DBCommGetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{8}
}

func (m *DBCommGetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommGetRsp.Unmarshal(m, b)
}
func (m *DBCommGetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommGetRsp.Marshal(b, m, deterministic)
}
func (m *DBCommGetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommGetRsp.Merge(m, src)
}
func (m *DBCommGetRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommGetRsp.Size(m)
}
func (m *DBCommGetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommGetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommGetRsp proto.InternalMessageInfo

func (m *DBCommGetRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommGetRsp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// DB_COMM_MGET_REQ
type DBCommMGetReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	KeyList              []string `protobuf:"bytes,2,rep,name=key_list,json=keyList,proto3" json:"key_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommMGetReq) Reset()         { *m = DBCommMGetReq{} }
func (m *DBCommMGetReq) String() string { return proto.CompactTextString(m) }
func (*DBCommMGetReq) ProtoMessage()    {}
func (*DBCommMGetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{9}
}

func (m *DBCommMGetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommMGetReq.Unmarshal(m, b)
}
func (m *DBCommMGetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommMGetReq.Marshal(b, m, deterministic)
}
func (m *DBCommMGetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommMGetReq.Merge(m, src)
}
func (m *DBCommMGetReq) XXX_Size() int {
	return xxx_messageInfo_DBCommMGetReq.Size(m)
}
func (m *DBCommMGetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommMGetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommMGetReq proto.InternalMessageInfo

func (m *DBCommMGetReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommMGetReq) GetKeyList() []string {
	if m != nil {
		return m.KeyList
	}
	return nil
}

type DBCommMGetRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	DataList             [][]byte `protobuf:"bytes,2,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommMGetRsp) Reset()         { *m = DBCommMGetRsp{} }
func (m *DBCommMGetRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommMGetRsp) ProtoMessage()    {}
func (*DBCommMGetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{10}
}

func (m *DBCommMGetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommMGetRsp.Unmarshal(m, b)
}
func (m *DBCommMGetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommMGetRsp.Marshal(b, m, deterministic)
}
func (m *DBCommMGetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommMGetRsp.Merge(m, src)
}
func (m *DBCommMGetRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommMGetRsp.Size(m)
}
func (m *DBCommMGetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommMGetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommMGetRsp proto.InternalMessageInfo

func (m *DBCommMGetRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommMGetRsp) GetDataList() [][]byte {
	if m != nil {
		return m.DataList
	}
	return nil
}

// DB_COMM_SET_REQ
type DBCommSetReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	IgnoreRsp            bool     `protobuf:"varint,4,opt,name=ignore_rsp,json=ignoreRsp,proto3" json:"ignore_rsp,omitempty"`
	ExpireSeconds        int32    `protobuf:"varint,5,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommSetReq) Reset()         { *m = DBCommSetReq{} }
func (m *DBCommSetReq) String() string { return proto.CompactTextString(m) }
func (*DBCommSetReq) ProtoMessage()    {}
func (*DBCommSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{11}
}

func (m *DBCommSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommSetReq.Unmarshal(m, b)
}
func (m *DBCommSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommSetReq.Marshal(b, m, deterministic)
}
func (m *DBCommSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommSetReq.Merge(m, src)
}
func (m *DBCommSetReq) XXX_Size() int {
	return xxx_messageInfo_DBCommSetReq.Size(m)
}
func (m *DBCommSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommSetReq proto.InternalMessageInfo

func (m *DBCommSetReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommSetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DBCommSetReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DBCommSetReq) GetIgnoreRsp() bool {
	if m != nil {
		return m.IgnoreRsp
	}
	return false
}

func (m *DBCommSetReq) GetExpireSeconds() int32 {
	if m != nil {
		return m.ExpireSeconds
	}
	return 0
}

type DBCommSetRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	DbType               uint32   `protobuf:"varint,2,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommSetRsp) Reset()         { *m = DBCommSetRsp{} }
func (m *DBCommSetRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommSetRsp) ProtoMessage()    {}
func (*DBCommSetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{12}
}

func (m *DBCommSetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommSetRsp.Unmarshal(m, b)
}
func (m *DBCommSetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommSetRsp.Marshal(b, m, deterministic)
}
func (m *DBCommSetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommSetRsp.Merge(m, src)
}
func (m *DBCommSetRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommSetRsp.Size(m)
}
func (m *DBCommSetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommSetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommSetRsp proto.InternalMessageInfo

func (m *DBCommSetRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommSetRsp) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

// DB_COMM_DEL_REQ
type DBCommDelReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommDelReq) Reset()         { *m = DBCommDelReq{} }
func (m *DBCommDelReq) String() string { return proto.CompactTextString(m) }
func (*DBCommDelReq) ProtoMessage()    {}
func (*DBCommDelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{13}
}

func (m *DBCommDelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommDelReq.Unmarshal(m, b)
}
func (m *DBCommDelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommDelReq.Marshal(b, m, deterministic)
}
func (m *DBCommDelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommDelReq.Merge(m, src)
}
func (m *DBCommDelReq) XXX_Size() int {
	return xxx_messageInfo_DBCommDelReq.Size(m)
}
func (m *DBCommDelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommDelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommDelReq proto.InternalMessageInfo

func (m *DBCommDelReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommDelReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DBCommDelRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommDelRsp) Reset()         { *m = DBCommDelRsp{} }
func (m *DBCommDelRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommDelRsp) ProtoMessage()    {}
func (*DBCommDelRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{14}
}

func (m *DBCommDelRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommDelRsp.Unmarshal(m, b)
}
func (m *DBCommDelRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommDelRsp.Marshal(b, m, deterministic)
}
func (m *DBCommDelRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommDelRsp.Merge(m, src)
}
func (m *DBCommDelRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommDelRsp.Size(m)
}
func (m *DBCommDelRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommDelRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommDelRsp proto.InternalMessageInfo

func (m *DBCommDelRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// DB_COMM_INCR_REQ
type DBCommIncrReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommIncrReq) Reset()         { *m = DBCommIncrReq{} }
func (m *DBCommIncrReq) String() string { return proto.CompactTextString(m) }
func (*DBCommIncrReq) ProtoMessage()    {}
func (*DBCommIncrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{15}
}

func (m *DBCommIncrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommIncrReq.Unmarshal(m, b)
}
func (m *DBCommIncrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommIncrReq.Marshal(b, m, deterministic)
}
func (m *DBCommIncrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommIncrReq.Merge(m, src)
}
func (m *DBCommIncrReq) XXX_Size() int {
	return xxx_messageInfo_DBCommIncrReq.Size(m)
}
func (m *DBCommIncrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommIncrReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommIncrReq proto.InternalMessageInfo

func (m *DBCommIncrReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommIncrReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DBCommIncrRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommIncrRsp) Reset()         { *m = DBCommIncrRsp{} }
func (m *DBCommIncrRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommIncrRsp) ProtoMessage()    {}
func (*DBCommIncrRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{16}
}

func (m *DBCommIncrRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommIncrRsp.Unmarshal(m, b)
}
func (m *DBCommIncrRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommIncrRsp.Marshal(b, m, deterministic)
}
func (m *DBCommIncrRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommIncrRsp.Merge(m, src)
}
func (m *DBCommIncrRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommIncrRsp.Size(m)
}
func (m *DBCommIncrRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommIncrRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommIncrRsp proto.InternalMessageInfo

func (m *DBCommIncrRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommIncrRsp) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// DB_COMM_ZSET_SET_REQ
type DBCommZsetSetReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	SetName              string   `protobuf:"bytes,2,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	MaxKeyCnt            int32    `protobuf:"varint,3,opt,name=max_key_cnt,json=maxKeyCnt,proto3" json:"max_key_cnt,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Score                int32    `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZsetSetReq) Reset()         { *m = DBCommZsetSetReq{} }
func (m *DBCommZsetSetReq) String() string { return proto.CompactTextString(m) }
func (*DBCommZsetSetReq) ProtoMessage()    {}
func (*DBCommZsetSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{17}
}

func (m *DBCommZsetSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZsetSetReq.Unmarshal(m, b)
}
func (m *DBCommZsetSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZsetSetReq.Marshal(b, m, deterministic)
}
func (m *DBCommZsetSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZsetSetReq.Merge(m, src)
}
func (m *DBCommZsetSetReq) XXX_Size() int {
	return xxx_messageInfo_DBCommZsetSetReq.Size(m)
}
func (m *DBCommZsetSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZsetSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZsetSetReq proto.InternalMessageInfo

func (m *DBCommZsetSetReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommZsetSetReq) GetSetName() string {
	if m != nil {
		return m.SetName
	}
	return ""
}

func (m *DBCommZsetSetReq) GetMaxKeyCnt() int32 {
	if m != nil {
		return m.MaxKeyCnt
	}
	return 0
}

func (m *DBCommZsetSetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DBCommZsetSetReq) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type DBCommZsetSetRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZsetSetRsp) Reset()         { *m = DBCommZsetSetRsp{} }
func (m *DBCommZsetSetRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommZsetSetRsp) ProtoMessage()    {}
func (*DBCommZsetSetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{18}
}

func (m *DBCommZsetSetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZsetSetRsp.Unmarshal(m, b)
}
func (m *DBCommZsetSetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZsetSetRsp.Marshal(b, m, deterministic)
}
func (m *DBCommZsetSetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZsetSetRsp.Merge(m, src)
}
func (m *DBCommZsetSetRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommZsetSetRsp.Size(m)
}
func (m *DBCommZsetSetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZsetSetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZsetSetRsp proto.InternalMessageInfo

func (m *DBCommZsetSetRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// DB_COMM_ZSET_GET_REQ
type DBCommZsetGetReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	SetName              string   `protobuf:"bytes,2,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	BeginRank            int32    `protobuf:"varint,3,opt,name=begin_rank,json=beginRank,proto3" json:"begin_rank,omitempty"`
	EndRank              int32    `protobuf:"varint,4,opt,name=end_rank,json=endRank,proto3" json:"end_rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZsetGetReq) Reset()         { *m = DBCommZsetGetReq{} }
func (m *DBCommZsetGetReq) String() string { return proto.CompactTextString(m) }
func (*DBCommZsetGetReq) ProtoMessage()    {}
func (*DBCommZsetGetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{19}
}

func (m *DBCommZsetGetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZsetGetReq.Unmarshal(m, b)
}
func (m *DBCommZsetGetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZsetGetReq.Marshal(b, m, deterministic)
}
func (m *DBCommZsetGetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZsetGetReq.Merge(m, src)
}
func (m *DBCommZsetGetReq) XXX_Size() int {
	return xxx_messageInfo_DBCommZsetGetReq.Size(m)
}
func (m *DBCommZsetGetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZsetGetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZsetGetReq proto.InternalMessageInfo

func (m *DBCommZsetGetReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommZsetGetReq) GetSetName() string {
	if m != nil {
		return m.SetName
	}
	return ""
}

func (m *DBCommZsetGetReq) GetBeginRank() int32 {
	if m != nil {
		return m.BeginRank
	}
	return 0
}

func (m *DBCommZsetGetReq) GetEndRank() int32 {
	if m != nil {
		return m.EndRank
	}
	return 0
}

type DBCommZsetGetRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	BeginRank            uint32   `protobuf:"varint,2,opt,name=begin_rank,json=beginRank,proto3" json:"begin_rank,omitempty"`
	EndRank              uint32   `protobuf:"varint,3,opt,name=end_rank,json=endRank,proto3" json:"end_rank,omitempty"`
	RankList             []string `protobuf:"bytes,4,rep,name=rank_list,json=rankList,proto3" json:"rank_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZsetGetRsp) Reset()         { *m = DBCommZsetGetRsp{} }
func (m *DBCommZsetGetRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommZsetGetRsp) ProtoMessage()    {}
func (*DBCommZsetGetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{20}
}

func (m *DBCommZsetGetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZsetGetRsp.Unmarshal(m, b)
}
func (m *DBCommZsetGetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZsetGetRsp.Marshal(b, m, deterministic)
}
func (m *DBCommZsetGetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZsetGetRsp.Merge(m, src)
}
func (m *DBCommZsetGetRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommZsetGetRsp.Size(m)
}
func (m *DBCommZsetGetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZsetGetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZsetGetRsp proto.InternalMessageInfo

func (m *DBCommZsetGetRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommZsetGetRsp) GetBeginRank() uint32 {
	if m != nil {
		return m.BeginRank
	}
	return 0
}

func (m *DBCommZsetGetRsp) GetEndRank() uint32 {
	if m != nil {
		return m.EndRank
	}
	return 0
}

func (m *DBCommZsetGetRsp) GetRankList() []string {
	if m != nil {
		return m.RankList
	}
	return nil
}

// DB_COMM_ZSET_FIND_RANK_REQ
type DBCommZsetFindRankReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	SetName              string   `protobuf:"bytes,2,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZsetFindRankReq) Reset()         { *m = DBCommZsetFindRankReq{} }
func (m *DBCommZsetFindRankReq) String() string { return proto.CompactTextString(m) }
func (*DBCommZsetFindRankReq) ProtoMessage()    {}
func (*DBCommZsetFindRankReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{21}
}

func (m *DBCommZsetFindRankReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZsetFindRankReq.Unmarshal(m, b)
}
func (m *DBCommZsetFindRankReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZsetFindRankReq.Marshal(b, m, deterministic)
}
func (m *DBCommZsetFindRankReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZsetFindRankReq.Merge(m, src)
}
func (m *DBCommZsetFindRankReq) XXX_Size() int {
	return xxx_messageInfo_DBCommZsetFindRankReq.Size(m)
}
func (m *DBCommZsetFindRankReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZsetFindRankReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZsetFindRankReq proto.InternalMessageInfo

func (m *DBCommZsetFindRankReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommZsetFindRankReq) GetSetName() string {
	if m != nil {
		return m.SetName
	}
	return ""
}

func (m *DBCommZsetFindRankReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DBCommZsetFindRankRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Rank                 int32    `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZsetFindRankRsp) Reset()         { *m = DBCommZsetFindRankRsp{} }
func (m *DBCommZsetFindRankRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommZsetFindRankRsp) ProtoMessage()    {}
func (*DBCommZsetFindRankRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{22}
}

func (m *DBCommZsetFindRankRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZsetFindRankRsp.Unmarshal(m, b)
}
func (m *DBCommZsetFindRankRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZsetFindRankRsp.Marshal(b, m, deterministic)
}
func (m *DBCommZsetFindRankRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZsetFindRankRsp.Merge(m, src)
}
func (m *DBCommZsetFindRankRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommZsetFindRankRsp.Size(m)
}
func (m *DBCommZsetFindRankRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZsetFindRankRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZsetFindRankRsp proto.InternalMessageInfo

func (m *DBCommZsetFindRankRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommZsetFindRankRsp) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

// DB_COMM_ZSET_INCR_REQ
type DBCommZsetIncrReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	SetName              string   `protobuf:"bytes,2,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	Member               string   `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	AddedScore           float64  `protobuf:"fixed64,4,opt,name=added_score,json=addedScore,proto3" json:"added_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZsetIncrReq) Reset()         { *m = DBCommZsetIncrReq{} }
func (m *DBCommZsetIncrReq) String() string { return proto.CompactTextString(m) }
func (*DBCommZsetIncrReq) ProtoMessage()    {}
func (*DBCommZsetIncrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{23}
}

func (m *DBCommZsetIncrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZsetIncrReq.Unmarshal(m, b)
}
func (m *DBCommZsetIncrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZsetIncrReq.Marshal(b, m, deterministic)
}
func (m *DBCommZsetIncrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZsetIncrReq.Merge(m, src)
}
func (m *DBCommZsetIncrReq) XXX_Size() int {
	return xxx_messageInfo_DBCommZsetIncrReq.Size(m)
}
func (m *DBCommZsetIncrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZsetIncrReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZsetIncrReq proto.InternalMessageInfo

func (m *DBCommZsetIncrReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommZsetIncrReq) GetSetName() string {
	if m != nil {
		return m.SetName
	}
	return ""
}

func (m *DBCommZsetIncrReq) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

func (m *DBCommZsetIncrReq) GetAddedScore() float64 {
	if m != nil {
		return m.AddedScore
	}
	return 0
}

type DBCommZsetIncrRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ScoreAfter           float64  `protobuf:"fixed64,2,opt,name=score_after,json=scoreAfter,proto3" json:"score_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZsetIncrRsp) Reset()         { *m = DBCommZsetIncrRsp{} }
func (m *DBCommZsetIncrRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommZsetIncrRsp) ProtoMessage()    {}
func (*DBCommZsetIncrRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{24}
}

func (m *DBCommZsetIncrRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZsetIncrRsp.Unmarshal(m, b)
}
func (m *DBCommZsetIncrRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZsetIncrRsp.Marshal(b, m, deterministic)
}
func (m *DBCommZsetIncrRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZsetIncrRsp.Merge(m, src)
}
func (m *DBCommZsetIncrRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommZsetIncrRsp.Size(m)
}
func (m *DBCommZsetIncrRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZsetIncrRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZsetIncrRsp proto.InternalMessageInfo

func (m *DBCommZsetIncrRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommZsetIncrRsp) GetScoreAfter() float64 {
	if m != nil {
		return m.ScoreAfter
	}
	return 0
}

// DB_COMM_ZSCORE_REQ
type DBCommZScoreReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	SetName              string   `protobuf:"bytes,2,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	Member               string   `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZScoreReq) Reset()         { *m = DBCommZScoreReq{} }
func (m *DBCommZScoreReq) String() string { return proto.CompactTextString(m) }
func (*DBCommZScoreReq) ProtoMessage()    {}
func (*DBCommZScoreReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{25}
}

func (m *DBCommZScoreReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZScoreReq.Unmarshal(m, b)
}
func (m *DBCommZScoreReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZScoreReq.Marshal(b, m, deterministic)
}
func (m *DBCommZScoreReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZScoreReq.Merge(m, src)
}
func (m *DBCommZScoreReq) XXX_Size() int {
	return xxx_messageInfo_DBCommZScoreReq.Size(m)
}
func (m *DBCommZScoreReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZScoreReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZScoreReq proto.InternalMessageInfo

func (m *DBCommZScoreReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommZScoreReq) GetSetName() string {
	if m != nil {
		return m.SetName
	}
	return ""
}

func (m *DBCommZScoreReq) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

type DBCommZScoreRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Score                float64  `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZScoreRsp) Reset()         { *m = DBCommZScoreRsp{} }
func (m *DBCommZScoreRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommZScoreRsp) ProtoMessage()    {}
func (*DBCommZScoreRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{26}
}

func (m *DBCommZScoreRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZScoreRsp.Unmarshal(m, b)
}
func (m *DBCommZScoreRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZScoreRsp.Marshal(b, m, deterministic)
}
func (m *DBCommZScoreRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZScoreRsp.Merge(m, src)
}
func (m *DBCommZScoreRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommZScoreRsp.Size(m)
}
func (m *DBCommZScoreRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZScoreRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZScoreRsp proto.InternalMessageInfo

func (m *DBCommZScoreRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommZScoreRsp) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

// DB_COMM_ZREVRANGE_REQ
type DBCommZRevRangeReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Start                int32    `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	Stop                 int32    `protobuf:"varint,4,opt,name=stop,proto3" json:"stop,omitempty"`
	WithScores           bool     `protobuf:"varint,5,opt,name=with_scores,json=withScores,proto3" json:"with_scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommZRevRangeReq) Reset()         { *m = DBCommZRevRangeReq{} }
func (m *DBCommZRevRangeReq) String() string { return proto.CompactTextString(m) }
func (*DBCommZRevRangeReq) ProtoMessage()    {}
func (*DBCommZRevRangeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{27}
}

func (m *DBCommZRevRangeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZRevRangeReq.Unmarshal(m, b)
}
func (m *DBCommZRevRangeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZRevRangeReq.Marshal(b, m, deterministic)
}
func (m *DBCommZRevRangeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZRevRangeReq.Merge(m, src)
}
func (m *DBCommZRevRangeReq) XXX_Size() int {
	return xxx_messageInfo_DBCommZRevRangeReq.Size(m)
}
func (m *DBCommZRevRangeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZRevRangeReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZRevRangeReq proto.InternalMessageInfo

func (m *DBCommZRevRangeReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommZRevRangeReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DBCommZRevRangeReq) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *DBCommZRevRangeReq) GetStop() int32 {
	if m != nil {
		return m.Stop
	}
	return 0
}

func (m *DBCommZRevRangeReq) GetWithScores() bool {
	if m != nil {
		return m.WithScores
	}
	return false
}

type DBRedisZItem struct {
	Member               string   `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Score                int32    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Rank                 int32    `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBRedisZItem) Reset()         { *m = DBRedisZItem{} }
func (m *DBRedisZItem) String() string { return proto.CompactTextString(m) }
func (*DBRedisZItem) ProtoMessage()    {}
func (*DBRedisZItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{28}
}

func (m *DBRedisZItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRedisZItem.Unmarshal(m, b)
}
func (m *DBRedisZItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRedisZItem.Marshal(b, m, deterministic)
}
func (m *DBRedisZItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRedisZItem.Merge(m, src)
}
func (m *DBRedisZItem) XXX_Size() int {
	return xxx_messageInfo_DBRedisZItem.Size(m)
}
func (m *DBRedisZItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRedisZItem.DiscardUnknown(m)
}

var xxx_messageInfo_DBRedisZItem proto.InternalMessageInfo

func (m *DBRedisZItem) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

func (m *DBRedisZItem) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *DBRedisZItem) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type DBCommZRevRangeRsp struct {
	Ret                  *Ret            `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Items                []*DBRedisZItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DBCommZRevRangeRsp) Reset()         { *m = DBCommZRevRangeRsp{} }
func (m *DBCommZRevRangeRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommZRevRangeRsp) ProtoMessage()    {}
func (*DBCommZRevRangeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{29}
}

func (m *DBCommZRevRangeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommZRevRangeRsp.Unmarshal(m, b)
}
func (m *DBCommZRevRangeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommZRevRangeRsp.Marshal(b, m, deterministic)
}
func (m *DBCommZRevRangeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommZRevRangeRsp.Merge(m, src)
}
func (m *DBCommZRevRangeRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommZRevRangeRsp.Size(m)
}
func (m *DBCommZRevRangeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommZRevRangeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommZRevRangeRsp proto.InternalMessageInfo

func (m *DBCommZRevRangeRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *DBCommZRevRangeRsp) GetItems() []*DBRedisZItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// DB_COMM_EXPIRE_REQ
type DBCommExpireReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Seconds              int32    `protobuf:"varint,3,opt,name=seconds,proto3" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommExpireReq) Reset()         { *m = DBCommExpireReq{} }
func (m *DBCommExpireReq) String() string { return proto.CompactTextString(m) }
func (*DBCommExpireReq) ProtoMessage()    {}
func (*DBCommExpireReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{30}
}

func (m *DBCommExpireReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommExpireReq.Unmarshal(m, b)
}
func (m *DBCommExpireReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommExpireReq.Marshal(b, m, deterministic)
}
func (m *DBCommExpireReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommExpireReq.Merge(m, src)
}
func (m *DBCommExpireReq) XXX_Size() int {
	return xxx_messageInfo_DBCommExpireReq.Size(m)
}
func (m *DBCommExpireReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommExpireReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommExpireReq proto.InternalMessageInfo

func (m *DBCommExpireReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommExpireReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DBCommExpireReq) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type DBCommExpireRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommExpireRsp) Reset()         { *m = DBCommExpireRsp{} }
func (m *DBCommExpireRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommExpireRsp) ProtoMessage()    {}
func (*DBCommExpireRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{31}
}

func (m *DBCommExpireRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommExpireRsp.Unmarshal(m, b)
}
func (m *DBCommExpireRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommExpireRsp.Marshal(b, m, deterministic)
}
func (m *DBCommExpireRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommExpireRsp.Merge(m, src)
}
func (m *DBCommExpireRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommExpireRsp.Size(m)
}
func (m *DBCommExpireRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommExpireRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommExpireRsp proto.InternalMessageInfo

func (m *DBCommExpireRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// DB_COMM_SETEXNX_REQ
type DBCommSetExNxReq struct {
	DbType               uint32   `protobuf:"varint,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Seconds              int32    `protobuf:"varint,4,opt,name=seconds,proto3" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommSetExNxReq) Reset()         { *m = DBCommSetExNxReq{} }
func (m *DBCommSetExNxReq) String() string { return proto.CompactTextString(m) }
func (*DBCommSetExNxReq) ProtoMessage()    {}
func (*DBCommSetExNxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{32}
}

func (m *DBCommSetExNxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommSetExNxReq.Unmarshal(m, b)
}
func (m *DBCommSetExNxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommSetExNxReq.Marshal(b, m, deterministic)
}
func (m *DBCommSetExNxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommSetExNxReq.Merge(m, src)
}
func (m *DBCommSetExNxReq) XXX_Size() int {
	return xxx_messageInfo_DBCommSetExNxReq.Size(m)
}
func (m *DBCommSetExNxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommSetExNxReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommSetExNxReq proto.InternalMessageInfo

func (m *DBCommSetExNxReq) GetDbType() uint32 {
	if m != nil {
		return m.DbType
	}
	return 0
}

func (m *DBCommSetExNxReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DBCommSetExNxReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DBCommSetExNxReq) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type DBCommSetExNxRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBCommSetExNxRsp) Reset()         { *m = DBCommSetExNxRsp{} }
func (m *DBCommSetExNxRsp) String() string { return proto.CompactTextString(m) }
func (*DBCommSetExNxRsp) ProtoMessage()    {}
func (*DBCommSetExNxRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef0e59ea4b09dc2, []int{33}
}

func (m *DBCommSetExNxRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBCommSetExNxRsp.Unmarshal(m, b)
}
func (m *DBCommSetExNxRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBCommSetExNxRsp.Marshal(b, m, deterministic)
}
func (m *DBCommSetExNxRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBCommSetExNxRsp.Merge(m, src)
}
func (m *DBCommSetExNxRsp) XXX_Size() int {
	return xxx_messageInfo_DBCommSetExNxRsp.Size(m)
}
func (m *DBCommSetExNxRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBCommSetExNxRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DBCommSetExNxRsp proto.InternalMessageInfo

func (m *DBCommSetExNxRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func init() {
	proto.RegisterEnum("g1.protocol.DBType_EDBType", DBType_EDBType_name, DBType_EDBType_value)
	proto.RegisterType((*DBType)(nil), "g1.protocol.DBType")
	proto.RegisterType((*DBUidGetReq)(nil), "g1.protocol.DBUidGetReq")
	proto.RegisterType((*DBUidGetRsp)(nil), "g1.protocol.DBUidGetRsp")
	proto.RegisterType((*DBUidMGetReq)(nil), "g1.protocol.DBUidMGetReq")
	proto.RegisterType((*DBUidMGetRsp)(nil), "g1.protocol.DBUidMGetRsp")
	proto.RegisterType((*DBUidSetReq)(nil), "g1.protocol.DBUidSetReq")
	proto.RegisterType((*DBUidSetRsp)(nil), "g1.protocol.DBUidSetRsp")
	proto.RegisterType((*DBCommGetReq)(nil), "g1.protocol.DBCommGetReq")
	proto.RegisterType((*DBCommGetRsp)(nil), "g1.protocol.DBCommGetRsp")
	proto.RegisterType((*DBCommMGetReq)(nil), "g1.protocol.DBCommMGetReq")
	proto.RegisterType((*DBCommMGetRsp)(nil), "g1.protocol.DBCommMGetRsp")
	proto.RegisterType((*DBCommSetReq)(nil), "g1.protocol.DBCommSetReq")
	proto.RegisterType((*DBCommSetRsp)(nil), "g1.protocol.DBCommSetRsp")
	proto.RegisterType((*DBCommDelReq)(nil), "g1.protocol.DBCommDelReq")
	proto.RegisterType((*DBCommDelRsp)(nil), "g1.protocol.DBCommDelRsp")
	proto.RegisterType((*DBCommIncrReq)(nil), "g1.protocol.DBCommIncrReq")
	proto.RegisterType((*DBCommIncrRsp)(nil), "g1.protocol.DBCommIncrRsp")
	proto.RegisterType((*DBCommZsetSetReq)(nil), "g1.protocol.DBCommZsetSetReq")
	proto.RegisterType((*DBCommZsetSetRsp)(nil), "g1.protocol.DBCommZsetSetRsp")
	proto.RegisterType((*DBCommZsetGetReq)(nil), "g1.protocol.DBCommZsetGetReq")
	proto.RegisterType((*DBCommZsetGetRsp)(nil), "g1.protocol.DBCommZsetGetRsp")
	proto.RegisterType((*DBCommZsetFindRankReq)(nil), "g1.protocol.DBCommZsetFindRankReq")
	proto.RegisterType((*DBCommZsetFindRankRsp)(nil), "g1.protocol.DBCommZsetFindRankRsp")
	proto.RegisterType((*DBCommZsetIncrReq)(nil), "g1.protocol.DBCommZsetIncrReq")
	proto.RegisterType((*DBCommZsetIncrRsp)(nil), "g1.protocol.DBCommZsetIncrRsp")
	proto.RegisterType((*DBCommZScoreReq)(nil), "g1.protocol.DBCommZScoreReq")
	proto.RegisterType((*DBCommZScoreRsp)(nil), "g1.protocol.DBCommZScoreRsp")
	proto.RegisterType((*DBCommZRevRangeReq)(nil), "g1.protocol.DBCommZRevRangeReq")
	proto.RegisterType((*DBRedisZItem)(nil), "g1.protocol.DBRedisZItem")
	proto.RegisterType((*DBCommZRevRangeRsp)(nil), "g1.protocol.DBCommZRevRangeRsp")
	proto.RegisterType((*DBCommExpireReq)(nil), "g1.protocol.DBCommExpireReq")
	proto.RegisterType((*DBCommExpireRsp)(nil), "g1.protocol.DBCommExpireRsp")
	proto.RegisterType((*DBCommSetExNxReq)(nil), "g1.protocol.DBCommSetExNxReq")
	proto.RegisterType((*DBCommSetExNxRsp)(nil), "g1.protocol.DBCommSetExNxRsp")
}

func init() {
	proto.RegisterFile("dbsvr.proto", fileDescriptor_bef0e59ea4b09dc2)
}

var fileDescriptor_bef0e59ea4b09dc2 = []byte{
	// 931 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0xc5, 0xb5, 0xf3, 0x75, 0x93, 0x2e, 0xde, 0x61, 0x59, 0xb2, 0xa0, 0x65, 0xa3, 0x91, 0x90,
	0xf2, 0x54, 0x44, 0x11, 0x2b, 0xe0, 0x2d, 0x1f, 0x4e, 0x31, 0xed, 0x26, 0xd5, 0xa4, 0x45, 0x50,
	0xa9, 0xb2, 0x9c, 0xf8, 0x52, 0xac, 0xd4, 0x76, 0xb0, 0xa7, 0x25, 0x79, 0xe3, 0x19, 0x09, 0x5e,
	0xf8, 0x4d, 0xbc, 0xf3, 0x93, 0xd0, 0xcc, 0xd8, 0x8d, 0xdd, 0x02, 0x75, 0xba, 0x7d, 0x9b, 0x39,
	0x93, 0x7b, 0xe7, 0x9c, 0x7b, 0xee, 0x5c, 0x07, 0x9a, 0xde, 0x2c, 0xb9, 0x8e, 0xf7, 0x96, 0x71,
	0xc4, 0x23, 0xd2, 0xbc, 0xf8, 0x4c, 0xad, 0xe6, 0xd1, 0xe5, 0x87, 0xad, 0x79, 0x14, 0x04, 0x51,
	0xa8, 0x00, 0xfa, 0xb7, 0x06, 0xd5, 0x61, 0xff, 0x64, 0xbd, 0x44, 0xfa, 0x97, 0x06, 0x35, 0x4b,
	0xad, 0x49, 0x0b, 0xea, 0xce, 0xb0, 0xef, 0x9c, 0x59, 0x6c, 0x62, 0xbe, 0x43, 0x4c, 0x68, 0x0d,
	0xfb, 0xce, 0xc9, 0x0f, 0xc7, 0x96, 0xc3, 0x26, 0x47, 0x96, 0xa9, 0x91, 0xf7, 0xe0, 0xdd, 0x0c,
	0xe9, 0x0d, 0x06, 0x93, 0xd3, 0xf1, 0x89, 0xb9, 0x43, 0x9e, 0x03, 0xc9, 0xc0, 0x3e, 0xb3, 0xad,
	0x91, 0x63, 0x8f, 0x47, 0x13, 0x53, 0x2f, 0x84, 0xf7, 0xc6, 0x87, 0xa6, 0x41, 0x9e, 0xc2, 0x6e,
	0x86, 0x1c, 0x9c, 0xda, 0x47, 0x43, 0xb3, 0x92, 0xff, 0xd1, 0x9b, 0x9e, 0x7d, 0x64, 0x56, 0xf3,
	0xc8, 0xe0, 0x9b, 0xde, 0x89, 0x59, 0x23, 0x04, 0x9e, 0x64, 0xc8, 0x88, 0xd9, 0xd6, 0x78, 0x68,
	0xd6, 0x0b, 0x71, 0xf6, 0x74, 0x60, 0xce, 0xe9, 0x97, 0xd0, 0x1c, 0xf6, 0x4f, 0x7d, 0xef, 0x00,
	0x39, 0xc3, 0x9f, 0xc9, 0x07, 0x50, 0xf3, 0x66, 0x0e, 0x5f, 0x2f, 0xb1, 0xad, 0x75, 0xb4, 0xee,
	0x2e, 0xab, 0x7a, 0x33, 0xa9, 0xd1, 0x04, 0xfd, 0xca, 0xf7, 0xda, 0x3b, 0x1d, 0xad, 0x6b, 0x30,
	0xb1, 0xa4, 0x56, 0x2e, 0x32, 0x59, 0x12, 0x0a, 0x7a, 0x8c, 0x5c, 0x46, 0x35, 0xf7, 0xcd, 0xbd,
	0x5c, 0x11, 0xf7, 0x18, 0x72, 0x26, 0x0e, 0x09, 0x01, 0xc3, 0x73, 0xb9, 0x2b, 0xb3, 0xb4, 0x98,
	0x5c, 0xd3, 0xbe, 0xa0, 0x74, 0xea, 0x7b, 0x6f, 0xee, 0x63, 0xf0, 0x02, 0xea, 0x57, 0xbe, 0xe7,
	0x5c, 0xfa, 0x09, 0x6f, 0xef, 0x74, 0xf4, 0xae, 0xc1, 0x6a, 0x57, 0xbe, 0x77, 0xe4, 0x27, 0x9c,
	0x4e, 0xf2, 0x39, 0x4a, 0x72, 0xf9, 0x08, 0x1a, 0xe2, 0xfe, 0x4d, 0xbe, 0x16, 0xab, 0x0b, 0x40,
	0x26, 0x5c, 0xa4, 0xda, 0xa6, 0xdb, 0x56, 0xe5, 0x46, 0xa2, 0xbe, 0x91, 0x48, 0x5e, 0x02, 0xf8,
	0x17, 0x61, 0x14, 0xa3, 0x13, 0x27, 0xcb, 0xb6, 0xd1, 0xd1, 0xba, 0x75, 0xd6, 0x50, 0x08, 0x4b,
	0x96, 0xf4, 0xdb, 0xdc, 0x65, 0x25, 0xc9, 0xe7, 0x08, 0xed, 0xe4, 0x09, 0xd1, 0xaf, 0x44, 0x25,
	0x06, 0x51, 0x10, 0x94, 0xf0, 0x73, 0x81, 0x6b, 0x19, 0xdd, 0x60, 0x62, 0x49, 0x47, 0xf9, 0xd0,
	0xb7, 0x30, 0x74, 0x20, 0xda, 0x55, 0xe4, 0x29, 0xe3, 0xe8, 0x02, 0xd7, 0x1b, 0x07, 0x1a, 0xac,
	0xb6, 0xc0, 0xb5, 0x34, 0xe0, 0xb8, 0x90, 0xe4, 0x31, 0x2c, 0xfd, 0x53, 0xcb, 0xf4, 0x4d, 0xb7,
	0x2d, 0xcd, 0x03, 0x4c, 0x25, 0x9f, 0xc0, 0x13, 0x5c, 0x2d, 0xfd, 0x18, 0x9d, 0x04, 0xe7, 0x51,
	0xe8, 0x25, 0xed, 0x4a, 0x47, 0xeb, 0x56, 0xd8, 0xae, 0x42, 0xa7, 0x0a, 0xa4, 0x87, 0x79, 0x52,
	0x8f, 0x66, 0xfe, 0x10, 0x2f, 0xb7, 0x34, 0x7f, 0x3f, 0x1f, 0x5a, 0x8e, 0x07, 0xfd, 0x3a, 0xf3,
	0xc8, 0x0e, 0xe7, 0xf1, 0x96, 0xf7, 0xd9, 0x85, 0xd8, 0x92, 0xc2, 0x9f, 0x41, 0xe5, 0xda, 0xbd,
	0xbc, 0x52, 0xb2, 0x75, 0xa6, 0x36, 0xf4, 0x0f, 0x0d, 0x4c, 0x95, 0xeb, 0x2c, 0x41, 0x3e, 0xbd,
	0xbf, 0xe7, 0x12, 0xe4, 0x4e, 0xe8, 0x06, 0x98, 0xf2, 0xa9, 0x25, 0xc8, 0xc7, 0x6e, 0x80, 0xe4,
	0x63, 0x68, 0x06, 0xee, 0xca, 0x11, 0x2d, 0x39, 0x0f, 0xb9, 0x34, 0xbb, 0xc2, 0x1a, 0x81, 0xbb,
	0x3a, 0xc4, 0xf5, 0x20, 0xe4, 0x99, 0x0a, 0x63, 0xd3, 0x17, 0xcf, 0xa0, 0x92, 0xcc, 0xa3, 0x18,
	0x53, 0x6f, 0xd5, 0x86, 0xbe, 0xbe, 0xcd, 0xa7, 0x64, 0x3d, 0x7f, 0x2d, 0x08, 0x39, 0x78, 0xb8,
	0x90, 0x97, 0x00, 0x33, 0xbc, 0xf0, 0x43, 0x27, 0x76, 0xc3, 0x45, 0xa6, 0x43, 0x22, 0xcc, 0x0d,
	0x17, 0x22, 0x12, 0x43, 0x4f, 0x1d, 0x1a, 0xf2, 0xb0, 0x86, 0xa1, 0x27, 0x8e, 0xe8, 0xef, 0x77,
	0x28, 0x94, 0xb4, 0xa6, 0x78, 0xa5, 0x6a, 0xcb, 0xff, 0xb8, 0x52, 0x97, 0x87, 0xd9, 0x95, 0xe2,
	0xd1, 0x0a, 0x58, 0x3d, 0x5a, 0x43, 0x4e, 0x81, 0xba, 0x00, 0xe4, 0xa3, 0x3d, 0x87, 0xf7, 0x37,
	0x74, 0x46, 0xbe, 0x0a, 0x79, 0x68, 0x59, 0x52, 0xff, 0xf4, 0x4d, 0x17, 0x4e, 0xfe, 0x35, 0x7d,
	0xf9, 0xd9, 0x77, 0x23, 0xb6, 0xc2, 0xe4, 0x5a, 0x58, 0xf8, 0x74, 0x93, 0xf1, 0xde, 0x77, 0xf1,
	0x3f, 0x64, 0x9f, 0x43, 0x35, 0xc0, 0x60, 0x86, 0x71, 0xca, 0x37, 0xdd, 0x91, 0x57, 0xd0, 0x74,
	0x3d, 0x0f, 0x3d, 0x47, 0x35, 0x9e, 0xf0, 0x4f, 0x63, 0x20, 0xa1, 0xa9, 0xec, 0xbe, 0xef, 0xef,
	0x30, 0x28, 0xa9, 0xe7, 0x15, 0x34, 0x65, 0x4e, 0xc7, 0xfd, 0x91, 0x63, 0x2c, 0xf9, 0x68, 0x0c,
	0x24, 0xd4, 0x13, 0x08, 0x3d, 0x17, 0x7f, 0x63, 0x64, 0x66, 0x79, 0xd3, 0x23, 0x2b, 0xa3, 0x87,
	0xb7, 0xd2, 0x97, 0x1f, 0x0a, 0xaa, 0x14, 0x8a, 0x70, 0xfa, 0x06, 0x7f, 0xd3, 0xc4, 0xdf, 0x2b,
	0x99, 0x8d, 0xe1, 0x35, 0x73, 0xc3, 0x0b, 0xdc, 0x72, 0xe6, 0x8b, 0xbc, 0xdc, 0x8d, 0xb3, 0x39,
	0xa0, 0x36, 0xc2, 0xf4, 0x84, 0x47, 0xcb, 0xf4, 0xdd, 0xc8, 0xb5, 0x28, 0xdc, 0x2f, 0x3e, 0xff,
	0x49, 0x39, 0xa2, 0xe6, 0x7c, 0x9d, 0x81, 0x80, 0xa4, 0x90, 0x84, 0x1e, 0x8b, 0xe1, 0xca, 0xd0,
	0xf3, 0x93, 0x33, 0x9b, 0x63, 0x90, 0xab, 0x80, 0x56, 0xf0, 0xb6, 0x20, 0x25, 0x1b, 0x27, 0x37,
	0x7d, 0xa6, 0xe7, 0xfa, 0xcc, 0xbf, 0xab, 0xae, 0x64, 0xb9, 0x3e, 0x85, 0x8a, 0xcf, 0x31, 0x48,
	0xe4, 0xf7, 0xb1, 0xb9, 0xff, 0xa2, 0xf0, 0xab, 0x3c, 0x4b, 0xa6, 0x7e, 0x47, 0xbf, 0xcb, 0x6c,
	0xb1, 0xe4, 0x87, 0x6b, 0xcb, 0x2a, 0xb6, 0xa1, 0x96, 0x7d, 0xff, 0x14, 0xff, 0x6c, 0x4b, 0xbf,
	0xb8, 0x95, 0xb7, 0xe4, 0x90, 0x0c, 0xb2, 0x01, 0x35, 0x45, 0x6e, 0xad, 0xc6, 0xab, 0xed, 0x5d,
	0x55, 0x9f, 0x10, 0xd5, 0x7b, 0x6a, 0x93, 0x67, 0x69, 0x14, 0x59, 0xbe, 0xbe, 0x7d, 0x5d, 0x39,
	0x9a, 0xb3, 0xaa, 0x84, 0x3e, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0x67, 0xe4, 0x2f, 0xac, 0x5a,
	0x0c, 0x00, 0x00,
}
