// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gm.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MAIN_GM_GET_ROLE_REQ
type GMGetRoleReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GMGetRoleReq) Reset()         { *m = GMGetRoleReq{} }
func (m *GMGetRoleReq) String() string { return proto.CompactTextString(m) }
func (*GMGetRoleReq) ProtoMessage()    {}
func (*GMGetRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e843c9cc9a3a239, []int{0}
}

func (m *GMGetRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GMGetRoleReq.Unmarshal(m, b)
}
func (m *GMGetRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GMGetRoleReq.Marshal(b, m, deterministic)
}
func (m *GMGetRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GMGetRoleReq.Merge(m, src)
}
func (m *GMGetRoleReq) XXX_Size() int {
	return xxx_messageInfo_GMGetRoleReq.Size(m)
}
func (m *GMGetRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GMGetRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_GMGetRoleReq proto.InternalMessageInfo

type GMGetRoleRsp struct {
	Ret                  *Ret      `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	RoleInfo             *RoleInfo `protobuf:"bytes,2,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GMGetRoleRsp) Reset()         { *m = GMGetRoleRsp{} }
func (m *GMGetRoleRsp) String() string { return proto.CompactTextString(m) }
func (*GMGetRoleRsp) ProtoMessage()    {}
func (*GMGetRoleRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e843c9cc9a3a239, []int{1}
}

func (m *GMGetRoleRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GMGetRoleRsp.Unmarshal(m, b)
}
func (m *GMGetRoleRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GMGetRoleRsp.Marshal(b, m, deterministic)
}
func (m *GMGetRoleRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GMGetRoleRsp.Merge(m, src)
}
func (m *GMGetRoleRsp) XXX_Size() int {
	return xxx_messageInfo_GMGetRoleRsp.Size(m)
}
func (m *GMGetRoleRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GMGetRoleRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GMGetRoleRsp proto.InternalMessageInfo

func (m *GMGetRoleRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *GMGetRoleRsp) GetRoleInfo() *RoleInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

// MAIN_GM_SET_ROLE_REQ
type GMSetRoleReq struct {
	RoleInfo             *RoleInfo `protobuf:"bytes,1,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GMSetRoleReq) Reset()         { *m = GMSetRoleReq{} }
func (m *GMSetRoleReq) String() string { return proto.CompactTextString(m) }
func (*GMSetRoleReq) ProtoMessage()    {}
func (*GMSetRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e843c9cc9a3a239, []int{2}
}

func (m *GMSetRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GMSetRoleReq.Unmarshal(m, b)
}
func (m *GMSetRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GMSetRoleReq.Marshal(b, m, deterministic)
}
func (m *GMSetRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GMSetRoleReq.Merge(m, src)
}
func (m *GMSetRoleReq) XXX_Size() int {
	return xxx_messageInfo_GMSetRoleReq.Size(m)
}
func (m *GMSetRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GMSetRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_GMSetRoleReq proto.InternalMessageInfo

func (m *GMSetRoleReq) GetRoleInfo() *RoleInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

type GMSetRoleRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GMSetRoleRsp) Reset()         { *m = GMSetRoleRsp{} }
func (m *GMSetRoleRsp) String() string { return proto.CompactTextString(m) }
func (*GMSetRoleRsp) ProtoMessage()    {}
func (*GMSetRoleRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e843c9cc9a3a239, []int{3}
}

func (m *GMSetRoleRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GMSetRoleRsp.Unmarshal(m, b)
}
func (m *GMSetRoleRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GMSetRoleRsp.Marshal(b, m, deterministic)
}
func (m *GMSetRoleRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GMSetRoleRsp.Merge(m, src)
}
func (m *GMSetRoleRsp) XXX_Size() int {
	return xxx_messageInfo_GMSetRoleRsp.Size(m)
}
func (m *GMSetRoleRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GMSetRoleRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GMSetRoleRsp proto.InternalMessageInfo

func (m *GMSetRoleRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// MAIN_GM_ADD_ITEM_REQ
type GMAddItemReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GMAddItemReq) Reset()         { *m = GMAddItemReq{} }
func (m *GMAddItemReq) String() string { return proto.CompactTextString(m) }
func (*GMAddItemReq) ProtoMessage()    {}
func (*GMAddItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e843c9cc9a3a239, []int{4}
}

func (m *GMAddItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GMAddItemReq.Unmarshal(m, b)
}
func (m *GMAddItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GMAddItemReq.Marshal(b, m, deterministic)
}
func (m *GMAddItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GMAddItemReq.Merge(m, src)
}
func (m *GMAddItemReq) XXX_Size() int {
	return xxx_messageInfo_GMAddItemReq.Size(m)
}
func (m *GMAddItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GMAddItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_GMAddItemReq proto.InternalMessageInfo

func (m *GMAddItemReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GMAddItemReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GMAddItemRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GMAddItemRsp) Reset()         { *m = GMAddItemRsp{} }
func (m *GMAddItemRsp) String() string { return proto.CompactTextString(m) }
func (*GMAddItemRsp) ProtoMessage()    {}
func (*GMAddItemRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e843c9cc9a3a239, []int{5}
}

func (m *GMAddItemRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GMAddItemRsp.Unmarshal(m, b)
}
func (m *GMAddItemRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GMAddItemRsp.Marshal(b, m, deterministic)
}
func (m *GMAddItemRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GMAddItemRsp.Merge(m, src)
}
func (m *GMAddItemRsp) XXX_Size() int {
	return xxx_messageInfo_GMAddItemRsp.Size(m)
}
func (m *GMAddItemRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GMAddItemRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GMAddItemRsp proto.InternalMessageInfo

func (m *GMAddItemRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func init() {
	proto.RegisterType((*GMGetRoleReq)(nil), "g1.protocol.GMGetRoleReq")
	proto.RegisterType((*GMGetRoleRsp)(nil), "g1.protocol.GMGetRoleRsp")
	proto.RegisterType((*GMSetRoleReq)(nil), "g1.protocol.GMSetRoleReq")
	proto.RegisterType((*GMSetRoleRsp)(nil), "g1.protocol.GMSetRoleRsp")
	proto.RegisterType((*GMAddItemReq)(nil), "g1.protocol.GMAddItemReq")
	proto.RegisterType((*GMAddItemRsp)(nil), "g1.protocol.GMAddItemRsp")
}

func init() {
	proto.RegisterFile("gm.proto", fileDescriptor_9e843c9cc9a3a239)
}

var fileDescriptor_9e843c9cc9a3a239 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0xcf, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x37, 0x84, 0xb0, 0x92, 0xf3, 0x73, 0xa4, 0xb8, 0x8a,
	0xf2, 0x73, 0x52, 0x21, 0x5c, 0x29, 0x9e, 0xe4, 0xfc, 0xdc, 0xdc, 0xfc, 0x3c, 0x08, 0x4f, 0x89,
	0x8f, 0x8b, 0xc7, 0xdd, 0xd7, 0x3d, 0xb5, 0x24, 0x28, 0x3f, 0x27, 0x35, 0x28, 0xb5, 0x50, 0x29,
	0x0d, 0x99, 0x5f, 0x5c, 0x20, 0xa4, 0xc4, 0xc5, 0x5c, 0x94, 0x5a, 0x22, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x6d, 0x24, 0xa0, 0x87, 0x64, 0xa8, 0x5e, 0x50, 0x6a, 0x49, 0x10, 0x48, 0x52, 0xc8, 0x88,
	0x8b, 0x13, 0x64, 0x7e, 0x7c, 0x66, 0x5e, 0x5a, 0xbe, 0x04, 0x13, 0x58, 0xa5, 0x28, 0xaa, 0xca,
	0xfc, 0x9c, 0x54, 0xcf, 0xbc, 0xb4, 0xfc, 0x20, 0x8e, 0x22, 0x28, 0x4b, 0xc9, 0x09, 0x64, 0x4f,
	0x30, 0xdc, 0x5e, 0x54, 0x33, 0x18, 0x89, 0x33, 0xc3, 0x08, 0xd9, 0x0c, 0xe2, 0xdc, 0xaa, 0x64,
	0x02, 0xd2, 0xe3, 0x98, 0x92, 0xe2, 0x59, 0x92, 0x9a, 0x0b, 0xb2, 0x97, 0x8f, 0x8b, 0x29, 0x33,
	0x05, 0xac, 0x85, 0x35, 0x88, 0x29, 0x33, 0x45, 0x48, 0x84, 0x8b, 0x35, 0x39, 0xbf, 0x34, 0xaf,
	0x04, 0xec, 0x0f, 0xd6, 0x20, 0x08, 0x07, 0x62, 0x13, 0x4c, 0x17, 0x71, 0x36, 0x25, 0xb1, 0x81,
	0x85, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xa4, 0x5d, 0x54, 0x93, 0x01, 0x00, 0x00,
}
