// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infosvr.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PbRoleBriefInfo struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 int32    `protobuf:"varint,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Frame                int32    `protobuf:"varint,4,opt,name=frame,proto3" json:"frame,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	VipLevel             int32    `protobuf:"varint,6,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`
	Exp                  int32    `protobuf:"varint,7,opt,name=exp,proto3" json:"exp,omitempty"`
	Image                int32    `protobuf:"varint,8,opt,name=image,proto3" json:"image,omitempty"`
	RegisterTime         int32    `protobuf:"varint,9,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	TotalStar            int32    `protobuf:"varint,11,opt,name=total_star,json=totalStar,proto3" json:"total_star,omitempty"`
	CardCnt              int32    `protobuf:"varint,12,opt,name=card_cnt,json=cardCnt,proto3" json:"card_cnt,omitempty"`
	Fp                   int32    `protobuf:"varint,13,opt,name=fp,proto3" json:"fp,omitempty"`
	OpvpLevel            int32    `protobuf:"varint,14,opt,name=opvp_level,json=opvpLevel,proto3" json:"opvp_level,omitempty"`
	OpvpRank             int32    `protobuf:"varint,15,opt,name=opvp_rank,json=opvpRank,proto3" json:"opvp_rank,omitempty"`
	LastOnlineTime       int32    `protobuf:"varint,16,opt,name=last_online_time,json=lastOnlineTime,proto3" json:"last_online_time,omitempty"`
	ConnBusId            uint32   `protobuf:"varint,100,opt,name=conn_bus_id,json=connBusId,proto3" json:"conn_bus_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbRoleBriefInfo) Reset()         { *m = PbRoleBriefInfo{} }
func (m *PbRoleBriefInfo) String() string { return proto.CompactTextString(m) }
func (*PbRoleBriefInfo) ProtoMessage()    {}
func (*PbRoleBriefInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9800ea8119df1933, []int{0}
}

func (m *PbRoleBriefInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbRoleBriefInfo.Unmarshal(m, b)
}
func (m *PbRoleBriefInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbRoleBriefInfo.Marshal(b, m, deterministic)
}
func (m *PbRoleBriefInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbRoleBriefInfo.Merge(m, src)
}
func (m *PbRoleBriefInfo) XXX_Size() int {
	return xxx_messageInfo_PbRoleBriefInfo.Size(m)
}
func (m *PbRoleBriefInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PbRoleBriefInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PbRoleBriefInfo proto.InternalMessageInfo

func (m *PbRoleBriefInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PbRoleBriefInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PbRoleBriefInfo) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *PbRoleBriefInfo) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *PbRoleBriefInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *PbRoleBriefInfo) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *PbRoleBriefInfo) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *PbRoleBriefInfo) GetImage() int32 {
	if m != nil {
		return m.Image
	}
	return 0
}

func (m *PbRoleBriefInfo) GetRegisterTime() int32 {
	if m != nil {
		return m.RegisterTime
	}
	return 0
}

func (m *PbRoleBriefInfo) GetTotalStar() int32 {
	if m != nil {
		return m.TotalStar
	}
	return 0
}

func (m *PbRoleBriefInfo) GetCardCnt() int32 {
	if m != nil {
		return m.CardCnt
	}
	return 0
}

func (m *PbRoleBriefInfo) GetFp() int32 {
	if m != nil {
		return m.Fp
	}
	return 0
}

func (m *PbRoleBriefInfo) GetOpvpLevel() int32 {
	if m != nil {
		return m.OpvpLevel
	}
	return 0
}

func (m *PbRoleBriefInfo) GetOpvpRank() int32 {
	if m != nil {
		return m.OpvpRank
	}
	return 0
}

func (m *PbRoleBriefInfo) GetLastOnlineTime() int32 {
	if m != nil {
		return m.LastOnlineTime
	}
	return 0
}

func (m *PbRoleBriefInfo) GetConnBusId() uint32 {
	if m != nil {
		return m.ConnBusId
	}
	return 0
}

// INFO_SET_BRIEF_INFO_REQ
type InfoSetBriefInfoReq struct {
	Uid                  uint64           `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Info                 *PbRoleBriefInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	IgnoreRsp            bool             `protobuf:"varint,3,opt,name=ignore_rsp,json=ignoreRsp,proto3" json:"ignore_rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *InfoSetBriefInfoReq) Reset()         { *m = InfoSetBriefInfoReq{} }
func (m *InfoSetBriefInfoReq) String() string { return proto.CompactTextString(m) }
func (*InfoSetBriefInfoReq) ProtoMessage()    {}
func (*InfoSetBriefInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9800ea8119df1933, []int{1}
}

func (m *InfoSetBriefInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoSetBriefInfoReq.Unmarshal(m, b)
}
func (m *InfoSetBriefInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoSetBriefInfoReq.Marshal(b, m, deterministic)
}
func (m *InfoSetBriefInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoSetBriefInfoReq.Merge(m, src)
}
func (m *InfoSetBriefInfoReq) XXX_Size() int {
	return xxx_messageInfo_InfoSetBriefInfoReq.Size(m)
}
func (m *InfoSetBriefInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoSetBriefInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoSetBriefInfoReq proto.InternalMessageInfo

func (m *InfoSetBriefInfoReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InfoSetBriefInfoReq) GetInfo() *PbRoleBriefInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *InfoSetBriefInfoReq) GetIgnoreRsp() bool {
	if m != nil {
		return m.IgnoreRsp
	}
	return false
}

type InfoSetBriefInfoRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoSetBriefInfoRsp) Reset()         { *m = InfoSetBriefInfoRsp{} }
func (m *InfoSetBriefInfoRsp) String() string { return proto.CompactTextString(m) }
func (*InfoSetBriefInfoRsp) ProtoMessage()    {}
func (*InfoSetBriefInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9800ea8119df1933, []int{2}
}

func (m *InfoSetBriefInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoSetBriefInfoRsp.Unmarshal(m, b)
}
func (m *InfoSetBriefInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoSetBriefInfoRsp.Marshal(b, m, deterministic)
}
func (m *InfoSetBriefInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoSetBriefInfoRsp.Merge(m, src)
}
func (m *InfoSetBriefInfoRsp) XXX_Size() int {
	return xxx_messageInfo_InfoSetBriefInfoRsp.Size(m)
}
func (m *InfoSetBriefInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoSetBriefInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_InfoSetBriefInfoRsp proto.InternalMessageInfo

func (m *InfoSetBriefInfoRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func init() {
	proto.RegisterType((*PbRoleBriefInfo)(nil), "g1.protocol.PbRoleBriefInfo")
	proto.RegisterType((*InfoSetBriefInfoReq)(nil), "g1.protocol.InfoSetBriefInfoReq")
	proto.RegisterType((*InfoSetBriefInfoRsp)(nil), "g1.protocol.InfoSetBriefInfoRsp")
}

func init() {
	proto.RegisterFile("infosvr.proto", fileDescriptor_9800ea8119df1933)
}

var fileDescriptor_9800ea8119df1933 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0x71, 0x9c, 0xec, 0xc6, 0xe3, 0x24, 0x6b, 0xd4, 0x1e, 0xd4, 0xbf, 0x84, 0xf4, 0xe2,
	0x53, 0x68, 0xb7, 0xa7, 0x5e, 0xb7, 0xa7, 0x85, 0x85, 0x16, 0x6d, 0xef, 0x46, 0xb1, 0xc7, 0x41,
	0xac, 0x2d, 0xa9, 0x92, 0x62, 0xf6, 0x6b, 0xf5, 0x1b, 0x16, 0x8d, 0x48, 0x69, 0x4b, 0x6e, 0x6f,
	0x7e, 0x6f, 0x18, 0xcd, 0xf0, 0x04, 0x6b, 0xa5, 0x7b, 0xe3, 0x27, 0xb7, 0xb7, 0xce, 0x04, 0xc3,
	0xca, 0xe3, 0xa7, 0xa4, 0x5a, 0x33, 0xbc, 0x5e, 0xb5, 0x66, 0x1c, 0x8d, 0x4e, 0x60, 0xf7, 0x2b,
	0x87, 0x9b, 0xef, 0x07, 0x61, 0x06, 0xbc, 0x73, 0x0a, 0xfb, 0x7b, 0xdd, 0x1b, 0x56, 0x41, 0x7e,
	0x52, 0x1d, 0xcf, 0xb6, 0x59, 0x3d, 0x17, 0x51, 0x32, 0x06, 0x73, 0x2d, 0x47, 0xe4, 0xb3, 0x6d,
	0x56, 0x17, 0x82, 0x74, 0x64, 0xaa, 0x35, 0x9a, 0xe7, 0xdb, 0xac, 0x5e, 0x08, 0xd2, 0xec, 0x25,
	0x2c, 0x7a, 0x17, 0x1b, 0xe7, 0x04, 0x53, 0x11, 0xe9, 0x80, 0x13, 0x0e, 0x7c, 0x91, 0x28, 0x15,
	0xec, 0x0d, 0x14, 0x93, 0xb2, 0x4d, 0x72, 0xae, 0xc8, 0x59, 0x4e, 0xca, 0x3e, 0x90, 0x59, 0x41,
	0x8e, 0xcf, 0x96, 0x5f, 0x13, 0x8e, 0x32, 0x0e, 0x51, 0xa3, 0x3c, 0x22, 0x5f, 0xa6, 0x21, 0x54,
	0xb0, 0x0f, 0xb0, 0x76, 0x78, 0x54, 0x3e, 0xa0, 0x6b, 0x82, 0x1a, 0x91, 0x17, 0xe4, 0xae, 0xce,
	0xf0, 0x87, 0x1a, 0x91, 0xbd, 0x03, 0x08, 0x26, 0xc8, 0xa1, 0xf1, 0x41, 0x3a, 0x5e, 0x52, 0x47,
	0x41, 0xe4, 0x31, 0x48, 0xc7, 0x5e, 0xc1, 0xb2, 0x95, 0xae, 0x6b, 0x5a, 0x1d, 0xf8, 0x8a, 0xcc,
	0xeb, 0x58, 0x7f, 0xd5, 0x81, 0x6d, 0x60, 0xd6, 0x5b, 0xbe, 0x26, 0x38, 0xeb, 0x6d, 0x9c, 0x64,
	0xec, 0x74, 0x5e, 0x7a, 0x93, 0x26, 0x45, 0xf2, 0x70, 0x3e, 0x89, 0x6c, 0x27, 0xf5, 0x13, 0xbf,
	0x49, 0x27, 0x45, 0x20, 0xa4, 0x7e, 0x62, 0x35, 0x54, 0x83, 0xf4, 0xa1, 0x31, 0x7a, 0x50, 0x1a,
	0xd3, 0xb6, 0x15, 0xf5, 0x6c, 0x22, 0xff, 0x46, 0x98, 0xf6, 0x7d, 0x0f, 0x65, 0x6b, 0xb4, 0x6e,
	0x0e, 0x27, 0xdf, 0xa8, 0x8e, 0x77, 0xdb, 0xac, 0x5e, 0x8b, 0x22, 0xa2, 0xbb, 0x93, 0xbf, 0xef,
	0x76, 0xcf, 0xf0, 0x22, 0xe6, 0xf4, 0x88, 0xe1, 0x4f, 0x66, 0x02, 0x7f, 0x5e, 0x88, 0xed, 0x23,
	0xcc, 0xe3, 0x47, 0xa0, 0xd8, 0xca, 0xdb, 0xb7, 0xfb, 0xbf, 0xbe, 0xc1, 0xfe, 0xbf, 0xd0, 0x05,
	0x75, 0xc6, 0x03, 0xd5, 0x51, 0x1b, 0x87, 0x8d, 0xf3, 0x96, 0xa2, 0x5d, 0x8a, 0x22, 0x11, 0xe1,
	0xed, 0xee, 0xcb, 0x85, 0x97, 0xbd, 0x65, 0x3b, 0xc8, 0x1d, 0x06, 0x7a, 0xb9, 0xbc, 0xad, 0xfe,
	0x79, 0x46, 0x60, 0x10, 0xd1, 0x3c, 0x5c, 0x11, 0xfa, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x8f,
	0xf9, 0x8a, 0x73, 0x9b, 0x02, 0x00, 0x00,
}
