// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mailsvr.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PbMail struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32     `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ConfId               int32     `protobuf:"varint,3,opt,name=conf_id,json=confId,proto3" json:"conf_id,omitempty"`
	CreateTime           int32     `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	AttachList           []*PbItem `protobuf:"bytes,5,rep,name=attach_list,json=attachList,proto3" json:"attach_list,omitempty"`
	Sender               uint64    `protobuf:"varint,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Read                 bool      `protobuf:"varint,10,opt,name=read,proto3" json:"read,omitempty"`
	AttachGet            bool      `protobuf:"varint,11,opt,name=attach_get,json=attachGet,proto3" json:"attach_get,omitempty"`
	Title                string    `protobuf:"bytes,20,opt,name=title,proto3" json:"title,omitempty"`
	Content              string    `protobuf:"bytes,21,opt,name=content,proto3" json:"content,omitempty"`
	ContentArgv          []string  `protobuf:"bytes,22,rep,name=content_argv,json=contentArgv,proto3" json:"content_argv,omitempty"`
	RemoveStartTime      int32     `protobuf:"varint,50,opt,name=remove_start_time,json=removeStartTime,proto3" json:"remove_start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PbMail) Reset()         { *m = PbMail{} }
func (m *PbMail) String() string { return proto.CompactTextString(m) }
func (*PbMail) ProtoMessage()    {}
func (*PbMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd2ebf93486e449, []int{0}
}

func (m *PbMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbMail.Unmarshal(m, b)
}
func (m *PbMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbMail.Marshal(b, m, deterministic)
}
func (m *PbMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbMail.Merge(m, src)
}
func (m *PbMail) XXX_Size() int {
	return xxx_messageInfo_PbMail.Size(m)
}
func (m *PbMail) XXX_DiscardUnknown() {
	xxx_messageInfo_PbMail.DiscardUnknown(m)
}

var xxx_messageInfo_PbMail proto.InternalMessageInfo

func (m *PbMail) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PbMail) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PbMail) GetConfId() int32 {
	if m != nil {
		return m.ConfId
	}
	return 0
}

func (m *PbMail) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *PbMail) GetAttachList() []*PbItem {
	if m != nil {
		return m.AttachList
	}
	return nil
}

func (m *PbMail) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *PbMail) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *PbMail) GetAttachGet() bool {
	if m != nil {
		return m.AttachGet
	}
	return false
}

func (m *PbMail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PbMail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PbMail) GetContentArgv() []string {
	if m != nil {
		return m.ContentArgv
	}
	return nil
}

func (m *PbMail) GetRemoveStartTime() int32 {
	if m != nil {
		return m.RemoveStartTime
	}
	return 0
}

type MailInfo struct {
	Uid                  uint64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MailList             []*PbMail `protobuf:"bytes,2,rep,name=mail_list,json=mailList,proto3" json:"mail_list,omitempty"`
	CurMailId            int32     `protobuf:"varint,3,opt,name=cur_mail_id,json=curMailId,proto3" json:"cur_mail_id,omitempty"`
	AddMailList          []int32   `protobuf:"varint,4,rep,packed,name=add_mail_list,json=addMailList,proto3" json:"add_mail_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MailInfo) Reset()         { *m = MailInfo{} }
func (m *MailInfo) String() string { return proto.CompactTextString(m) }
func (*MailInfo) ProtoMessage()    {}
func (*MailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd2ebf93486e449, []int{1}
}

func (m *MailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailInfo.Unmarshal(m, b)
}
func (m *MailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailInfo.Marshal(b, m, deterministic)
}
func (m *MailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailInfo.Merge(m, src)
}
func (m *MailInfo) XXX_Size() int {
	return xxx_messageInfo_MailInfo.Size(m)
}
func (m *MailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MailInfo proto.InternalMessageInfo

func (m *MailInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MailInfo) GetMailList() []*PbMail {
	if m != nil {
		return m.MailList
	}
	return nil
}

func (m *MailInfo) GetCurMailId() int32 {
	if m != nil {
		return m.CurMailId
	}
	return 0
}

func (m *MailInfo) GetAddMailList() []int32 {
	if m != nil {
		return m.AddMailList
	}
	return nil
}

// MAIL_INNER_ADD_MAIL_REQ
type MailInnerAddMailReq struct {
	MailList             []*PbMail `protobuf:"bytes,1,rep,name=mail_list,json=mailList,proto3" json:"mail_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MailInnerAddMailReq) Reset()         { *m = MailInnerAddMailReq{} }
func (m *MailInnerAddMailReq) String() string { return proto.CompactTextString(m) }
func (*MailInnerAddMailReq) ProtoMessage()    {}
func (*MailInnerAddMailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd2ebf93486e449, []int{2}
}

func (m *MailInnerAddMailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailInnerAddMailReq.Unmarshal(m, b)
}
func (m *MailInnerAddMailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailInnerAddMailReq.Marshal(b, m, deterministic)
}
func (m *MailInnerAddMailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailInnerAddMailReq.Merge(m, src)
}
func (m *MailInnerAddMailReq) XXX_Size() int {
	return xxx_messageInfo_MailInnerAddMailReq.Size(m)
}
func (m *MailInnerAddMailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MailInnerAddMailReq.DiscardUnknown(m)
}

var xxx_messageInfo_MailInnerAddMailReq proto.InternalMessageInfo

func (m *MailInnerAddMailReq) GetMailList() []*PbMail {
	if m != nil {
		return m.MailList
	}
	return nil
}

type MailInnerAddMailRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailInnerAddMailRsp) Reset()         { *m = MailInnerAddMailRsp{} }
func (m *MailInnerAddMailRsp) String() string { return proto.CompactTextString(m) }
func (*MailInnerAddMailRsp) ProtoMessage()    {}
func (*MailInnerAddMailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccd2ebf93486e449, []int{3}
}

func (m *MailInnerAddMailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailInnerAddMailRsp.Unmarshal(m, b)
}
func (m *MailInnerAddMailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailInnerAddMailRsp.Marshal(b, m, deterministic)
}
func (m *MailInnerAddMailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailInnerAddMailRsp.Merge(m, src)
}
func (m *MailInnerAddMailRsp) XXX_Size() int {
	return xxx_messageInfo_MailInnerAddMailRsp.Size(m)
}
func (m *MailInnerAddMailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MailInnerAddMailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MailInnerAddMailRsp proto.InternalMessageInfo

func (m *MailInnerAddMailRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func init() {
	proto.RegisterType((*PbMail)(nil), "g1.protocol.PbMail")
	proto.RegisterType((*MailInfo)(nil), "g1.protocol.MailInfo")
	proto.RegisterType((*MailInnerAddMailReq)(nil), "g1.protocol.MailInnerAddMailReq")
	proto.RegisterType((*MailInnerAddMailRsp)(nil), "g1.protocol.MailInnerAddMailRsp")
}

func init() {
	proto.RegisterFile("mailsvr.proto", fileDescriptor_ccd2ebf93486e449)
}

var fileDescriptor_ccd2ebf93486e449 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x95, 0x3f, 0x1b, 0x9a, 0x71, 0x0b, 0xc5, 0x2d, 0xc5, 0xaa, 0x04, 0x84, 0x9c, 0x22,
	0x0e, 0x2b, 0x58, 0xb8, 0x70, 0xec, 0xa9, 0x5a, 0x89, 0x4a, 0x95, 0xe1, 0x1e, 0x79, 0xe3, 0xe9,
	0x62, 0x29, 0x89, 0x17, 0x67, 0x76, 0x25, 0x5e, 0x83, 0x87, 0xe4, 0x39, 0x90, 0xed, 0xf0, 0xa7,
	0x52, 0x0f, 0xdc, 0xbe, 0xf9, 0x4d, 0x66, 0x32, 0xdf, 0x67, 0x38, 0x19, 0x94, 0xe9, 0xa7, 0x83,
	0x5b, 0xee, 0x9c, 0x25, 0xcb, 0xd9, 0xf6, 0x5d, 0x54, 0x9d, 0xed, 0x2f, 0x8f, 0x3b, 0x3b, 0x0c,
	0x76, 0x8c, 0xe0, 0x12, 0x9c, 0xed, 0x31, 0xea, 0xfa, 0x67, 0x0a, 0xc5, 0xed, 0xe6, 0x46, 0x99,
	0x9e, 0x3f, 0x86, 0xd4, 0x68, 0x91, 0x54, 0x49, 0xb3, 0x90, 0xa9, 0xd1, 0x9c, 0x43, 0x4e, 0xdf,
	0x77, 0x28, 0xd2, 0x40, 0x82, 0xe6, 0xcf, 0xe1, 0x51, 0x67, 0xc7, 0xbb, 0xd6, 0x68, 0x91, 0x05,
	0x5c, 0xf8, 0x72, 0xad, 0xf9, 0x2b, 0x60, 0x9d, 0x43, 0x45, 0xd8, 0x92, 0x19, 0x50, 0xe4, 0xa1,
	0x09, 0x11, 0x7d, 0x31, 0x03, 0xf2, 0x0f, 0xc0, 0x14, 0x91, 0xea, 0xbe, 0xb6, 0xbd, 0x99, 0x48,
	0x2c, 0xaa, 0xac, 0x61, 0xab, 0xb3, 0xe5, 0x3f, 0x57, 0x2e, 0x6f, 0x37, 0x6b, 0xc2, 0x41, 0x42,
	0xfc, 0xee, 0x93, 0x99, 0x88, 0x5f, 0x40, 0x31, 0xe1, 0xa8, 0xd1, 0x89, 0xa2, 0x4a, 0x9a, 0x5c,
	0xce, 0x95, 0xbf, 0xcd, 0xa1, 0xd2, 0x02, 0xaa, 0xa4, 0x39, 0x92, 0x41, 0xf3, 0x17, 0x30, 0x4f,
	0xb6, 0x5b, 0x24, 0xc1, 0x42, 0xa7, 0x8c, 0xe4, 0x1a, 0x89, 0x9f, 0xc3, 0x82, 0x0c, 0xf5, 0x28,
	0xce, 0xab, 0xa4, 0x29, 0x65, 0x2c, 0xb8, 0x08, 0x86, 0x08, 0x47, 0x12, 0xcf, 0x02, 0xff, 0x5d,
	0xf2, 0xd7, 0x70, 0x3c, 0xcb, 0x56, 0xb9, 0xed, 0x41, 0x5c, 0x54, 0x59, 0x53, 0x4a, 0x36, 0xb3,
	0x2b, 0xb7, 0x3d, 0xf0, 0x37, 0xf0, 0xd4, 0xe1, 0x60, 0x0f, 0xd8, 0x4e, 0xa4, 0x1c, 0x45, 0xeb,
	0xab, 0x60, 0xfd, 0x49, 0x6c, 0x7c, 0xf6, 0xdc, 0xfb, 0xaf, 0x7f, 0x24, 0x70, 0xe4, 0x63, 0x5e,
	0x8f, 0x77, 0x96, 0x9f, 0x42, 0xb6, 0x9f, 0xb3, 0xce, 0xa5, 0x97, 0xfc, 0x2d, 0x94, 0xfe, 0xfd,
	0x62, 0x38, 0xe9, 0x83, 0xe1, 0xf8, 0x69, 0x79, 0xe4, 0xbf, 0x0a, 0xd1, 0xbc, 0x04, 0xd6, 0xed,
	0x5d, 0x1b, 0xa6, 0xfe, 0x3c, 0x47, 0xd9, 0xed, 0x5d, 0xf8, 0x8b, 0xe6, 0x35, 0x9c, 0x28, 0xad,
	0xdb, 0xbf, 0x5b, 0xf3, 0x2a, 0x6b, 0x16, 0x92, 0x29, 0xad, 0x6f, 0xe6, 0x1d, 0xf5, 0x35, 0x9c,
	0xc5, 0x9b, 0x46, 0x74, 0x57, 0x91, 0x4b, 0xfc, 0x76, 0xff, 0x98, 0xe4, 0x3f, 0x8e, 0xa9, 0x3f,
	0x3e, 0xb0, 0x68, 0xda, 0xf1, 0x1a, 0x32, 0x87, 0x14, 0x7c, 0xb2, 0xd5, 0xe9, 0xbd, 0x15, 0x12,
	0x49, 0xfa, 0xe6, 0xa6, 0x08, 0xe8, 0xfd, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0xb7, 0x55,
	0x54, 0xc0, 0x02, 0x00, 0x00,
}
