// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mainsvr.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MAIN_INNER_ADD_ITEM_REQ
type MainInnerAddItemReq struct {
	ItemList             []*PbItem `protobuf:"bytes,1,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MainInnerAddItemReq) Reset()         { *m = MainInnerAddItemReq{} }
func (m *MainInnerAddItemReq) String() string { return proto.CompactTextString(m) }
func (*MainInnerAddItemReq) ProtoMessage()    {}
func (*MainInnerAddItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ec037bf804c92f, []int{0}
}

func (m *MainInnerAddItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainInnerAddItemReq.Unmarshal(m, b)
}
func (m *MainInnerAddItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainInnerAddItemReq.Marshal(b, m, deterministic)
}
func (m *MainInnerAddItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainInnerAddItemReq.Merge(m, src)
}
func (m *MainInnerAddItemReq) XXX_Size() int {
	return xxx_messageInfo_MainInnerAddItemReq.Size(m)
}
func (m *MainInnerAddItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MainInnerAddItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_MainInnerAddItemReq proto.InternalMessageInfo

func (m *MainInnerAddItemReq) GetItemList() []*PbItem {
	if m != nil {
		return m.ItemList
	}
	return nil
}

type MainInnerAddItemRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MainInnerAddItemRsp) Reset()         { *m = MainInnerAddItemRsp{} }
func (m *MainInnerAddItemRsp) String() string { return proto.CompactTextString(m) }
func (*MainInnerAddItemRsp) ProtoMessage()    {}
func (*MainInnerAddItemRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ec037bf804c92f, []int{1}
}

func (m *MainInnerAddItemRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainInnerAddItemRsp.Unmarshal(m, b)
}
func (m *MainInnerAddItemRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainInnerAddItemRsp.Marshal(b, m, deterministic)
}
func (m *MainInnerAddItemRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainInnerAddItemRsp.Merge(m, src)
}
func (m *MainInnerAddItemRsp) XXX_Size() int {
	return xxx_messageInfo_MainInnerAddItemRsp.Size(m)
}
func (m *MainInnerAddItemRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MainInnerAddItemRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MainInnerAddItemRsp proto.InternalMessageInfo

func (m *MainInnerAddItemRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// CONN_KICK_OUT_REQ
type ConnKickOutReq struct {
	Reason               EKickOutReason `protobuf:"varint,1,opt,name=reason,proto3,enum=g1.protocol.EKickOutReason" json:"reason,omitempty"`
	RemoteAddr           string         `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConnKickOutReq) Reset()         { *m = ConnKickOutReq{} }
func (m *ConnKickOutReq) String() string { return proto.CompactTextString(m) }
func (*ConnKickOutReq) ProtoMessage()    {}
func (*ConnKickOutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ec037bf804c92f, []int{2}
}

func (m *ConnKickOutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnKickOutReq.Unmarshal(m, b)
}
func (m *ConnKickOutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnKickOutReq.Marshal(b, m, deterministic)
}
func (m *ConnKickOutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnKickOutReq.Merge(m, src)
}
func (m *ConnKickOutReq) XXX_Size() int {
	return xxx_messageInfo_ConnKickOutReq.Size(m)
}
func (m *ConnKickOutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnKickOutReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnKickOutReq proto.InternalMessageInfo

func (m *ConnKickOutReq) GetReason() EKickOutReason {
	if m != nil {
		return m.Reason
	}
	return EKickOutReason_UNKNOWN
}

func (m *ConnKickOutReq) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

type ConnKickOutRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnKickOutRsp) Reset()         { *m = ConnKickOutRsp{} }
func (m *ConnKickOutRsp) String() string { return proto.CompactTextString(m) }
func (*ConnKickOutRsp) ProtoMessage()    {}
func (*ConnKickOutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ec037bf804c92f, []int{3}
}

func (m *ConnKickOutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnKickOutRsp.Unmarshal(m, b)
}
func (m *ConnKickOutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnKickOutRsp.Marshal(b, m, deterministic)
}
func (m *ConnKickOutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnKickOutRsp.Merge(m, src)
}
func (m *ConnKickOutRsp) XXX_Size() int {
	return xxx_messageInfo_ConnKickOutRsp.Size(m)
}
func (m *ConnKickOutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnKickOutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnKickOutRsp proto.InternalMessageInfo

// CONN_BROADCAST_REQ
type ConnBroadcastReq struct {
	Cmd                  uint32   `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnBroadcastReq) Reset()         { *m = ConnBroadcastReq{} }
func (m *ConnBroadcastReq) String() string { return proto.CompactTextString(m) }
func (*ConnBroadcastReq) ProtoMessage()    {}
func (*ConnBroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ec037bf804c92f, []int{4}
}

func (m *ConnBroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnBroadcastReq.Unmarshal(m, b)
}
func (m *ConnBroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnBroadcastReq.Marshal(b, m, deterministic)
}
func (m *ConnBroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnBroadcastReq.Merge(m, src)
}
func (m *ConnBroadcastReq) XXX_Size() int {
	return xxx_messageInfo_ConnBroadcastReq.Size(m)
}
func (m *ConnBroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnBroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnBroadcastReq proto.InternalMessageInfo

func (m *ConnBroadcastReq) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *ConnBroadcastReq) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ConnBroadcastRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnBroadcastRsp) Reset()         { *m = ConnBroadcastRsp{} }
func (m *ConnBroadcastRsp) String() string { return proto.CompactTextString(m) }
func (*ConnBroadcastRsp) ProtoMessage()    {}
func (*ConnBroadcastRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ec037bf804c92f, []int{5}
}

func (m *ConnBroadcastRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnBroadcastRsp.Unmarshal(m, b)
}
func (m *ConnBroadcastRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnBroadcastRsp.Marshal(b, m, deterministic)
}
func (m *ConnBroadcastRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnBroadcastRsp.Merge(m, src)
}
func (m *ConnBroadcastRsp) XXX_Size() int {
	return xxx_messageInfo_ConnBroadcastRsp.Size(m)
}
func (m *ConnBroadcastRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnBroadcastRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnBroadcastRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MainInnerAddItemReq)(nil), "g1.protocol.MainInnerAddItemReq")
	proto.RegisterType((*MainInnerAddItemRsp)(nil), "g1.protocol.MainInnerAddItemRsp")
	proto.RegisterType((*ConnKickOutReq)(nil), "g1.protocol.ConnKickOutReq")
	proto.RegisterType((*ConnKickOutRsp)(nil), "g1.protocol.ConnKickOutRsp")
	proto.RegisterType((*ConnBroadcastReq)(nil), "g1.protocol.ConnBroadcastReq")
	proto.RegisterType((*ConnBroadcastRsp)(nil), "g1.protocol.ConnBroadcastRsp")
}

func init() {
	proto.RegisterFile("mainsvr.proto", fileDescriptor_41ec037bf804c92f)
}

var fileDescriptor_41ec037bf804c92f = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xe9, 0xbf, 0x7f, 0x86, 0x7b, 0xbb, 0x8d, 0x92, 0x5d, 0xc6, 0x3c, 0x38, 0x72, 0xea,
	0xa9, 0x68, 0x77, 0xd1, 0xe3, 0x14, 0x91, 0xa1, 0xa2, 0xe4, 0x0b, 0x8c, 0x34, 0x89, 0x12, 0x6c,
	0xf2, 0xd6, 0x24, 0x0a, 0x7e, 0x7b, 0x49, 0x2a, 0x62, 0xc5, 0xdb, 0xc3, 0x9b, 0xdf, 0xf3, 0x7b,
	0x02, 0x73, 0xc3, 0xb5, 0xf5, 0xef, 0xae, 0xee, 0x1d, 0x06, 0x24, 0xc5, 0xf3, 0xd9, 0x90, 0x04,
	0x76, 0xeb, 0x99, 0x40, 0x63, 0xd0, 0x0e, 0x87, 0x35, 0x38, 0xec, 0xd4, 0x90, 0xe9, 0x0d, 0x2c,
	0xef, 0xb9, 0xb6, 0x7b, 0x6b, 0x95, 0xdb, 0x49, 0xb9, 0x0f, 0xca, 0x30, 0xf5, 0x4a, 0x4e, 0x61,
	0xaa, 0x83, 0x32, 0x87, 0x4e, 0xfb, 0xb0, 0xca, 0x36, 0x79, 0x55, 0x34, 0xcb, 0xfa, 0x87, 0xb1,
	0x7e, 0x6c, 0x13, 0x7a, 0x14, 0xa9, 0x3b, 0xed, 0x03, 0xbd, 0xf8, 0x43, 0xe4, 0x7b, 0x42, 0x21,
	0x77, 0x2a, 0x2a, 0xb2, 0xaa, 0x68, 0xca, 0x91, 0x82, 0xa9, 0xc0, 0xe2, 0x23, 0x7d, 0x82, 0xc5,
	0x15, 0x5a, 0x7b, 0xab, 0xc5, 0xcb, 0xc3, 0x5b, 0x88, 0xf3, 0x5b, 0x98, 0x38, 0xc5, 0x3d, 0xda,
	0x54, 0x5c, 0x34, 0xc7, 0xa3, 0xe2, 0xf5, 0x37, 0x19, 0x11, 0xf6, 0x85, 0x92, 0x13, 0x28, 0x9c,
	0x32, 0x18, 0xd4, 0x81, 0x4b, 0xe9, 0x56, 0xff, 0x36, 0x59, 0x35, 0x65, 0x30, 0x9c, 0x76, 0x52,
	0x3a, 0x5a, 0x8e, 0x77, 0x7c, 0x4f, 0xcf, 0xa1, 0x8c, 0x97, 0x4b, 0x87, 0x5c, 0x0a, 0xee, 0xd3,
	0x76, 0x09, 0xb9, 0x30, 0x32, 0x0d, 0xcf, 0x59, 0x8c, 0x84, 0xc0, 0xff, 0x16, 0xe5, 0x47, 0x32,
	0xce, 0x58, 0xca, 0x94, 0xfc, 0x6e, 0xfa, 0xbe, 0x9d, 0xa4, 0x1f, 0x6e, 0x3f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x3e, 0x2e, 0x06, 0x2e, 0x8a, 0x01, 0x00, 0x00,
}
