// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mysqlsvr.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EMysqlType int32

const (
	EMysqlType__MYSQL_TYPE_NONE     EMysqlType = 0
	EMysqlType_MYSQL_TYPE_ROLE_INFO EMysqlType = 1
)

var EMysqlType_name = map[int32]string{
	0: "_MYSQL_TYPE_NONE",
	1: "MYSQL_TYPE_ROLE_INFO",
}

var EMysqlType_value = map[string]int32{
	"_MYSQL_TYPE_NONE":     0,
	"MYSQL_TYPE_ROLE_INFO": 1,
}

func (x EMysqlType) String() string {
	return proto.EnumName(EMysqlType_name, int32(x))
}

func (EMysqlType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43471e5c926502ed, []int{0}
}

// MYSQL_INNER_UPDATE_ROLE_INFO_REQ
type MysqlInnerUpdateRoleInfoReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysqlInnerUpdateRoleInfoReq) Reset()         { *m = MysqlInnerUpdateRoleInfoReq{} }
func (m *MysqlInnerUpdateRoleInfoReq) String() string { return proto.CompactTextString(m) }
func (*MysqlInnerUpdateRoleInfoReq) ProtoMessage()    {}
func (*MysqlInnerUpdateRoleInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_43471e5c926502ed, []int{0}
}

func (m *MysqlInnerUpdateRoleInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysqlInnerUpdateRoleInfoReq.Unmarshal(m, b)
}
func (m *MysqlInnerUpdateRoleInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysqlInnerUpdateRoleInfoReq.Marshal(b, m, deterministic)
}
func (m *MysqlInnerUpdateRoleInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysqlInnerUpdateRoleInfoReq.Merge(m, src)
}
func (m *MysqlInnerUpdateRoleInfoReq) XXX_Size() int {
	return xxx_messageInfo_MysqlInnerUpdateRoleInfoReq.Size(m)
}
func (m *MysqlInnerUpdateRoleInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MysqlInnerUpdateRoleInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_MysqlInnerUpdateRoleInfoReq proto.InternalMessageInfo

func (m *MysqlInnerUpdateRoleInfoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MysqlInnerUpdateRoleInfoRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysqlInnerUpdateRoleInfoRsp) Reset()         { *m = MysqlInnerUpdateRoleInfoRsp{} }
func (m *MysqlInnerUpdateRoleInfoRsp) String() string { return proto.CompactTextString(m) }
func (*MysqlInnerUpdateRoleInfoRsp) ProtoMessage()    {}
func (*MysqlInnerUpdateRoleInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_43471e5c926502ed, []int{1}
}

func (m *MysqlInnerUpdateRoleInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysqlInnerUpdateRoleInfoRsp.Unmarshal(m, b)
}
func (m *MysqlInnerUpdateRoleInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysqlInnerUpdateRoleInfoRsp.Marshal(b, m, deterministic)
}
func (m *MysqlInnerUpdateRoleInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysqlInnerUpdateRoleInfoRsp.Merge(m, src)
}
func (m *MysqlInnerUpdateRoleInfoRsp) XXX_Size() int {
	return xxx_messageInfo_MysqlInnerUpdateRoleInfoRsp.Size(m)
}
func (m *MysqlInnerUpdateRoleInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MysqlInnerUpdateRoleInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MysqlInnerUpdateRoleInfoRsp proto.InternalMessageInfo

func (m *MysqlInnerUpdateRoleInfoRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

// MYSQL_INNER_SEARCH_ROLE_REQ
type MysqlInnerSearchRoleReq struct {
	SearchString         string   `protobuf:"bytes,1,opt,name=search_string,json=searchString,proto3" json:"search_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysqlInnerSearchRoleReq) Reset()         { *m = MysqlInnerSearchRoleReq{} }
func (m *MysqlInnerSearchRoleReq) String() string { return proto.CompactTextString(m) }
func (*MysqlInnerSearchRoleReq) ProtoMessage()    {}
func (*MysqlInnerSearchRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_43471e5c926502ed, []int{2}
}

func (m *MysqlInnerSearchRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysqlInnerSearchRoleReq.Unmarshal(m, b)
}
func (m *MysqlInnerSearchRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysqlInnerSearchRoleReq.Marshal(b, m, deterministic)
}
func (m *MysqlInnerSearchRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysqlInnerSearchRoleReq.Merge(m, src)
}
func (m *MysqlInnerSearchRoleReq) XXX_Size() int {
	return xxx_messageInfo_MysqlInnerSearchRoleReq.Size(m)
}
func (m *MysqlInnerSearchRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MysqlInnerSearchRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_MysqlInnerSearchRoleReq proto.InternalMessageInfo

func (m *MysqlInnerSearchRoleReq) GetSearchString() string {
	if m != nil {
		return m.SearchString
	}
	return ""
}

type MysqlInnerSearchRoleRsp struct {
	Ret                  *Ret     `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysqlInnerSearchRoleRsp) Reset()         { *m = MysqlInnerSearchRoleRsp{} }
func (m *MysqlInnerSearchRoleRsp) String() string { return proto.CompactTextString(m) }
func (*MysqlInnerSearchRoleRsp) ProtoMessage()    {}
func (*MysqlInnerSearchRoleRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_43471e5c926502ed, []int{3}
}

func (m *MysqlInnerSearchRoleRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysqlInnerSearchRoleRsp.Unmarshal(m, b)
}
func (m *MysqlInnerSearchRoleRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysqlInnerSearchRoleRsp.Marshal(b, m, deterministic)
}
func (m *MysqlInnerSearchRoleRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysqlInnerSearchRoleRsp.Merge(m, src)
}
func (m *MysqlInnerSearchRoleRsp) XXX_Size() int {
	return xxx_messageInfo_MysqlInnerSearchRoleRsp.Size(m)
}
func (m *MysqlInnerSearchRoleRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MysqlInnerSearchRoleRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MysqlInnerSearchRoleRsp proto.InternalMessageInfo

func (m *MysqlInnerSearchRoleRsp) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *MysqlInnerSearchRoleRsp) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterEnum("g1.protocol.EMysqlType", EMysqlType_name, EMysqlType_value)
	proto.RegisterType((*MysqlInnerUpdateRoleInfoReq)(nil), "g1.protocol.MysqlInnerUpdateRoleInfoReq")
	proto.RegisterType((*MysqlInnerUpdateRoleInfoRsp)(nil), "g1.protocol.MysqlInnerUpdateRoleInfoRsp")
	proto.RegisterType((*MysqlInnerSearchRoleReq)(nil), "g1.protocol.MysqlInnerSearchRoleReq")
	proto.RegisterType((*MysqlInnerSearchRoleRsp)(nil), "g1.protocol.MysqlInnerSearchRoleRsp")
}

func init() {
	proto.RegisterFile("mysqlsvr.proto", fileDescriptor_43471e5c926502ed)
}

var fileDescriptor_43471e5c926502ed = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8d, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xad, 0x1b, 0x82, 0x6f, 0x53, 0x42, 0x18, 0x58, 0xf4, 0x32, 0xe2, 0x65, 0x78, 0x28,
	0x4c, 0xaf, 0x22, 0x78, 0xa8, 0x50, 0xd8, 0x5a, 0x4d, 0xe7, 0x61, 0xa7, 0x50, 0xbb, 0xe7, 0x1c,
	0xb4, 0x49, 0x96, 0x44, 0x61, 0xff, 0xbd, 0x24, 0x15, 0xdc, 0x45, 0xd9, 0xed, 0xe3, 0xf7, 0xde,
	0xf7, 0xfd, 0xe0, 0xbc, 0xdd, 0xd9, 0x6d, 0x63, 0xbf, 0x4c, 0xa2, 0x8d, 0x72, 0x8a, 0x0e, 0xd6,
	0xd3, 0x2e, 0xd5, 0xaa, 0xb9, 0x1c, 0xd6, 0xaa, 0x6d, 0x95, 0xec, 0x00, 0x9b, 0xc2, 0xd5, 0xdc,
	0x3f, 0x67, 0x52, 0xa2, 0x79, 0xd5, 0xab, 0xca, 0x21, 0x57, 0x0d, 0x66, 0xf2, 0x5d, 0x71, 0xdc,
	0x52, 0x0a, 0x7d, 0x59, 0xb5, 0x18, 0x47, 0xe3, 0x68, 0x72, 0xca, 0x43, 0x66, 0x8f, 0xff, 0x54,
	0xac, 0xa6, 0x0c, 0x7a, 0x06, 0x5d, 0x68, 0x0c, 0x6e, 0x49, 0xb2, 0xa7, 0x4e, 0x38, 0x3a, 0xee,
	0x8f, 0xec, 0x01, 0x2e, 0x7e, 0x27, 0x4a, 0xac, 0x4c, 0xfd, 0xe1, 0x27, 0xbc, 0xf1, 0x1a, 0xce,
	0x6c, 0x00, 0xc2, 0x3a, 0xb3, 0x91, 0xeb, 0x1f, 0xf5, 0xb0, 0x83, 0x65, 0x60, 0xac, 0xf8, 0xa3,
	0x7f, 0x98, 0x9e, 0x12, 0xe8, 0x7d, 0x6e, 0x56, 0xf1, 0xf1, 0x38, 0x9a, 0xf4, 0xb9, 0x8f, 0x37,
	0xf7, 0x00, 0x69, 0x58, 0x5c, 0xec, 0x34, 0xd2, 0x11, 0x10, 0x31, 0x5f, 0x96, 0x2f, 0x33, 0xb1,
	0x58, 0x3e, 0xa7, 0x22, 0x2f, 0xf2, 0x94, 0x1c, 0xd1, 0x18, 0x46, 0x7b, 0x90, 0x17, 0xb3, 0x54,
	0x64, 0xf9, 0x53, 0x41, 0xa2, 0xb7, 0x93, 0xa0, 0xb8, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x19,
	0x77, 0xfe, 0x6a, 0x78, 0x01, 0x00, 0x00,
}
