// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package g1_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoleRegisterInfo struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RegisterTime         int32    `protobuf:"varint,2,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	Zone                 int32    `protobuf:"varint,3,opt,name=zone,proto3" json:"zone,omitempty"`
	TimeOffsetMinute     int32    `protobuf:"varint,4,opt,name=time_offset_minute,json=timeOffsetMinute,proto3" json:"time_offset_minute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleRegisterInfo) Reset()         { *m = RoleRegisterInfo{} }
func (m *RoleRegisterInfo) String() string { return proto.CompactTextString(m) }
func (*RoleRegisterInfo) ProtoMessage()    {}
func (*RoleRegisterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{0}
}

func (m *RoleRegisterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleRegisterInfo.Unmarshal(m, b)
}
func (m *RoleRegisterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleRegisterInfo.Marshal(b, m, deterministic)
}
func (m *RoleRegisterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleRegisterInfo.Merge(m, src)
}
func (m *RoleRegisterInfo) XXX_Size() int {
	return xxx_messageInfo_RoleRegisterInfo.Size(m)
}
func (m *RoleRegisterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleRegisterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleRegisterInfo proto.InternalMessageInfo

func (m *RoleRegisterInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RoleRegisterInfo) GetRegisterTime() int32 {
	if m != nil {
		return m.RegisterTime
	}
	return 0
}

func (m *RoleRegisterInfo) GetZone() int32 {
	if m != nil {
		return m.Zone
	}
	return 0
}

func (m *RoleRegisterInfo) GetTimeOffsetMinute() int32 {
	if m != nil {
		return m.TimeOffsetMinute
	}
	return 0
}

type RoleLoginInfo struct {
	LastLoginTime        int32    `protobuf:"varint,1,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	LastLogoutTime       int32    `protobuf:"varint,2,opt,name=last_logout_time,json=lastLogoutTime,proto3" json:"last_logout_time,omitempty"`
	LastHartBeatTime     int32    `protobuf:"varint,3,opt,name=last_hart_beat_time,json=lastHartBeatTime,proto3" json:"last_hart_beat_time,omitempty"`
	NowLoginTime         int32    `protobuf:"varint,4,opt,name=now_login_time,json=nowLoginTime,proto3" json:"now_login_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleLoginInfo) Reset()         { *m = RoleLoginInfo{} }
func (m *RoleLoginInfo) String() string { return proto.CompactTextString(m) }
func (*RoleLoginInfo) ProtoMessage()    {}
func (*RoleLoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{1}
}

func (m *RoleLoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleLoginInfo.Unmarshal(m, b)
}
func (m *RoleLoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleLoginInfo.Marshal(b, m, deterministic)
}
func (m *RoleLoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleLoginInfo.Merge(m, src)
}
func (m *RoleLoginInfo) XXX_Size() int {
	return xxx_messageInfo_RoleLoginInfo.Size(m)
}
func (m *RoleLoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleLoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleLoginInfo proto.InternalMessageInfo

func (m *RoleLoginInfo) GetLastLoginTime() int32 {
	if m != nil {
		return m.LastLoginTime
	}
	return 0
}

func (m *RoleLoginInfo) GetLastLogoutTime() int32 {
	if m != nil {
		return m.LastLogoutTime
	}
	return 0
}

func (m *RoleLoginInfo) GetLastHartBeatTime() int32 {
	if m != nil {
		return m.LastHartBeatTime
	}
	return 0
}

func (m *RoleLoginInfo) GetNowLoginTime() int32 {
	if m != nil {
		return m.NowLoginTime
	}
	return 0
}

type RoleDescInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IconId               int32    `protobuf:"varint,2,opt,name=icon_id,json=iconId,proto3" json:"icon_id,omitempty"`
	FrameId              int32    `protobuf:"varint,3,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	FreeCnt              uint32   `protobuf:"varint,4,opt,name=free_cnt,json=freeCnt,proto3" json:"free_cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleDescInfo) Reset()         { *m = RoleDescInfo{} }
func (m *RoleDescInfo) String() string { return proto.CompactTextString(m) }
func (*RoleDescInfo) ProtoMessage()    {}
func (*RoleDescInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{2}
}

func (m *RoleDescInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleDescInfo.Unmarshal(m, b)
}
func (m *RoleDescInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleDescInfo.Marshal(b, m, deterministic)
}
func (m *RoleDescInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleDescInfo.Merge(m, src)
}
func (m *RoleDescInfo) XXX_Size() int {
	return xxx_messageInfo_RoleDescInfo.Size(m)
}
func (m *RoleDescInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleDescInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleDescInfo proto.InternalMessageInfo

func (m *RoleDescInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleDescInfo) GetIconId() int32 {
	if m != nil {
		return m.IconId
	}
	return 0
}

func (m *RoleDescInfo) GetFrameId() int32 {
	if m != nil {
		return m.FrameId
	}
	return 0
}

func (m *RoleDescInfo) GetFreeCnt() uint32 {
	if m != nil {
		return m.FreeCnt
	}
	return 0
}

type RoleBasicInfo struct {
	Level                int32    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Exp                  int32    `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold                 int32    `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	Diamond              int32    `protobuf:"varint,4,opt,name=diamond,proto3" json:"diamond,omitempty"`
	Sinew                int32    `protobuf:"varint,5,opt,name=sinew,proto3" json:"sinew,omitempty"`
	Liveness             int32    `protobuf:"varint,6,opt,name=liveness,proto3" json:"liveness,omitempty"`
	GuildCoin            int32    `protobuf:"varint,7,opt,name=guild_coin,json=guildCoin,proto3" json:"guild_coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleBasicInfo) Reset()         { *m = RoleBasicInfo{} }
func (m *RoleBasicInfo) String() string { return proto.CompactTextString(m) }
func (*RoleBasicInfo) ProtoMessage()    {}
func (*RoleBasicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{3}
}

func (m *RoleBasicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleBasicInfo.Unmarshal(m, b)
}
func (m *RoleBasicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleBasicInfo.Marshal(b, m, deterministic)
}
func (m *RoleBasicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleBasicInfo.Merge(m, src)
}
func (m *RoleBasicInfo) XXX_Size() int {
	return xxx_messageInfo_RoleBasicInfo.Size(m)
}
func (m *RoleBasicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleBasicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleBasicInfo proto.InternalMessageInfo

func (m *RoleBasicInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RoleBasicInfo) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *RoleBasicInfo) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *RoleBasicInfo) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *RoleBasicInfo) GetSinew() int32 {
	if m != nil {
		return m.Sinew
	}
	return 0
}

func (m *RoleBasicInfo) GetLiveness() int32 {
	if m != nil {
		return m.Liveness
	}
	return 0
}

func (m *RoleBasicInfo) GetGuildCoin() int32 {
	if m != nil {
		return m.GuildCoin
	}
	return 0
}

// 道具信息
type PbItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbItem) Reset()         { *m = PbItem{} }
func (m *PbItem) String() string { return proto.CompactTextString(m) }
func (*PbItem) ProtoMessage()    {}
func (*PbItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{4}
}

func (m *PbItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbItem.Unmarshal(m, b)
}
func (m *PbItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbItem.Marshal(b, m, deterministic)
}
func (m *PbItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbItem.Merge(m, src)
}
func (m *PbItem) XXX_Size() int {
	return xxx_messageInfo_PbItem.Size(m)
}
func (m *PbItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PbItem.DiscardUnknown(m)
}

var xxx_messageInfo_PbItem proto.InternalMessageInfo

func (m *PbItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PbItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RoleInventoryInfo struct {
	ItemList             []*PbItem `protobuf:"bytes,1,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoleInventoryInfo) Reset()         { *m = RoleInventoryInfo{} }
func (m *RoleInventoryInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInventoryInfo) ProtoMessage()    {}
func (*RoleInventoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{5}
}

func (m *RoleInventoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInventoryInfo.Unmarshal(m, b)
}
func (m *RoleInventoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInventoryInfo.Marshal(b, m, deterministic)
}
func (m *RoleInventoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInventoryInfo.Merge(m, src)
}
func (m *RoleInventoryInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInventoryInfo.Size(m)
}
func (m *RoleInventoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInventoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInventoryInfo proto.InternalMessageInfo

func (m *RoleInventoryInfo) GetItemList() []*PbItem {
	if m != nil {
		return m.ItemList
	}
	return nil
}

// 头像
type PbIcon struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RedPoint             bool     `protobuf:"varint,2,opt,name=red_point,json=redPoint,proto3" json:"red_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbIcon) Reset()         { *m = PbIcon{} }
func (m *PbIcon) String() string { return proto.CompactTextString(m) }
func (*PbIcon) ProtoMessage()    {}
func (*PbIcon) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{6}
}

func (m *PbIcon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbIcon.Unmarshal(m, b)
}
func (m *PbIcon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbIcon.Marshal(b, m, deterministic)
}
func (m *PbIcon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbIcon.Merge(m, src)
}
func (m *PbIcon) XXX_Size() int {
	return xxx_messageInfo_PbIcon.Size(m)
}
func (m *PbIcon) XXX_DiscardUnknown() {
	xxx_messageInfo_PbIcon.DiscardUnknown(m)
}

var xxx_messageInfo_PbIcon proto.InternalMessageInfo

func (m *PbIcon) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PbIcon) GetRedPoint() bool {
	if m != nil {
		return m.RedPoint
	}
	return false
}

// 头像框
type PbFrame struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RedPoint             bool     `protobuf:"varint,2,opt,name=red_point,json=redPoint,proto3" json:"red_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbFrame) Reset()         { *m = PbFrame{} }
func (m *PbFrame) String() string { return proto.CompactTextString(m) }
func (*PbFrame) ProtoMessage()    {}
func (*PbFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{7}
}

func (m *PbFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbFrame.Unmarshal(m, b)
}
func (m *PbFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbFrame.Marshal(b, m, deterministic)
}
func (m *PbFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbFrame.Merge(m, src)
}
func (m *PbFrame) XXX_Size() int {
	return xxx_messageInfo_PbFrame.Size(m)
}
func (m *PbFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PbFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PbFrame proto.InternalMessageInfo

func (m *PbFrame) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PbFrame) GetRedPoint() bool {
	if m != nil {
		return m.RedPoint
	}
	return false
}

// 头像
type RoleIconInfo struct {
	IconList             []*PbIcon  `protobuf:"bytes,1,rep,name=icon_list,json=iconList,proto3" json:"icon_list,omitempty"`
	FrameList            []*PbFrame `protobuf:"bytes,2,rep,name=frame_list,json=frameList,proto3" json:"frame_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoleIconInfo) Reset()         { *m = RoleIconInfo{} }
func (m *RoleIconInfo) String() string { return proto.CompactTextString(m) }
func (*RoleIconInfo) ProtoMessage()    {}
func (*RoleIconInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{8}
}

func (m *RoleIconInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleIconInfo.Unmarshal(m, b)
}
func (m *RoleIconInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleIconInfo.Marshal(b, m, deterministic)
}
func (m *RoleIconInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleIconInfo.Merge(m, src)
}
func (m *RoleIconInfo) XXX_Size() int {
	return xxx_messageInfo_RoleIconInfo.Size(m)
}
func (m *RoleIconInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleIconInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleIconInfo proto.InternalMessageInfo

func (m *RoleIconInfo) GetIconList() []*PbIcon {
	if m != nil {
		return m.IconList
	}
	return nil
}

func (m *RoleIconInfo) GetFrameList() []*PbFrame {
	if m != nil {
		return m.FrameList
	}
	return nil
}

// 商城礼包
type PbMallItem struct {
	ConfId               int32    `protobuf:"varint,1,opt,name=conf_id,json=confId,proto3" json:"conf_id,omitempty"`
	DailyBuyCount        int32    `protobuf:"varint,2,opt,name=daily_buy_count,json=dailyBuyCount,proto3" json:"daily_buy_count,omitempty"`
	TotalBuyCount        int32    `protobuf:"varint,3,opt,name=total_buy_count,json=totalBuyCount,proto3" json:"total_buy_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbMallItem) Reset()         { *m = PbMallItem{} }
func (m *PbMallItem) String() string { return proto.CompactTextString(m) }
func (*PbMallItem) ProtoMessage()    {}
func (*PbMallItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{9}
}

func (m *PbMallItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbMallItem.Unmarshal(m, b)
}
func (m *PbMallItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbMallItem.Marshal(b, m, deterministic)
}
func (m *PbMallItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbMallItem.Merge(m, src)
}
func (m *PbMallItem) XXX_Size() int {
	return xxx_messageInfo_PbMallItem.Size(m)
}
func (m *PbMallItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PbMallItem.DiscardUnknown(m)
}

var xxx_messageInfo_PbMallItem proto.InternalMessageInfo

func (m *PbMallItem) GetConfId() int32 {
	if m != nil {
		return m.ConfId
	}
	return 0
}

func (m *PbMallItem) GetDailyBuyCount() int32 {
	if m != nil {
		return m.DailyBuyCount
	}
	return 0
}

func (m *PbMallItem) GetTotalBuyCount() int32 {
	if m != nil {
		return m.TotalBuyCount
	}
	return 0
}

// 商城礼包
type RoleMallInfo struct {
	ItemList             []*PbMallItem `protobuf:"bytes,1,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoleMallInfo) Reset()         { *m = RoleMallInfo{} }
func (m *RoleMallInfo) String() string { return proto.CompactTextString(m) }
func (*RoleMallInfo) ProtoMessage()    {}
func (*RoleMallInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{10}
}

func (m *RoleMallInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMallInfo.Unmarshal(m, b)
}
func (m *RoleMallInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMallInfo.Marshal(b, m, deterministic)
}
func (m *RoleMallInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMallInfo.Merge(m, src)
}
func (m *RoleMallInfo) XXX_Size() int {
	return xxx_messageInfo_RoleMallInfo.Size(m)
}
func (m *RoleMallInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMallInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMallInfo proto.InternalMessageInfo

func (m *RoleMallInfo) GetItemList() []*PbMallItem {
	if m != nil {
		return m.ItemList
	}
	return nil
}

type PbTask struct {
	TaskId               int32    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Argv1                int32    `protobuf:"varint,2,opt,name=argv1,proto3" json:"argv1,omitempty"`
	Argv2                int32    `protobuf:"varint,3,opt,name=argv2,proto3" json:"argv2,omitempty"`
	Argv3                int32    `protobuf:"varint,4,opt,name=argv3,proto3" json:"argv3,omitempty"`
	Progress             int32    `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskType             int32    `protobuf:"varint,6,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	HasAward             int32    `protobuf:"varint,7,opt,name=has_award,json=hasAward,proto3" json:"has_award,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbTask) Reset()         { *m = PbTask{} }
func (m *PbTask) String() string { return proto.CompactTextString(m) }
func (*PbTask) ProtoMessage()    {}
func (*PbTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{11}
}

func (m *PbTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbTask.Unmarshal(m, b)
}
func (m *PbTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbTask.Marshal(b, m, deterministic)
}
func (m *PbTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbTask.Merge(m, src)
}
func (m *PbTask) XXX_Size() int {
	return xxx_messageInfo_PbTask.Size(m)
}
func (m *PbTask) XXX_DiscardUnknown() {
	xxx_messageInfo_PbTask.DiscardUnknown(m)
}

var xxx_messageInfo_PbTask proto.InternalMessageInfo

func (m *PbTask) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *PbTask) GetArgv1() int32 {
	if m != nil {
		return m.Argv1
	}
	return 0
}

func (m *PbTask) GetArgv2() int32 {
	if m != nil {
		return m.Argv2
	}
	return 0
}

func (m *PbTask) GetArgv3() int32 {
	if m != nil {
		return m.Argv3
	}
	return 0
}

func (m *PbTask) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *PbTask) GetTaskType() int32 {
	if m != nil {
		return m.TaskType
	}
	return 0
}

func (m *PbTask) GetHasAward() int32 {
	if m != nil {
		return m.HasAward
	}
	return 0
}

type RoleTaskInfo struct {
	TaskList             []*PbTask `protobuf:"bytes,1,rep,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoleTaskInfo) Reset()         { *m = RoleTaskInfo{} }
func (m *RoleTaskInfo) String() string { return proto.CompactTextString(m) }
func (*RoleTaskInfo) ProtoMessage()    {}
func (*RoleTaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{12}
}

func (m *RoleTaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleTaskInfo.Unmarshal(m, b)
}
func (m *RoleTaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleTaskInfo.Marshal(b, m, deterministic)
}
func (m *RoleTaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleTaskInfo.Merge(m, src)
}
func (m *RoleTaskInfo) XXX_Size() int {
	return xxx_messageInfo_RoleTaskInfo.Size(m)
}
func (m *RoleTaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleTaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleTaskInfo proto.InternalMessageInfo

func (m *RoleTaskInfo) GetTaskList() []*PbTask {
	if m != nil {
		return m.TaskList
	}
	return nil
}

// 主线任务
type RoleMainTaskInfo struct {
	CurTaskId            int32    `protobuf:"varint,1,opt,name=cur_task_id,json=curTaskId,proto3" json:"cur_task_id,omitempty"`
	Finished             bool     `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleMainTaskInfo) Reset()         { *m = RoleMainTaskInfo{} }
func (m *RoleMainTaskInfo) String() string { return proto.CompactTextString(m) }
func (*RoleMainTaskInfo) ProtoMessage()    {}
func (*RoleMainTaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{13}
}

func (m *RoleMainTaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMainTaskInfo.Unmarshal(m, b)
}
func (m *RoleMainTaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMainTaskInfo.Marshal(b, m, deterministic)
}
func (m *RoleMainTaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMainTaskInfo.Merge(m, src)
}
func (m *RoleMainTaskInfo) XXX_Size() int {
	return xxx_messageInfo_RoleMainTaskInfo.Size(m)
}
func (m *RoleMainTaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMainTaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMainTaskInfo proto.InternalMessageInfo

func (m *RoleMainTaskInfo) GetCurTaskId() int32 {
	if m != nil {
		return m.CurTaskId
	}
	return 0
}

func (m *RoleMainTaskInfo) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

// 个人公会信息 ,例如公会副本，商场购买记录等
type RoleGuildInfo struct {
	Gid                  uint64   `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title                int32    `protobuf:"varint,3,opt,name=title,proto3" json:"title,omitempty"`
	DonateCnt            uint32   `protobuf:"varint,4,opt,name=donate_cnt,json=donateCnt,proto3" json:"donate_cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleGuildInfo) Reset()         { *m = RoleGuildInfo{} }
func (m *RoleGuildInfo) String() string { return proto.CompactTextString(m) }
func (*RoleGuildInfo) ProtoMessage()    {}
func (*RoleGuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{14}
}

func (m *RoleGuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleGuildInfo.Unmarshal(m, b)
}
func (m *RoleGuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleGuildInfo.Marshal(b, m, deterministic)
}
func (m *RoleGuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleGuildInfo.Merge(m, src)
}
func (m *RoleGuildInfo) XXX_Size() int {
	return xxx_messageInfo_RoleGuildInfo.Size(m)
}
func (m *RoleGuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleGuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleGuildInfo proto.InternalMessageInfo

func (m *RoleGuildInfo) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *RoleGuildInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleGuildInfo) GetTitle() int32 {
	if m != nil {
		return m.Title
	}
	return 0
}

func (m *RoleGuildInfo) GetDonateCnt() uint32 {
	if m != nil {
		return m.DonateCnt
	}
	return 0
}

//玩家引导ID
type RoleGuideInfo struct {
	IdLis                []int32  `protobuf:"varint,1,rep,packed,name=id_lis,json=idLis,proto3" json:"id_lis,omitempty"`
	CurId                int32    `protobuf:"varint,2,opt,name=cur_id,json=curId,proto3" json:"cur_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleGuideInfo) Reset()         { *m = RoleGuideInfo{} }
func (m *RoleGuideInfo) String() string { return proto.CompactTextString(m) }
func (*RoleGuideInfo) ProtoMessage()    {}
func (*RoleGuideInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{15}
}

func (m *RoleGuideInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleGuideInfo.Unmarshal(m, b)
}
func (m *RoleGuideInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleGuideInfo.Marshal(b, m, deterministic)
}
func (m *RoleGuideInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleGuideInfo.Merge(m, src)
}
func (m *RoleGuideInfo) XXX_Size() int {
	return xxx_messageInfo_RoleGuideInfo.Size(m)
}
func (m *RoleGuideInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleGuideInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleGuideInfo proto.InternalMessageInfo

func (m *RoleGuideInfo) GetIdLis() []int32 {
	if m != nil {
		return m.IdLis
	}
	return nil
}

func (m *RoleGuideInfo) GetCurId() int32 {
	if m != nil {
		return m.CurId
	}
	return 0
}

// 功能开放列表
type RoleOpenFunction struct {
	Data                 []int32  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	IsAllOpen            bool     `protobuf:"varint,2,opt,name=is_all_open,json=isAllOpen,proto3" json:"is_all_open,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleOpenFunction) Reset()         { *m = RoleOpenFunction{} }
func (m *RoleOpenFunction) String() string { return proto.CompactTextString(m) }
func (*RoleOpenFunction) ProtoMessage()    {}
func (*RoleOpenFunction) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{16}
}

func (m *RoleOpenFunction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleOpenFunction.Unmarshal(m, b)
}
func (m *RoleOpenFunction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleOpenFunction.Marshal(b, m, deterministic)
}
func (m *RoleOpenFunction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleOpenFunction.Merge(m, src)
}
func (m *RoleOpenFunction) XXX_Size() int {
	return xxx_messageInfo_RoleOpenFunction.Size(m)
}
func (m *RoleOpenFunction) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleOpenFunction.DiscardUnknown(m)
}

var xxx_messageInfo_RoleOpenFunction proto.InternalMessageInfo

func (m *RoleOpenFunction) GetData() []int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RoleOpenFunction) GetIsAllOpen() bool {
	if m != nil {
		return m.IsAllOpen
	}
	return false
}

// 礼包码
type RoleGiftExchangeInfo struct {
	TypeList             []int32  `protobuf:"varint,1,rep,packed,name=type_list,json=typeList,proto3" json:"type_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleGiftExchangeInfo) Reset()         { *m = RoleGiftExchangeInfo{} }
func (m *RoleGiftExchangeInfo) String() string { return proto.CompactTextString(m) }
func (*RoleGiftExchangeInfo) ProtoMessage()    {}
func (*RoleGiftExchangeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{17}
}

func (m *RoleGiftExchangeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleGiftExchangeInfo.Unmarshal(m, b)
}
func (m *RoleGiftExchangeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleGiftExchangeInfo.Marshal(b, m, deterministic)
}
func (m *RoleGiftExchangeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleGiftExchangeInfo.Merge(m, src)
}
func (m *RoleGiftExchangeInfo) XXX_Size() int {
	return xxx_messageInfo_RoleGiftExchangeInfo.Size(m)
}
func (m *RoleGiftExchangeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleGiftExchangeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleGiftExchangeInfo proto.InternalMessageInfo

func (m *RoleGiftExchangeInfo) GetTypeList() []int32 {
	if m != nil {
		return m.TypeList
	}
	return nil
}

//活动任务,日常，成就等
type RoleActvityTaskInfo struct {
	TaskList             []*PbTask `protobuf:"bytes,1,rep,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoleActvityTaskInfo) Reset()         { *m = RoleActvityTaskInfo{} }
func (m *RoleActvityTaskInfo) String() string { return proto.CompactTextString(m) }
func (*RoleActvityTaskInfo) ProtoMessage()    {}
func (*RoleActvityTaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{18}
}

func (m *RoleActvityTaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleActvityTaskInfo.Unmarshal(m, b)
}
func (m *RoleActvityTaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleActvityTaskInfo.Marshal(b, m, deterministic)
}
func (m *RoleActvityTaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleActvityTaskInfo.Merge(m, src)
}
func (m *RoleActvityTaskInfo) XXX_Size() int {
	return xxx_messageInfo_RoleActvityTaskInfo.Size(m)
}
func (m *RoleActvityTaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleActvityTaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleActvityTaskInfo proto.InternalMessageInfo

func (m *RoleActvityTaskInfo) GetTaskList() []*PbTask {
	if m != nil {
		return m.TaskList
	}
	return nil
}

// 角色的所有数据
type RoleInfo struct {
	RegisterInfo         *RoleRegisterInfo     `protobuf:"bytes,1,opt,name=register_info,json=registerInfo,proto3" json:"register_info,omitempty"`
	LoginInfo            *RoleLoginInfo        `protobuf:"bytes,2,opt,name=login_info,json=loginInfo,proto3" json:"login_info,omitempty"`
	DescInfo             *RoleDescInfo         `protobuf:"bytes,3,opt,name=desc_info,json=descInfo,proto3" json:"desc_info,omitempty"`
	BasicInfo            *RoleBasicInfo        `protobuf:"bytes,4,opt,name=basic_info,json=basicInfo,proto3" json:"basic_info,omitempty"`
	InventoryInfo        *RoleInventoryInfo    `protobuf:"bytes,5,opt,name=inventory_info,json=inventoryInfo,proto3" json:"inventory_info,omitempty"`
	IconInfo             *RoleIconInfo         `protobuf:"bytes,6,opt,name=icon_info,json=iconInfo,proto3" json:"icon_info,omitempty"`
	MallInfo             *RoleMallInfo         `protobuf:"bytes,7,opt,name=mall_info,json=mallInfo,proto3" json:"mall_info,omitempty"`
	MainTaskInfo         *RoleMainTaskInfo     `protobuf:"bytes,8,opt,name=main_task_info,json=mainTaskInfo,proto3" json:"main_task_info,omitempty"`
	GuildInfo            *RoleGuildInfo        `protobuf:"bytes,9,opt,name=guild_info,json=guildInfo,proto3" json:"guild_info,omitempty"`
	GuideInfo            *RoleGuideInfo        `protobuf:"bytes,10,opt,name=guide_info,json=guideInfo,proto3" json:"guide_info,omitempty"`
	OpenFunInfo          *RoleOpenFunction     `protobuf:"bytes,11,opt,name=open_fun_info,json=openFunInfo,proto3" json:"open_fun_info,omitempty"`
	GiftInfo             *RoleGiftExchangeInfo `protobuf:"bytes,12,opt,name=gift_info,json=giftInfo,proto3" json:"gift_info,omitempty"`
	Actvity_Info         *RoleActvityTaskInfo  `protobuf:"bytes,13,opt,name=actvity_Info,json=actvityInfo,proto3" json:"actvity_Info,omitempty"`
	ConnSvrInfo          *ConnSvrInfo          `protobuf:"bytes,100,opt,name=conn_svr_info,json=connSvrInfo,proto3" json:"conn_svr_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{19}
}

func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInfo.Unmarshal(m, b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInfo.Size(m)
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetRegisterInfo() *RoleRegisterInfo {
	if m != nil {
		return m.RegisterInfo
	}
	return nil
}

func (m *RoleInfo) GetLoginInfo() *RoleLoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

func (m *RoleInfo) GetDescInfo() *RoleDescInfo {
	if m != nil {
		return m.DescInfo
	}
	return nil
}

func (m *RoleInfo) GetBasicInfo() *RoleBasicInfo {
	if m != nil {
		return m.BasicInfo
	}
	return nil
}

func (m *RoleInfo) GetInventoryInfo() *RoleInventoryInfo {
	if m != nil {
		return m.InventoryInfo
	}
	return nil
}

func (m *RoleInfo) GetIconInfo() *RoleIconInfo {
	if m != nil {
		return m.IconInfo
	}
	return nil
}

func (m *RoleInfo) GetMallInfo() *RoleMallInfo {
	if m != nil {
		return m.MallInfo
	}
	return nil
}

func (m *RoleInfo) GetMainTaskInfo() *RoleMainTaskInfo {
	if m != nil {
		return m.MainTaskInfo
	}
	return nil
}

func (m *RoleInfo) GetGuildInfo() *RoleGuildInfo {
	if m != nil {
		return m.GuildInfo
	}
	return nil
}

func (m *RoleInfo) GetGuideInfo() *RoleGuideInfo {
	if m != nil {
		return m.GuideInfo
	}
	return nil
}

func (m *RoleInfo) GetOpenFunInfo() *RoleOpenFunction {
	if m != nil {
		return m.OpenFunInfo
	}
	return nil
}

func (m *RoleInfo) GetGiftInfo() *RoleGiftExchangeInfo {
	if m != nil {
		return m.GiftInfo
	}
	return nil
}

func (m *RoleInfo) GetActvity_Info() *RoleActvityTaskInfo {
	if m != nil {
		return m.Actvity_Info
	}
	return nil
}

func (m *RoleInfo) GetConnSvrInfo() *ConnSvrInfo {
	if m != nil {
		return m.ConnSvrInfo
	}
	return nil
}

type ConnSvrInfo struct {
	BusId                uint32   `protobuf:"varint,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	ClientPos            string   `protobuf:"bytes,2,opt,name=client_pos,json=clientPos,proto3" json:"client_pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnSvrInfo) Reset()         { *m = ConnSvrInfo{} }
func (m *ConnSvrInfo) String() string { return proto.CompactTextString(m) }
func (*ConnSvrInfo) ProtoMessage()    {}
func (*ConnSvrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{20}
}

func (m *ConnSvrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnSvrInfo.Unmarshal(m, b)
}
func (m *ConnSvrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnSvrInfo.Marshal(b, m, deterministic)
}
func (m *ConnSvrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnSvrInfo.Merge(m, src)
}
func (m *ConnSvrInfo) XXX_Size() int {
	return xxx_messageInfo_ConnSvrInfo.Size(m)
}
func (m *ConnSvrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnSvrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnSvrInfo proto.InternalMessageInfo

func (m *ConnSvrInfo) GetBusId() uint32 {
	if m != nil {
		return m.BusId
	}
	return 0
}

func (m *ConnSvrInfo) GetClientPos() string {
	if m != nil {
		return m.ClientPos
	}
	return ""
}

// 玩家头像框需要的信息
type PbIconDesc struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 int32    `protobuf:"varint,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Frame                int32    `protobuf:"varint,4,opt,name=frame,proto3" json:"frame,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	VipLevel             int32    `protobuf:"varint,6,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`
	LastOnlineTime       int32    `protobuf:"varint,30,opt,name=last_online_time,json=lastOnlineTime,proto3" json:"last_online_time,omitempty"`
	IsOnline             bool     `protobuf:"varint,31,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbIconDesc) Reset()         { *m = PbIconDesc{} }
func (m *PbIconDesc) String() string { return proto.CompactTextString(m) }
func (*PbIconDesc) ProtoMessage()    {}
func (*PbIconDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{21}
}

func (m *PbIconDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbIconDesc.Unmarshal(m, b)
}
func (m *PbIconDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbIconDesc.Marshal(b, m, deterministic)
}
func (m *PbIconDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbIconDesc.Merge(m, src)
}
func (m *PbIconDesc) XXX_Size() int {
	return xxx_messageInfo_PbIconDesc.Size(m)
}
func (m *PbIconDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_PbIconDesc.DiscardUnknown(m)
}

var xxx_messageInfo_PbIconDesc proto.InternalMessageInfo

func (m *PbIconDesc) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PbIconDesc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PbIconDesc) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *PbIconDesc) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *PbIconDesc) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *PbIconDesc) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *PbIconDesc) GetLastOnlineTime() int32 {
	if m != nil {
		return m.LastOnlineTime
	}
	return 0
}

func (m *PbIconDesc) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func init() {
	proto.RegisterType((*RoleRegisterInfo)(nil), "g1.protocol.RoleRegisterInfo")
	proto.RegisterType((*RoleLoginInfo)(nil), "g1.protocol.RoleLoginInfo")
	proto.RegisterType((*RoleDescInfo)(nil), "g1.protocol.RoleDescInfo")
	proto.RegisterType((*RoleBasicInfo)(nil), "g1.protocol.RoleBasicInfo")
	proto.RegisterType((*PbItem)(nil), "g1.protocol.PbItem")
	proto.RegisterType((*RoleInventoryInfo)(nil), "g1.protocol.RoleInventoryInfo")
	proto.RegisterType((*PbIcon)(nil), "g1.protocol.PbIcon")
	proto.RegisterType((*PbFrame)(nil), "g1.protocol.PbFrame")
	proto.RegisterType((*RoleIconInfo)(nil), "g1.protocol.RoleIconInfo")
	proto.RegisterType((*PbMallItem)(nil), "g1.protocol.PbMallItem")
	proto.RegisterType((*RoleMallInfo)(nil), "g1.protocol.RoleMallInfo")
	proto.RegisterType((*PbTask)(nil), "g1.protocol.PbTask")
	proto.RegisterType((*RoleTaskInfo)(nil), "g1.protocol.RoleTaskInfo")
	proto.RegisterType((*RoleMainTaskInfo)(nil), "g1.protocol.RoleMainTaskInfo")
	proto.RegisterType((*RoleGuildInfo)(nil), "g1.protocol.RoleGuildInfo")
	proto.RegisterType((*RoleGuideInfo)(nil), "g1.protocol.RoleGuideInfo")
	proto.RegisterType((*RoleOpenFunction)(nil), "g1.protocol.RoleOpenFunction")
	proto.RegisterType((*RoleGiftExchangeInfo)(nil), "g1.protocol.RoleGiftExchangeInfo")
	proto.RegisterType((*RoleActvityTaskInfo)(nil), "g1.protocol.RoleActvityTaskInfo")
	proto.RegisterType((*RoleInfo)(nil), "g1.protocol.RoleInfo")
	proto.RegisterType((*ConnSvrInfo)(nil), "g1.protocol.ConnSvrInfo")
	proto.RegisterType((*PbIconDesc)(nil), "g1.protocol.PbIconDesc")
}

func init() {
	proto.RegisterFile("role.proto", fileDescriptor_48a3ff9f7c9032f8)
}

var fileDescriptor_48a3ff9f7c9032f8 = []byte{
	// 1296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xff, 0x6e, 0xdb, 0xb6,
	0x13, 0x87, 0x93, 0xd8, 0x96, 0xce, 0x71, 0xbe, 0xf9, 0xaa, 0x19, 0xea, 0xb6, 0x68, 0x97, 0x69,
	0xc3, 0x90, 0x3f, 0xb6, 0x60, 0x6d, 0xb6, 0x02, 0x05, 0xb6, 0x61, 0x49, 0xfa, 0x63, 0x06, 0xd2,
	0x35, 0xd0, 0xf2, 0xbf, 0x40, 0x4b, 0xb4, 0xc3, 0x55, 0x26, 0x35, 0x91, 0x72, 0xea, 0xbd, 0xc2,
	0xde, 0x67, 0xc0, 0x5e, 0x64, 0x4f, 0xb2, 0x07, 0x18, 0xee, 0x48, 0x2a, 0x4a, 0x5c, 0x17, 0x18,
	0xf6, 0x1f, 0xef, 0x78, 0x9f, 0xbb, 0x0f, 0xc9, 0xfb, 0x41, 0x80, 0x4a, 0x15, 0xfc, 0xb0, 0xac,
	0x94, 0x51, 0xd1, 0x60, 0xf6, 0xd8, 0xae, 0x32, 0x55, 0xc4, 0xbf, 0x77, 0x60, 0x37, 0x51, 0x05,
	0x4f, 0xf8, 0x4c, 0x68, 0xc3, 0xab, 0xb1, 0x9c, 0xaa, 0x68, 0x17, 0x36, 0x6b, 0x91, 0x8f, 0x3a,
	0xfb, 0x9d, 0x83, 0xad, 0x04, 0x97, 0xd1, 0xa7, 0x30, 0xac, 0x9c, 0x45, 0x6a, 0xc4, 0x9c, 0x8f,
	0x36, 0xf6, 0x3b, 0x07, 0xdd, 0x64, 0xdb, 0x2b, 0x2f, 0xc4, 0x9c, 0x47, 0x11, 0x6c, 0xfd, 0xa6,
	0x24, 0x1f, 0x6d, 0xd2, 0x1e, 0xad, 0xa3, 0x2f, 0x20, 0x42, 0xfb, 0x54, 0x4d, 0xa7, 0x9a, 0x9b,
	0x74, 0x2e, 0x64, 0x6d, 0xf8, 0x68, 0x8b, 0x2c, 0x76, 0x71, 0xe7, 0x0d, 0x6d, 0xbc, 0x26, 0x7d,
	0xfc, 0x47, 0x07, 0x86, 0xc8, 0xe6, 0x4c, 0xcd, 0x84, 0x24, 0x2a, 0x9f, 0xc3, 0xff, 0x0a, 0xa6,
	0x4d, 0x5a, 0xa0, 0xc6, 0x86, 0xee, 0x10, 0x78, 0x88, 0x6a, 0xb2, 0xa3, 0xd8, 0x07, 0xb0, 0xeb,
	0xed, 0x54, 0x6d, 0xda, 0x1c, 0x77, 0x9c, 0xa1, 0xaa, 0x0d, 0x59, 0x7e, 0x09, 0x77, 0xc8, 0xf2,
	0x92, 0x55, 0x26, 0x9d, 0x70, 0xe6, 0x8c, 0x2d, 0x69, 0x72, 0xf2, 0x23, 0xab, 0xcc, 0x09, 0x67,
	0xd6, 0xfc, 0x33, 0xd8, 0x91, 0xea, 0xaa, 0x1d, 0xdf, 0x92, 0xdf, 0x96, 0xea, 0xaa, 0x09, 0x1f,
	0xff, 0x0a, 0xdb, 0xc8, 0xfb, 0x39, 0xd7, 0x19, 0xd1, 0x8e, 0x60, 0x4b, 0x32, 0xc7, 0x35, 0x4c,
	0x68, 0x1d, 0xdd, 0x85, 0xbe, 0xc8, 0x94, 0x4c, 0x45, 0xee, 0x98, 0xf5, 0x50, 0x1c, 0xe7, 0xd1,
	0x3d, 0x08, 0xa6, 0x15, 0x9b, 0x73, 0xdc, 0xb1, 0x34, 0xfa, 0x24, 0xfb, 0x2d, 0xce, 0xd3, 0x4c,
	0x1a, 0x8a, 0x3b, 0xc4, 0x2d, 0xce, 0x4f, 0xa5, 0x69, 0xee, 0xea, 0x84, 0x69, 0x61, 0x83, 0xee,
	0x41, 0xb7, 0xe0, 0x0b, 0x5e, 0xb8, 0x1b, 0xb2, 0x02, 0x3e, 0x26, 0x7f, 0x57, 0xba, 0x90, 0xb8,
	0x44, 0x72, 0x33, 0x55, 0xf8, 0x58, 0xb4, 0x8e, 0x46, 0xd0, 0xcf, 0x05, 0x9b, 0x2b, 0x99, 0xbb,
	0xf3, 0x79, 0x11, 0xbd, 0x6a, 0x21, 0xf9, 0xd5, 0xa8, 0x6b, 0xbd, 0x92, 0x10, 0xdd, 0x87, 0xa0,
	0x10, 0x0b, 0x2e, 0xb9, 0xd6, 0xa3, 0x1e, 0x6d, 0x34, 0x72, 0xf4, 0x10, 0x60, 0x56, 0x8b, 0x22,
	0x4f, 0x33, 0x25, 0xe4, 0xa8, 0x4f, 0xbb, 0x21, 0x69, 0x4e, 0x95, 0x90, 0xf1, 0x21, 0xf4, 0xce,
	0x27, 0x63, 0xc3, 0xe7, 0xd1, 0x0e, 0x6c, 0xb8, 0x34, 0xeb, 0x26, 0x1b, 0x82, 0x42, 0x65, 0xaa,
	0x96, 0xc6, 0x91, 0xb5, 0x42, 0xfc, 0x02, 0xfe, 0x8f, 0xe7, 0x1c, 0xcb, 0x05, 0x97, 0x46, 0x55,
	0x4b, 0x3a, 0xeb, 0x57, 0x10, 0x0a, 0xc3, 0xe7, 0x69, 0x21, 0xb4, 0x19, 0x75, 0xf6, 0x37, 0x0f,
	0x06, 0x4f, 0xee, 0x1c, 0xb6, 0x12, 0xfb, 0xd0, 0x86, 0x48, 0x02, 0xb4, 0x3a, 0x13, 0xda, 0xc4,
	0xdf, 0x50, 0xd8, 0x4c, 0xc9, 0x95, 0xb0, 0x0f, 0x20, 0xac, 0x78, 0x9e, 0x96, 0x4a, 0xb8, 0xd0,
	0x41, 0x12, 0x54, 0x3c, 0x3f, 0x47, 0x39, 0x7e, 0x0a, 0xfd, 0xf3, 0xc9, 0x4b, 0x7c, 0x8e, 0x7f,
	0x87, 0xab, 0x6d, 0x46, 0x60, 0xc0, 0x86, 0x30, 0xbe, 0xfe, 0x87, 0x08, 0x67, 0x4a, 0x26, 0x01,
	0x5a, 0x21, 0xe1, 0xe8, 0x08, 0xc0, 0xa6, 0x05, 0x41, 0x36, 0x08, 0xb2, 0x77, 0x0b, 0x42, 0xc4,
	0x92, 0x90, 0xec, 0xe8, 0x94, 0x35, 0xc0, 0xf9, 0xe4, 0x35, 0x2b, 0x0a, 0xba, 0xe0, 0xbb, 0xd0,
	0xcf, 0x94, 0x9c, 0xa6, 0x0d, 0xed, 0x1e, 0x8a, 0xe3, 0x1c, 0xcb, 0x2a, 0x67, 0xa2, 0x58, 0xa6,
	0x93, 0x7a, 0x99, 0xb6, 0xef, 0x7c, 0x48, 0xea, 0x93, 0x7a, 0x79, 0x8a, 0x4a, 0xb4, 0x33, 0xca,
	0xb0, 0xa2, 0x65, 0x67, 0xb3, 0x66, 0x48, 0x6a, 0x6f, 0x17, 0x3f, 0xb7, 0xa7, 0xa5, 0xc0, 0x78,
	0xda, 0xaf, 0x57, 0x9f, 0xe7, 0xee, 0x2d, 0xea, 0x9e, 0x64, 0xeb, 0x89, 0xfe, 0xec, 0xe0, 0x1b,
	0x5d, 0x30, 0xfd, 0x16, 0x99, 0x1b, 0xa6, 0xdf, 0xb6, 0x98, 0xa3, 0x38, 0xa6, 0x1c, 0x61, 0xd5,
	0x6c, 0xf1, 0xd8, 0xe7, 0x08, 0x09, 0x5e, 0xfb, 0xc4, 0xb1, 0xb3, 0x82, 0xd7, 0x1e, 0xb9, 0x94,
	0xb6, 0x02, 0xa6, 0x6e, 0x59, 0xa9, 0x59, 0x85, 0xa9, 0x6b, 0x73, 0xba, 0x91, 0xf1, 0x49, 0x29,
	0xac, 0x59, 0x96, 0xdc, 0xe7, 0x35, 0x2a, 0x2e, 0x96, 0x25, 0xc7, 0xcd, 0x4b, 0xa6, 0x53, 0x76,
	0xc5, 0xaa, 0xdc, 0xa5, 0x75, 0x70, 0xc9, 0xf4, 0x31, 0xca, 0xf1, 0x0f, 0xf6, 0x06, 0x90, 0xbc,
	0x7f, 0x6f, 0xf2, 0xf4, 0x81, 0xf7, 0x46, 0x5b, 0xeb, 0x9e, 0x4e, 0xff, 0x93, 0xed, 0xc4, 0xaf,
	0x99, 0x90, 0x8d, 0x97, 0x47, 0x30, 0xc8, 0xea, 0x2a, 0xbd, 0x79, 0x15, 0x61, 0x56, 0x57, 0x17,
	0xf6, 0x36, 0xee, 0x43, 0x30, 0x15, 0x52, 0xe8, 0x4b, 0x9e, 0xfb, 0x0c, 0xf4, 0x72, 0xfc, 0x8b,
	0xed, 0x0f, 0xaf, 0xb0, 0xf0, 0x7c, 0x5b, 0x9f, 0x5d, 0xb7, 0xf5, 0x99, 0xc8, 0x9b, 0x36, 0xb5,
	0xd1, 0x6a, 0x53, 0x7b, 0xd0, 0x35, 0xc2, 0x14, 0xbe, 0x23, 0x5a, 0x01, 0x6b, 0x3a, 0x57, 0x92,
	0x99, 0x76, 0x2b, 0x0a, 0xad, 0x06, 0x9b, 0xd1, 0x77, 0x4d, 0xac, 0x9c, 0x53, 0xac, 0x8f, 0xa0,
	0x27, 0x72, 0x3c, 0x3c, 0x9d, 0xbd, 0x9b, 0x74, 0x45, 0x7e, 0x26, 0x34, 0xaa, 0xf1, 0x3c, 0x4d,
	0x0b, 0xec, 0x66, 0x75, 0x35, 0xce, 0xe3, 0x97, 0xf6, 0xe8, 0x6f, 0x4a, 0x2e, 0x5f, 0xd6, 0x32,
	0x33, 0x42, 0x49, 0xe4, 0x96, 0x33, 0xc3, 0x1c, 0x9e, 0xd6, 0x78, 0x1d, 0x42, 0xa7, 0xac, 0x28,
	0x52, 0x55, 0x72, 0xe9, 0x4e, 0x1c, 0x0a, 0x7d, 0x5c, 0x14, 0x88, 0x8d, 0x8f, 0x60, 0x8f, 0x68,
	0x88, 0xa9, 0x79, 0xf1, 0x2e, 0xbb, 0x64, 0x72, 0x66, 0xd9, 0xe0, 0xb3, 0x2e, 0x4b, 0x7e, 0xfd,
	0x18, 0xf8, 0xac, 0xcb, 0xd2, 0x96, 0xcc, 0x2b, 0xb8, 0x83, 0xa0, 0xe3, 0xcc, 0x2c, 0x84, 0x59,
	0xfe, 0x87, 0x07, 0xfc, 0xbb, 0x07, 0x81, 0xed, 0x54, 0x53, 0x15, 0x9d, 0xb4, 0x26, 0xa6, 0x90,
	0x53, 0x45, 0xd7, 0x3e, 0x78, 0xf2, 0xf0, 0x86, 0x8b, 0xdb, 0x93, 0xf7, 0x7a, 0xa0, 0x92, 0x8f,
	0x67, 0x00, 0x76, 0xee, 0x90, 0x83, 0x0d, 0x72, 0x70, 0x7f, 0xc5, 0x41, 0x33, 0x2c, 0x93, 0xb0,
	0x68, 0xe6, 0xe6, 0x53, 0x08, 0x73, 0xae, 0x33, 0x8b, 0xdc, 0x24, 0xe4, 0xbd, 0x15, 0xa4, 0x1f,
	0x57, 0x49, 0x90, 0xfb, 0xc1, 0xf5, 0x0c, 0x60, 0x82, 0x03, 0xc5, 0x02, 0xb7, 0xd6, 0x84, 0x6c,
	0x66, 0x4e, 0x12, 0x4e, 0x9a, 0xf1, 0xf3, 0x02, 0x76, 0x84, 0xef, 0xd1, 0x16, 0xde, 0x25, 0xf8,
	0xa3, 0x15, 0xf8, 0x8d, 0x56, 0x9e, 0x0c, 0xc5, 0x8d, 0xce, 0xfe, 0xd4, 0x35, 0x4a, 0xf2, 0xd0,
	0x5b, 0xc3, 0xdc, 0xb7, 0x55, 0xdb, 0x2e, 0x3d, 0x6e, 0x8e, 0x99, 0x41, 0xb8, 0xfe, 0x1a, 0x9c,
	0x6f, 0x50, 0x49, 0x30, 0xf7, 0xad, 0xea, 0x14, 0x76, 0xe6, 0x0c, 0x67, 0x3b, 0xd5, 0x18, 0x82,
	0x83, 0x35, 0x2f, 0xd5, 0xae, 0xcc, 0x64, 0x7b, 0xde, 0xae, 0xd3, 0x67, 0x7e, 0xe4, 0x91, 0x83,
	0x70, 0xcd, 0xb5, 0x35, 0xa5, 0xe8, 0xc6, 0x61, 0x0b, 0x9a, 0x73, 0x0b, 0x85, 0xf5, 0x50, 0x5b,
	0x59, 0x04, 0x75, 0x45, 0x76, 0x0c, 0x43, 0xac, 0x83, 0x74, 0x5a, 0xbb, 0xeb, 0x1a, 0xac, 0x61,
	0xde, 0x2e, 0xac, 0x64, 0xa0, 0xac, 0x44, 0x2e, 0xbe, 0x87, 0x70, 0x26, 0xa6, 0xc6, 0xc2, 0xb7,
	0x09, 0xfe, 0xc9, 0x6a, 0xf0, 0x5b, 0xf5, 0x94, 0x04, 0x88, 0x71, 0xb7, 0xb7, 0xcd, 0x6c, 0xe1,
	0xa4, 0x28, 0x8f, 0x86, 0xe4, 0x62, 0x7f, 0xc5, 0xc5, 0xad, 0xea, 0x4a, 0x06, 0x0e, 0x45, 0x4e,
	0xbe, 0x85, 0x61, 0xa6, 0xa4, 0x4c, 0xf5, 0xc2, 0xd5, 0x4a, 0x4e, 0x5e, 0x46, 0x37, 0xbc, 0x9c,
	0x2a, 0x29, 0x7f, 0x5e, 0xd8, 0x32, 0x19, 0x64, 0xd7, 0x42, 0x7c, 0x0a, 0x83, 0xd6, 0x1e, 0xb6,
	0x98, 0x49, 0xad, 0x7d, 0xb7, 0x1c, 0x26, 0xdd, 0x49, 0xad, 0xc7, 0x39, 0x36, 0xb0, 0xac, 0x10,
	0x5c, 0x9a, 0xb4, 0x54, 0xda, 0x35, 0xbc, 0xd0, 0x6a, 0xce, 0x95, 0x8e, 0xff, 0xea, 0xe0, 0xe0,
	0xc4, 0xb4, 0xc2, 0xa2, 0x78, 0xcf, 0x0f, 0xf8, 0x7d, 0xad, 0x32, 0x82, 0x2d, 0x4c, 0x3f, 0xff,
	0x91, 0xc2, 0x35, 0xb6, 0x4f, 0x9a, 0xc6, 0x7e, 0xe6, 0x90, 0x70, 0xfd, 0x35, 0xeb, 0xb6, 0xbf,
	0x66, 0x0f, 0x20, 0x5c, 0x88, 0x32, 0xb5, 0x3b, 0x6e, 0xda, 0x2c, 0x44, 0x79, 0x46, 0x9b, 0xfe,
	0x47, 0xab, 0x64, 0x21, 0x24, 0xb7, 0x5f, 0xcf, 0x47, 0xd7, 0x3f, 0xda, 0x37, 0xa4, 0xa6, 0x2f,
	0xea, 0x03, 0x08, 0x85, 0x76, 0x76, 0xa3, 0x8f, 0xed, 0x14, 0x10, 0xda, 0x1a, 0x4c, 0x7a, 0x74,
	0x81, 0x47, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x69, 0xea, 0x9c, 0x02, 0x0c, 0x00, 0x00,
}
